// components/breadcrumbs.tsx
'use client'

import { Button } from '@/components/ui/button'
import { ChevronRight, Home, List, LayoutGrid, FolderPlus, FilePlus, Trash2 } from 'lucide-react'

interface BreadcrumbsProps {
  currentPath: string
  onNavigate: (path: string) => void
  onFolderHover: (path: string) => void
  isEditable: boolean
  onCreateFolder: () => void
  onCreateFile: () => void
  onDeleteFolder: () => void
  showDeleteButton: boolean
  viewMode: 'list' | 'grid'
  onViewModeChange: (mode: 'list' | 'grid') => void
}

export function Breadcrumbs({
  currentPath,
  onNavigate,
  onFolderHover,
  isEditable,
  onCreateFolder,
  onCreateFile,
  onDeleteFolder,
  showDeleteButton,
  viewMode,
  onViewModeChange,
}: BreadcrumbsProps) {
  // Build breadcrumb path
  const pathParts = currentPath ? currentPath.split(/[/\\]/).filter(Boolean) : []
  const breadcrumbs = [
    { name: 'Home', path: '' },
    ...pathParts.map((part, index) => ({
      name: part,
      path: pathParts.slice(0, index + 1).join('/'),
    })),
  ]

  return (
    <div className='p-2 lg:p-3 border-b border-border bg-muted/30 shrink-0'>
      <div className='flex items-center justify-between gap-2 lg:gap-4'>
        <div className='flex items-center gap-1 lg:gap-2 flex-wrap'>
          {breadcrumbs.map((crumb, index) => (
            <div key={crumb.path} className='flex items-center gap-2'>
              {index > 0 && <ChevronRight className='h-4 w-4 text-muted-foreground' />}
              <Button
                variant={index === breadcrumbs.length - 1 ? 'default' : 'ghost'}
                size='sm'
                onClick={() => onNavigate(crumb.path)}
                onMouseEnter={() => onFolderHover(crumb.path)}
                className='gap-2'
              >
                {index === 0 && <Home className='h-4 w-4' />}
                {crumb.name}
              </Button>
            </div>
          ))}
        </div>
        <div className='flex gap-1 items-center'>
          {isEditable && (
            <>
              <Button
                variant='outline'
                size='icon'
                onClick={onCreateFolder}
                title='Create new folder'
              >
                <FolderPlus className='h-4 w-4' />
              </Button>
              <Button variant='outline' size='icon' onClick={onCreateFile} title='Create new file'>
                <FilePlus className='h-4 w-4' />
              </Button>
              {/* Show delete button only when inside an empty folder */}
              {showDeleteButton && (
                <Button
                  variant='outline'
                  size='icon'
                  onClick={onDeleteFolder}
                  className='text-destructive hover:text-destructive'
                  title='Delete this empty folder'
                >
                  <Trash2 className='h-4 w-4' />
                </Button>
              )}
              <div className='w-px h-6 bg-border mx-1' />
            </>
          )}
          <Button
            variant={viewMode === 'list' ? 'default' : 'ghost'}
            size='sm'
            onClick={() => onViewModeChange('list')}
          >
            <List className='h-4 w-4' />
          </Button>
          <Button
            variant={viewMode === 'grid' ? 'default' : 'ghost'}
            size='sm'
            onClick={() => onViewModeChange('grid')}
          >
            <LayoutGrid className='h-4 w-4' />
          </Button>
        </div>
      </div>
    </div>
  )
}

// solid/src/file-browser/Breadcrumbs.tsx
import { cn } from '@/lib/utils'
import ChevronRight from 'lucide-solid/icons/chevron-right'
import House from 'lucide-solid/icons/house'
import { createMemo, For, Show } from 'solid-js'

type BreadcrumbsProps = {
  currentPath: string
  onNavigate: (path: string) => void
}

export function Breadcrumbs(props: BreadcrumbsProps) {
  const crumbs = createMemo(() => {
    const parts = props.currentPath ? props.currentPath.split(/[/\\]/).filter(Boolean) : []
    return [
      { name: 'Home', path: '' },
      ...parts.map((part, index) => ({
        name: part,
        path: parts.slice(0, index + 1).join('/'),
      })),
    ]
  })

  return (
    <nav class='flex items-center gap-1 lg:gap-2 flex-wrap min-w-0 flex-1' aria-label='Breadcrumb'>
      <For each={crumbs()}>
        {(crumb, index) => (
          <div class='flex items-center gap-2'>
            <Show when={index() > 0}>
              <ChevronRight
                class='h-4 w-4 shrink-0 text-muted-foreground'
                size={16}
                stroke-width={2}
              />
            </Show>
            <button
              type='button'
              class={cn(
                'inline-flex items-center justify-center gap-1.5 rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring h-8 px-2.5 shrink-0',
                index() === crumbs().length - 1
                  ? 'bg-primary text-primary-foreground shadow-sm hover:bg-primary/90'
                  : 'text-foreground hover:bg-accent hover:text-accent-foreground',
              )}
              onClick={() => props.onNavigate(crumb.path)}
            >
              <Show when={index() === 0}>
                <House class='h-4 w-4 shrink-0' size={16} stroke-width={2} />
              </Show>
              {crumb.name}
            </button>
          </div>
        )}
      </For>
    </nav>
  )
}
