// components/kb-dashboard.tsx
import { useCallback, useEffect, useRef, memo } from 'react'
import { useQuery } from '@tanstack/react-query'
import { api } from '@/lib/api'
import { FileText } from 'lucide-react'
import { queryKeys } from '@/lib/query-keys'

interface RecentFile {
  path: string
  name: string
  modifiedAt: string
}

interface KbDashboardProps {
  scopePath: string
  onFileClick: (path: string) => void
  shareToken?: string
  dir?: string
}

const RecentFileButton = memo(function RecentFileButton({
  file,
  onFileClick,
}: {
  file: RecentFile
  onFileClick: (path: string) => void
}) {
  const onClick = useCallback(() => {
    onFileClick(file.path)
  }, [onFileClick, file.path])
  return (
    <button
      type='button'
      onClick={onClick}
      className='flex items-center gap-1 md:gap-1.5 px-1.5 py-1 md:px-2 md:py-1.5 rounded border border-border bg-background hover:bg-muted/50 transition-colors text-left shrink-0'
    >
      <FileText className='h-4 w-4 shrink-0 text-muted-foreground' />
      <span className='truncate text-sm font-medium'>{file.name}</span>
      <span className='text-xs text-muted-foreground shrink-0'>
        {formatRelativeTime(file.modifiedAt)}
      </span>
    </button>
  )
})

function formatRelativeTime(dateStr: string): string {
  const date = new Date(dateStr)
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffMins = Math.floor(diffMs / 60000)
  const diffHours = Math.floor(diffMs / 3600000)
  const diffDays = Math.floor(diffMs / 86400000)
  if (diffMins < 1) return 'Just now'
  if (diffMins < 60) return `${diffMins}m ago`
  if (diffHours < 24) return `${diffHours}h ago`
  if (diffDays < 7) return `${diffDays}d ago`
  return date.toLocaleDateString()
}

export function KbDashboard({ scopePath, onFileClick, shareToken, dir }: KbDashboardProps) {
  const { data: directData, isLoading: directLoading } = useQuery({
    queryKey: queryKeys.kbRecent(scopePath),
    queryFn: () =>
      api<{ results: RecentFile[] }>(`/api/kb/recent?root=${encodeURIComponent(scopePath)}`),
    enabled: !shareToken,
  })
  const { data: shareData, isLoading: shareLoading } = useQuery({
    queryKey: shareToken ? queryKeys.shareKbRecent(shareToken, dir) : queryKeys.shareKbRecent(),
    queryFn: () => {
      const params = new URLSearchParams()
      if (dir) params.set('dir', dir)
      return api<{ results: RecentFile[] }>(`/api/share/${shareToken}/kb/recent?${params}`)
    },
    enabled: !!shareToken,
  })
  const recent = ((shareToken ? shareData : directData)?.results || []) as RecentFile[]
  const isLoading = shareToken ? shareLoading : directLoading

  const scrollRef = useRef<HTMLDivElement>(null)

  const handleWheel = useCallback((e: WheelEvent) => {
    const el = scrollRef.current
    if (!el || el.scrollWidth <= el.clientWidth) return
    e.preventDefault()
    el.scrollLeft += e.deltaY
  }, [])

  useEffect(() => {
    const el = scrollRef.current
    if (!el) return
    el.addEventListener('wheel', handleWheel, { passive: false })
    return () => el.removeEventListener('wheel', handleWheel)
  }, [handleWheel])

  if (isLoading || !recent?.length) {
    return null
  }

  return (
    <div
      ref={scrollRef}
      data-testid='kb-recent-strip'
      className='min-w-0 shrink-0 overflow-x-auto scrollbar-none border-b border-border bg-muted/20 px-1.5 py-1.5 md:px-2 md:py-2'
    >
      <div className='flex w-max min-w-full flex-nowrap gap-1 md:gap-1.5'>
        {recent.map((file) => (
          <RecentFileButton key={file.path} file={file} onFileClick={onFileClick} />
        ))}
      </div>
    </div>
  )
}

// solid/src/file-browser/KbDashboard.tsx
import { useQuery } from '@tanstack/solid-query'
import { api } from '@/lib/api'
import { queryKeys } from '@/lib/query-keys'
import FileText from 'lucide-solid/icons/file-text'
import { For, Show, createEffect, createMemo, createSignal, onCleanup } from 'solid-js'

type RecentFile = { path: string; name: string; modifiedAt: string }

function formatRelativeTime(dateStr: string): string {
  const date = new Date(dateStr)
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffMins = Math.floor(diffMs / 60000)
  const diffHours = Math.floor(diffMs / 3600000)
  const diffDays = Math.floor(diffMs / 86400000)
  if (diffMins < 1) return 'Just now'
  if (diffMins < 60) return `${diffMins}m ago`
  if (diffHours < 24) return `${diffHours}h ago`
  if (diffDays < 7) return `${diffDays}d ago`
  return date.toLocaleDateString()
}

type Props = {
  scopePath: string
  onFileClick: (path: string) => void
  shareToken?: string
  dir?: string
}

export function KbDashboard(props: Props) {
  const directQuery = useQuery(() => ({
    queryKey: queryKeys.kbRecent(props.scopePath),
    queryFn: () =>
      api<{ results: RecentFile[] }>(`/api/kb/recent?root=${encodeURIComponent(props.scopePath)}`),
    enabled: !props.shareToken && !!props.scopePath,
  }))

  const shareQuery = useQuery(() => ({
    queryKey: queryKeys.shareKbRecent(props.shareToken!, props.dir),
    queryFn: () => {
      const params = new URLSearchParams()
      if (props.dir) params.set('dir', props.dir)
      return api<{ results: RecentFile[] }>(`/api/share/${props.shareToken}/kb/recent?${params}`)
    },
    enabled: !!props.shareToken,
  }))

  const recent = createMemo(() => {
    const data = props.shareToken ? shareQuery.data : directQuery.data
    return (data?.results ?? []) as RecentFile[]
  })

  const isLoading = createMemo(() =>
    props.shareToken ? shareQuery.isLoading : directQuery.isLoading,
  )

  const [scrollEl, setScrollEl] = createSignal<HTMLDivElement | null>(null)

  function handleWheel(e: WheelEvent) {
    const el = scrollEl()
    if (!el || el.scrollWidth <= el.clientWidth) return
    e.preventDefault()
    el.scrollLeft += e.deltaY
  }

  createEffect(() => {
    const el = scrollEl()
    if (!el) return
    el.addEventListener('wheel', handleWheel, { passive: false })
    onCleanup(() => el.removeEventListener('wheel', handleWheel))
  })

  return (
    <Show when={!isLoading() && recent().length > 0}>
      <div
        ref={setScrollEl}
        data-testid='kb-recent-strip'
        class='min-w-0 shrink-0 overflow-x-auto scrollbar-none border-b border-border bg-muted/20 px-1.5 py-1.5 md:px-2 md:py-2'
      >
        <div class='flex w-max min-w-full flex-nowrap gap-1 md:gap-1.5'>
          <For each={recent()}>
            {(file) => (
              <button
                type='button'
                class='flex shrink-0 items-center gap-1 rounded border border-border bg-background px-1.5 py-1 text-left transition-colors hover:bg-muted/50 md:gap-1.5 md:px-2 md:py-1.5'
                onClick={() => props.onFileClick(file.path)}
              >
                <FileText class='h-4 w-4 shrink-0 text-muted-foreground' stroke-width={2} />
                <span class='truncate text-sm font-medium'>{file.name}</span>
                <span class='shrink-0 text-xs text-muted-foreground'>
                  {formatRelativeTime(file.modifiedAt)}
                </span>
              </button>
            )}
          </For>
        </div>
      </div>
    </Show>
  )
}
