// components/move-to-dialog.tsx
import { useState, useEffect, useMemo, useCallback } from 'react'
import { useQuery } from '@tanstack/react-query'
import { api } from '@/lib/api'
import { FileItem } from '@/lib/types'
import { Folder, ArrowUp, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog'

type MoveOrCopyMode = 'move' | 'copy'

interface MoveToDialogProps {
  isOpen: boolean
  onClose: () => void
  fileName: string
  filePath: string
  onMove: (destinationDir: string) => void
  isPending?: boolean
  error?: Error | null
  editableFolders?: string[]
  shareToken?: string
  shareRootPath?: string
  /** When 'copy', shows "Copy to" UI; destination must be editable folder */
  mode?: MoveOrCopyMode
}

export function MoveToDialog({
  isOpen,
  onClose,
  fileName,
  filePath,
  onMove,
  isPending = false,
  error = null,
  editableFolders = [],
  shareToken,
  shareRootPath,
  mode = 'move',
}: MoveToDialogProps) {
  const isCopy = mode === 'copy'
  const sourceDir = useMemo(() => {
    const parts = filePath.split(/[/\\]/).filter(Boolean)
    return parts.slice(0, -1).join('/')
  }, [filePath])

  const sourceRoot = useMemo(() => {
    if (shareToken) return ''
    const normalized = filePath.replace(/\\/g, '/')
    for (const folder of editableFolders) {
      const nf = folder.replace(/\\/g, '/')
      if (normalized === nf || normalized.startsWith(nf + '/')) return nf
    }
    return editableFolders[0]?.replace(/\\/g, '/') || ''
  }, [filePath, editableFolders, shareToken])

  const [selectedRoot, setSelectedRoot] = useState(sourceRoot)
  const [browsePath, setBrowsePath] = useState(sourceDir)

  useEffect(() => {
    if (isOpen) {
      const root = sourceRoot
      const dir = sourceDir.replace(/\\/g, '/')
      setSelectedRoot(root)
      if (shareToken || dir === root || dir.startsWith(root + '/')) {
        setBrowsePath(dir)
      } else {
        setBrowsePath(root)
      }
    }
  }, [isOpen, sourceRoot, sourceDir, shareToken])

  const normalizedBrowse = browsePath.replace(/\\/g, '/')
  const normalizedRoot = selectedRoot.replace(/\\/g, '/')

  const stripShareRoot = useCallback(
    (p: string) => {
      if (!shareRootPath) return p
      const norm = p.replace(/\\/g, '/')
      const root = shareRootPath.replace(/\\/g, '/')
      return norm.startsWith(root + '/') ? norm.slice(root.length + 1) : norm
    },
    [shareRootPath],
  )

  const { data: shareFilesData, isLoading: shareLoading } = useQuery({
    queryKey: ['share-files', shareToken, browsePath],
    queryFn: () =>
      api<{ files: FileItem[] }>(
        `/api/share/${shareToken}/files?dir=${encodeURIComponent(browsePath)}`,
      ),
    enabled: isOpen && !!shareToken,
    staleTime: 1000 * 30,
  })
  const { data: localFilesData, isLoading: localLoading } = useQuery({
    queryKey: ['files', browsePath],
    queryFn: () => api<{ files: FileItem[] }>(`/api/files?dir=${encodeURIComponent(browsePath)}`),
    enabled: isOpen && !shareToken,
    staleTime: 1000 * 30,
  })
  const isLoading = shareToken ? shareLoading : localLoading
  const folders = useMemo(() => {
    const rawFiles: FileItem[] = (shareToken ? shareFilesData?.files : localFilesData?.files) || []
    const normalizedFilePath = filePath.replace(/\\/g, '/')
    return rawFiles
      .filter((f) => f.isDirectory)
      .map((f) => ({
        name: f.name,
        navPath: shareToken ? stripShareRoot(f.path) : f.path.replace(/\\/g, '/'),
      }))
      .filter((f) => {
        if (f.navPath === normalizedFilePath) return false
        if (f.navPath.startsWith(normalizedFilePath + '/')) return false
        return true
      })
  }, [shareToken, shareFilesData, localFilesData, filePath, stripShareRoot])

  const canGoUp = shareToken ? !!browsePath : normalizedBrowse !== normalizedRoot

  const goUp = useCallback(() => {
    const parts = browsePath.split(/[/\\]/).filter(Boolean)
    setBrowsePath(parts.slice(0, -1).join('/'))
  }, [browsePath])

  const handleRootChange = useCallback((root: string) => {
    const normalized = root.replace(/\\/g, '/')
    setSelectedRoot(normalized)
    setBrowsePath(normalized)
  }, [])

  const isSameAsSource = normalizedBrowse === sourceDir.replace(/\\/g, '/')

  const displayPath = useMemo(() => {
    if (shareToken) {
      return browsePath ? `/${browsePath}` : '/'
    }
    if (normalizedBrowse === normalizedRoot) return '/'
    return '/' + normalizedBrowse.slice(normalizedRoot.length + 1)
  }, [browsePath, normalizedBrowse, normalizedRoot, shareToken])

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className='sm:max-w-md'>
        <DialogHeader>
          <DialogTitle className='truncate pr-6'>
            {isCopy ? 'Copy' : 'Move'} &ldquo;{fileName}&rdquo;
          </DialogTitle>
          <DialogDescription>
            {isCopy ? 'Choose an editable destination folder' : 'Choose a destination folder'}
          </DialogDescription>
        </DialogHeader>

        {!shareToken && editableFolders.length > 1 && (
          <div className='flex gap-1.5 flex-wrap'>
            {editableFolders.map((folder) => {
              const nf = folder.replace(/\\/g, '/')
              return (
                <Button
                  key={folder}
                  variant={selectedRoot === nf ? 'default' : 'outline'}
                  size='sm'
                  onClick={() => handleRootChange(folder)}
                  className='text-xs h-7'
                >
                  {folder}
                </Button>
              )
            })}
          </div>
        )}

        <div className='flex items-center gap-1.5 text-sm text-muted-foreground px-1'>
          <Folder className='h-3.5 w-3.5 shrink-0' />
          <span className='font-mono text-xs truncate'>{displayPath}</span>
        </div>

        <div className='border rounded-md max-h-64 overflow-y-auto'>
          {isLoading ? (
            <div className='flex items-center justify-center py-8'>
              <Loader2 className='h-5 w-5 animate-spin text-muted-foreground' />
            </div>
          ) : (
            <div className='divide-y'>
              {canGoUp && (
                <button
                  type='button'
                  onClick={goUp}
                  className='flex items-center gap-2.5 w-full px-3 py-2 hover:bg-muted/50 text-left transition-colors'
                >
                  <ArrowUp className='h-4 w-4 text-muted-foreground shrink-0' />
                  <span className='text-sm font-medium'>..</span>
                </button>
              )}
              {folders.length === 0 && !canGoUp && (
                <div className='px-3 py-8 text-center text-sm text-muted-foreground'>
                  No subfolders
                </div>
              )}
              {folders.map((folder) => (
                <button
                  key={folder.navPath}
                  type='button'
                  onClick={() => setBrowsePath(folder.navPath)}
                  className='flex items-center gap-2.5 w-full px-3 py-2 hover:bg-muted/50 text-left transition-colors'
                >
                  <Folder className='h-4 w-4 text-muted-foreground shrink-0' />
                  <span className='text-sm truncate'>{folder.name}</span>
                </button>
              ))}
            </div>
          )}
        </div>

        {error && (
          <div className='rounded-md bg-destructive/10 border border-destructive/50 px-3 py-2 text-sm text-destructive'>
            {error.message}
          </div>
        )}

        <div className='flex justify-end gap-2'>
          <Button variant='outline' onClick={onClose} disabled={isPending}>
            Cancel
          </Button>
          <Button onClick={() => onMove(browsePath)} disabled={isSameAsSource || isPending}>
            {isPending ? (isCopy ? 'Copying...' : 'Moving...') : isCopy ? 'Copy here' : 'Move here'}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}

// solid/src/file-browser/MoveToDialog.tsx
import { api } from '@/lib/api'
import type { FileItem } from '@/lib/types'
import ArrowUp from 'lucide-solid/icons/arrow-up'
import Folder from 'lucide-solid/icons/folder'
import LoaderCircle from 'lucide-solid/icons/loader-circle'
import { createMemo, createResource, createSignal, For, Show } from 'solid-js'

type MoveOrCopyMode = 'move' | 'copy'

type MoveToDialogProps = {
  onClose: () => void
  fileName: string
  filePath: string
  onConfirm: (destinationDir: string) => void
  isPending: boolean
  error: Error | null | undefined
  editableFolders: string[]
  mode?: MoveOrCopyMode
}

function computeSourceRoot(filePath: string, editableFolders: string[]) {
  const normalized = filePath.replace(/\\/g, '/')
  for (const folder of editableFolders) {
    const nf = folder.replace(/\\/g, '/')
    if (normalized === nf || normalized.startsWith(nf + '/')) return nf
  }
  return editableFolders[0]?.replace(/\\/g, '/') || ''
}

function computeInitialBrowse(filePath: string, editableFolders: string[]) {
  const root = computeSourceRoot(filePath, editableFolders)
  const parts = filePath.split(/[/\\]/).filter(Boolean)
  const dir = parts.slice(0, -1).join('/').replace(/\\/g, '/')
  if (dir === root || dir.startsWith(root + '/')) return dir
  return root
}

export function MoveToDialog(props: MoveToDialogProps) {
  const isCopy = () => (props.mode ?? 'move') === 'copy'

  const [selectedRoot, setSelectedRoot] = createSignal(
    computeSourceRoot(props.filePath, props.editableFolders),
  )
  const [browsePath, setBrowsePath] = createSignal(
    computeInitialBrowse(props.filePath, props.editableFolders),
  )

  const [dirFiles] = createResource(browsePath, async (dir) => {
    const { files } = await api<{ files: FileItem[] }>(`/api/files?dir=${encodeURIComponent(dir)}`)
    return files
  })

  const sourceDir = createMemo(() => {
    const parts = props.filePath.split(/[/\\]/).filter(Boolean)
    return parts.slice(0, -1).join('/')
  })

  const normalizedBrowse = createMemo(() => browsePath().replace(/\\/g, '/'))
  const normalizedRoot = createMemo(() => selectedRoot().replace(/\\/g, '/'))

  const folders = createMemo(() => {
    const rawFiles: FileItem[] = dirFiles() ?? []
    const normalizedFilePath = props.filePath.replace(/\\/g, '/')
    return rawFiles
      .filter((f) => f.isDirectory)
      .map((f) => ({
        name: f.name,
        navPath: f.path.replace(/\\/g, '/'),
      }))
      .filter((f) => {
        if (f.navPath === normalizedFilePath) return false
        if (f.navPath.startsWith(normalizedFilePath + '/')) return false
        return true
      })
  })

  const canGoUp = createMemo(() => normalizedBrowse() !== normalizedRoot())

  function goUp() {
    const parts = browsePath().split(/[/\\]/).filter(Boolean)
    setBrowsePath(parts.slice(0, -1).join('/'))
  }

  function handleRootChange(root: string) {
    const normalized = root.replace(/\\/g, '/')
    setSelectedRoot(normalized)
    setBrowsePath(normalized)
  }

  const isSameAsSource = createMemo(() => normalizedBrowse() === sourceDir().replace(/\\/g, '/'))

  const displayPath = createMemo(() => {
    if (normalizedBrowse() === normalizedRoot()) return '/'
    return '/' + normalizedBrowse().slice(normalizedRoot().length + 1)
  })

  return (
    <div
      class='fixed inset-0 z-60 flex items-center justify-center bg-black/50 p-4'
      role='presentation'
      onClick={() => props.onClose()}
    >
      <div
        role='dialog'
        aria-modal='true'
        class='w-full max-w-md rounded-lg border border-border bg-card text-card-foreground shadow-lg p-6'
        onClick={(e) => e.stopPropagation()}
      >
        <h2 class='text-lg font-semibold truncate pr-6'>
          {isCopy() ? 'Copy' : 'Move'} &quot;{props.fileName}&quot;
        </h2>
        <p class='text-sm text-muted-foreground mt-1'>
          {isCopy() ? 'Choose an editable destination folder' : 'Choose a destination folder'}
        </p>

        <Show when={props.editableFolders.length > 1}>
          <div class='flex gap-1.5 flex-wrap mt-3'>
            <For each={props.editableFolders}>
              {(folder) => {
                const nf = folder.replace(/\\/g, '/')
                return (
                  <button
                    type='button'
                    class='text-xs h-7 px-2 rounded-md border text-sm font-medium'
                    classList={{
                      'bg-primary text-primary-foreground border-primary': selectedRoot() === nf,
                      'border-input bg-background hover:bg-accent': selectedRoot() !== nf,
                    }}
                    onClick={() => handleRootChange(folder)}
                  >
                    {folder}
                  </button>
                )
              }}
            </For>
          </div>
        </Show>

        <div class='flex items-center gap-1.5 text-sm text-muted-foreground px-1 mt-3'>
          <Folder class='h-3.5 w-3.5 shrink-0' stroke-width={2} />
          <span class='font-mono text-xs truncate'>{displayPath()}</span>
        </div>

        <div class='border border-border rounded-md max-h-64 overflow-y-auto mt-2'>
          <Show
            when={!dirFiles.loading}
            fallback={
              <div class='flex items-center justify-center py-8'>
                <LoaderCircle class='h-5 w-5 animate-spin text-muted-foreground' stroke-width={2} />
              </div>
            }
          >
            <Show when={dirFiles.error}>
              <div class='px-3 py-6 text-center text-sm text-destructive'>
                {(dirFiles.error as Error).message}
              </div>
            </Show>
            <Show when={!dirFiles.error}>
              <div class='divide-y divide-border'>
                <Show when={canGoUp()}>
                  <button
                    type='button'
                    class='flex items-center gap-2.5 w-full px-3 py-2 hover:bg-muted/50 text-left transition-colors'
                    onClick={() => goUp()}
                  >
                    <ArrowUp class='h-4 w-4 text-muted-foreground shrink-0' stroke-width={2} />
                    <span class='text-sm font-medium'>..</span>
                  </button>
                </Show>
                <Show when={folders().length === 0 && !canGoUp()}>
                  <div class='px-3 py-8 text-center text-sm text-muted-foreground'>
                    No subfolders
                  </div>
                </Show>
                <For each={folders()}>
                  {(folder) => (
                    <button
                      type='button'
                      class='flex items-center gap-2.5 w-full px-3 py-2 hover:bg-muted/50 text-left transition-colors'
                      onClick={() => setBrowsePath(folder.navPath)}
                    >
                      <Folder class='h-4 w-4 text-muted-foreground shrink-0' stroke-width={2} />
                      <span class='text-sm truncate'>{folder.name}</span>
                    </button>
                  )}
                </For>
              </div>
            </Show>
          </Show>
        </div>

        <Show when={props.error}>
          <p class='mt-3 text-sm text-destructive rounded-md bg-destructive/10 border border-destructive/50 px-3 py-2'>
            {props.error?.message}
          </p>
        </Show>

        <div class='flex justify-end gap-2 mt-6'>
          <button
            type='button'
            class='h-9 px-4 rounded-md border border-input bg-background text-sm font-medium hover:bg-accent'
            disabled={props.isPending}
            onClick={() => props.onClose()}
          >
            Cancel
          </button>
          <button
            type='button'
            class='h-9 px-4 rounded-md bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 disabled:opacity-50'
            disabled={isSameAsSource() || props.isPending}
            onClick={() => props.onConfirm(browsePath())}
          >
            {props.isPending
              ? isCopy()
                ? 'Copying...'
                : 'Moving...'
              : isCopy()
                ? 'Copy here'
                : 'Move here'}
          </button>
        </div>
      </div>
    </div>
  )
}
