// components/share-dialog.tsx
import { useState, useEffect, useCallback, useRef } from 'react'
import { useQueryClient, useMutation } from '@tanstack/react-query'
import { post } from '@/lib/api'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Copy, Check, Link, Trash2, ChevronDown, ChevronUp, Plus } from 'lucide-react'
import type { ShareLink, ShareRestrictions } from '@/lib/shares'
import { formatFileSize } from '@/lib/media-utils'
import { useShareLinkBase } from '@/lib/use-share-link-base'
import { queryKeys } from '@/lib/query-keys'

const SIZE_PRESETS = [
  { label: '500 MB', value: 500 * 1024 * 1024 },
  { label: '1 GB', value: 1024 * 1024 * 1024 },
  { label: '2 GB', value: 2 * 1024 * 1024 * 1024 },
  { label: '5 GB', value: 5 * 1024 * 1024 * 1024 },
  { label: '10 GB', value: 10 * 1024 * 1024 * 1024 },
]

const DEFAULT_MAX_UPLOAD_BYTES = 2 * 1024 * 1024 * 1024

interface ShareDialogProps {
  isOpen: boolean
  onClose: () => void
  filePath: string
  fileName: string
  isDirectory: boolean
  isEditable: boolean
  existingShares: ShareLink[]
}

type QuotaMode = 'unlimited' | 'preset' | 'custom'

function getQuotaMode(maxUploadBytes: number): QuotaMode {
  if (maxUploadBytes === 0) return 'unlimited'
  if (SIZE_PRESETS.some((p) => p.value === maxUploadBytes)) return 'preset'
  return 'custom'
}

function RestrictionsEditor({
  restrictions,
  onChange,
}: {
  restrictions: Required<ShareRestrictions>
  onChange: (r: Required<ShareRestrictions>) => void
}) {
  const quotaMode = getQuotaMode(restrictions.maxUploadBytes)

  const setMode = (mode: QuotaMode) => {
    if (mode === 'unlimited') onChange({ ...restrictions, maxUploadBytes: 0 })
    else if (mode === 'preset')
      onChange({ ...restrictions, maxUploadBytes: DEFAULT_MAX_UPLOAD_BYTES })
    else
      onChange({
        ...restrictions,
        maxUploadBytes: restrictions.maxUploadBytes || DEFAULT_MAX_UPLOAD_BYTES,
      })
  }

  return (
    <div className='space-y-3'>
      <label className='flex items-center gap-3 cursor-pointer'>
        <input
          type='checkbox'
          checked={restrictions.allowUpload}
          onChange={(e) => onChange({ ...restrictions, allowUpload: e.target.checked })}
          className='h-4 w-4 rounded border-input'
        />
        <div>
          <p className='text-sm font-medium'>Allow uploads & file creation</p>
          <p className='text-xs text-muted-foreground'>Create new files and folders</p>
        </div>
      </label>

      <label className='flex items-center gap-3 cursor-pointer'>
        <input
          type='checkbox'
          checked={restrictions.allowEdit}
          onChange={(e) => onChange({ ...restrictions, allowEdit: e.target.checked })}
          className='h-4 w-4 rounded border-input'
        />
        <div>
          <p className='text-sm font-medium'>Allow editing & renaming</p>
          <p className='text-xs text-muted-foreground'>
            Edit file contents, rename, and move items
          </p>
        </div>
      </label>

      <label className='flex items-center gap-3 cursor-pointer'>
        <input
          type='checkbox'
          checked={restrictions.allowDelete}
          onChange={(e) => onChange({ ...restrictions, allowDelete: e.target.checked })}
          className='h-4 w-4 rounded border-input'
        />
        <div>
          <p className='text-sm font-medium'>Allow deletion</p>
          <p className='text-xs text-muted-foreground'>Delete files and folders</p>
        </div>
      </label>

      <div className='space-y-2'>
        <p className='text-sm font-medium'>Upload size limit</p>
        <div className='flex gap-1.5'>
          {(['unlimited', 'preset', 'custom'] as const).map((mode) => (
            <Button
              key={mode}
              type='button'
              variant={quotaMode === mode ? 'default' : 'outline'}
              size='sm'
              className='h-7 text-xs capitalize'
              onClick={() => setMode(mode)}
            >
              {mode}
            </Button>
          ))}
        </div>
        {quotaMode === 'preset' && (
          <div className='flex flex-wrap gap-1.5'>
            {SIZE_PRESETS.map((preset) => (
              <Button
                key={preset.value}
                type='button'
                variant={restrictions.maxUploadBytes === preset.value ? 'default' : 'outline'}
                size='sm'
                className='h-7 text-xs'
                onClick={() => onChange({ ...restrictions, maxUploadBytes: preset.value })}
              >
                {preset.label}
              </Button>
            ))}
          </div>
        )}
        {quotaMode === 'custom' && (
          <div className='flex items-center gap-2'>
            <Input
              type='number'
              min={1}
              value={Math.round(restrictions.maxUploadBytes / (1024 * 1024))}
              onChange={(e) => {
                const mb = parseInt(e.target.value, 10)
                if (!isNaN(mb) && mb > 0) {
                  onChange({ ...restrictions, maxUploadBytes: mb * 1024 * 1024 })
                }
              }}
              className='h-7 text-xs w-24'
            />
            <span className='text-xs text-muted-foreground'>MB</span>
          </div>
        )}
      </div>
    </div>
  )
}

function extractRestrictions(share: ShareLink): Required<ShareRestrictions> {
  const r = share.restrictions || {}
  return {
    allowDelete: r.allowDelete !== false,
    allowUpload: r.allowUpload !== false,
    allowEdit: r.allowEdit !== false,
    maxUploadBytes: r.maxUploadBytes ?? DEFAULT_MAX_UPLOAD_BYTES,
  }
}

function buildShareUrl(share: ShareLink, baseOrigin: string) {
  const url = `${baseOrigin}/share/${share.token}`
  return share.passcode ? `${url}?p=${encodeURIComponent(share.passcode)}` : url
}

function ShareCard({
  share,
  isDirectory,
  isEditable,
  onRevoked,
}: {
  share: ShareLink
  isDirectory: boolean
  isEditable: boolean
  onRevoked: () => void
}) {
  const queryClient = useQueryClient()
  const shareLinkBase = useShareLinkBase()
  const [copiedLink, setCopiedLink] = useState(false)
  const [showSettings, setShowSettings] = useState(false)
  const [editable, setEditable] = useState(share.editable)
  const [restrictions, setRestrictions] = useState<Required<ShareRestrictions>>(
    extractRestrictions(share),
  )
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const initializedRef = useRef(false)

  useEffect(() => {
    setEditable(share.editable)
    setRestrictions(extractRestrictions(share))
  }, [share])

  const updateMutation = useMutation({
    mutationFn: (vars: {
      token: string
      editable: boolean
      restrictions: Required<ShareRestrictions>
    }) =>
      fetch('/api/shares', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(vars),
      }).then((r) => r.json()),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.shares() })
    },
  })

  const scheduleUpdate = useCallback(
    (newEditable: boolean, newRestrictions: Required<ShareRestrictions>) => {
      if (debounceRef.current) clearTimeout(debounceRef.current)
      debounceRef.current = setTimeout(() => {
        updateMutation.mutate({
          token: share.token,
          editable: newEditable,
          restrictions: newRestrictions,
        })
      }, 500)
    },
    [updateMutation, share.token],
  )

  const handleEditableChange = (val: boolean) => {
    setEditable(val)
    scheduleUpdate(val, restrictions)
  }

  const handleRestrictionsChange = (r: Required<ShareRestrictions>) => {
    setRestrictions(r)
    scheduleUpdate(editable, r)
  }

  useEffect(() => {
    if (!initializedRef.current) {
      initializedRef.current = true
      return
    }
  }, [editable, restrictions])

  useEffect(() => {
    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current)
    }
  }, [])

  const revokeMutation = useMutation({
    mutationFn: (vars: { token: string }) => post('/api/shares/delete', vars),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.shares() })
      onRevoked()
    },
  })

  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(buildShareUrl(share, shareLinkBase))
      setCopiedLink(true)
      setTimeout(() => setCopiedLink(false), 2000)
    } catch {
      /* ignore */
    }
  }

  const url = buildShareUrl(share, shareLinkBase)
  const used = share.usedBytes || 0
  const limit = restrictions.maxUploadBytes

  return (
    <div className='rounded-lg border p-3 space-y-3'>
      {/* Header: date + type */}
      <div className='flex items-center justify-between'>
        <p className='text-xs text-muted-foreground'>
          Created{' '}
          {new Date(share.createdAt).toLocaleDateString(undefined, {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
          })}
        </p>
        <span className='text-xs px-1.5 py-0.5 rounded bg-muted text-muted-foreground'>
          {share.isDirectory ? 'Folder' : 'File'}
        </span>
      </div>

      {/* URL + copy */}
      <div className='flex gap-2'>
        <Input value={url} readOnly className='font-mono text-xs' />
        <Button variant='outline' size='icon' onClick={handleCopyLink} title='Copy link'>
          {copiedLink ? <Check className='h-4 w-4' /> : <Copy className='h-4 w-4' />}
        </Button>
      </div>

      {share.passcode && (
        <p className='text-xs text-muted-foreground'>Passcode is included in the link.</p>
      )}

      {/* Settings toggle */}
      <Button
        variant='ghost'
        size='sm'
        className='w-full justify-between h-8'
        onClick={() => setShowSettings(!showSettings)}
      >
        <span className='text-xs'>
          {editable ? 'Editable' : 'Read-only'}
          {editable &&
            (() => {
              const denied: string[] = []
              if (!restrictions.allowUpload) denied.push('upload')
              if (!restrictions.allowEdit) denied.push('edit')
              if (!restrictions.allowDelete) denied.push('delete')
              if (denied.length > 0) return ` (no ${denied.join(', ')})`
              return ''
            })()}
          {editable && limit > 0 ? ` · ${formatFileSize(used)} / ${formatFileSize(limit)}` : ''}
          {editable && limit === 0 ? ` · ${formatFileSize(used)} (unlimited)` : ''}
        </span>
        {showSettings ? (
          <ChevronUp className='h-3.5 w-3.5' />
        ) : (
          <ChevronDown className='h-3.5 w-3.5' />
        )}
      </Button>

      {showSettings && (
        <div className='space-y-3 pt-1'>
          {/* Editable toggle */}
          {isDirectory && isEditable && (
            <label className='flex items-center gap-3 cursor-pointer'>
              <input
                type='checkbox'
                checked={editable}
                onChange={(e) => handleEditableChange(e.target.checked)}
                className='h-4 w-4 rounded border-input'
              />
              <div>
                <p className='text-sm font-medium'>Allow editing</p>
                <p className='text-xs text-muted-foreground'>
                  Recipients can create, edit, and delete files
                </p>
              </div>
            </label>
          )}

          {/* Restrictions */}
          {editable && (
            <div className='rounded-lg border p-3 space-y-3'>
              <p className='text-xs font-medium text-muted-foreground'>Restrictions</p>
              <RestrictionsEditor restrictions={restrictions} onChange={handleRestrictionsChange} />
            </div>
          )}
        </div>
      )}

      {/* Revoke */}
      <Button
        variant='destructive'
        size='sm'
        className='w-full'
        onClick={() => revokeMutation.mutate({ token: share.token })}
        disabled={revokeMutation.isPending}
      >
        <Trash2 className='h-3.5 w-3.5 mr-1.5' />
        {revokeMutation.isPending ? 'Revoking...' : 'Revoke'}
      </Button>
    </div>
  )
}

export function ShareDialog({
  isOpen,
  onClose,
  filePath,
  fileName,
  isDirectory,
  isEditable,
  existingShares,
}: ShareDialogProps) {
  const queryClient = useQueryClient()
  const [showCreate, setShowCreate] = useState(false)
  const [newEditable, setNewEditable] = useState(false)
  const [newRestrictions, setNewRestrictions] = useState<Required<ShareRestrictions>>({
    allowDelete: true,
    allowUpload: true,
    allowEdit: true,
    maxUploadBytes: DEFAULT_MAX_UPLOAD_BYTES,
  })

  useEffect(() => {
    if (isOpen) {
      setShowCreate(false)
      setNewEditable(false)
      setNewRestrictions({
        allowDelete: true,
        allowUpload: true,
        allowEdit: true,
        maxUploadBytes: DEFAULT_MAX_UPLOAD_BYTES,
      })
    }
  }, [isOpen])

  const createShareMutation = useMutation({
    mutationFn: (vars: {
      path: string
      isDirectory: boolean
      editable: boolean
      restrictions?: Required<ShareRestrictions>
    }) => post('/api/shares', vars),
    onSuccess: () => {
      setShowCreate(false)
      queryClient.invalidateQueries({ queryKey: queryKeys.shares() })
    },
  })

  const hasShares = existingShares.length > 0

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className='sm:max-w-md max-h-[85vh] overflow-y-auto'>
        <DialogHeader>
          <DialogTitle className='flex items-center gap-2'>
            <Link className='h-5 w-5' />
            Share Links
          </DialogTitle>
          <DialogDescription>
            {hasShares
              ? `${existingShares.length} share${existingShares.length > 1 ? 's' : ''} for "${fileName}"`
              : `Create a share link for "${fileName}"`}
          </DialogDescription>
        </DialogHeader>

        <div className='space-y-3'>
          {/* Create new share */}
          {showCreate ? (
            <div className='rounded-lg border border-dashed p-3 space-y-3'>
              <p className='text-sm font-medium'>New Share Link</p>

              {isDirectory && isEditable && (
                <>
                  <label className='flex items-center gap-3 cursor-pointer'>
                    <input
                      type='checkbox'
                      checked={newEditable}
                      onChange={(e) => setNewEditable(e.target.checked)}
                      className='h-4 w-4 rounded border-input'
                    />
                    <div>
                      <p className='text-sm font-medium'>Allow editing</p>
                      <p className='text-xs text-muted-foreground'>
                        Recipients can create, edit, and delete files
                      </p>
                    </div>
                  </label>

                  {newEditable && (
                    <div className='rounded-lg border p-3 space-y-3'>
                      <p className='text-xs font-medium text-muted-foreground'>Restrictions</p>
                      <RestrictionsEditor
                        restrictions={newRestrictions}
                        onChange={setNewRestrictions}
                      />
                    </div>
                  )}
                </>
              )}

              <div className='flex gap-2'>
                <Button
                  className='flex-1'
                  size='sm'
                  onClick={() =>
                    createShareMutation.mutate({
                      path: filePath,
                      isDirectory,
                      editable: newEditable,
                      ...(newEditable ? { restrictions: newRestrictions } : {}),
                    })
                  }
                  disabled={createShareMutation.isPending}
                >
                  <Link className='h-3.5 w-3.5 mr-1.5' />
                  {createShareMutation.isPending ? 'Creating...' : 'Create'}
                </Button>
                <Button variant='outline' size='sm' onClick={() => setShowCreate(false)}>
                  Cancel
                </Button>
              </div>
            </div>
          ) : (
            <Button
              variant='outline'
              className='w-full'
              size='sm'
              onClick={() => setShowCreate(true)}
            >
              <Plus className='h-3.5 w-3.5 mr-1.5' />
              Create New Share Link
            </Button>
          )}

          {/* Existing shares list (newest first) */}
          {[...existingShares]
            .sort((a, b) => b.createdAt - a.createdAt)
            .map((share) => (
              <ShareCard
                key={share.token}
                share={share}
                isDirectory={isDirectory}
                isEditable={isEditable}
                onRevoked={() => {}}
              />
            ))}

          {!hasShares && !showCreate && (
            <p className='text-sm text-muted-foreground text-center py-2'>
              No share links yet. Create one to get started.
            </p>
          )}
        </div>
      </DialogContent>
    </Dialog>
  )
}

// solid/src/file-browser/ShareDialog.tsx
import { useMutation, useQueryClient } from '@tanstack/solid-query'
import { post } from '@/lib/api'
import { queryKeys } from '@/lib/query-keys'
import type { ShareLink, ShareRestrictions } from '@/lib/shares'
import { formatFileSize } from '@/lib/media-utils'
import { createEffect, createMemo, createSignal, For, onCleanup, Show } from 'solid-js'
import Check from 'lucide-solid/icons/check'
import ChevronDown from 'lucide-solid/icons/chevron-down'
import ChevronUp from 'lucide-solid/icons/chevron-up'
import Copy from 'lucide-solid/icons/copy'
import LinkIcon from 'lucide-solid/icons/link'
import Plus from 'lucide-solid/icons/plus'
import Trash2 from 'lucide-solid/icons/trash-2'

const SIZE_PRESETS = [
  { label: '500 MB', value: 500 * 1024 * 1024 },
  { label: '1 GB', value: 1024 * 1024 * 1024 },
  { label: '2 GB', value: 2 * 1024 * 1024 * 1024 },
  { label: '5 GB', value: 5 * 1024 * 1024 * 1024 },
  { label: '10 GB', value: 10 * 1024 * 1024 * 1024 },
] as const

const DEFAULT_MAX_UPLOAD_BYTES = 2 * 1024 * 1024 * 1024

type QuotaMode = 'unlimited' | 'preset' | 'custom'

type RequiredRestrictions = Required<ShareRestrictions>

function getQuotaMode(maxUploadBytes: number): QuotaMode {
  if (maxUploadBytes === 0) return 'unlimited'
  if (SIZE_PRESETS.some((p) => p.value === maxUploadBytes)) return 'preset'
  return 'custom'
}

function extractRestrictions(share: ShareLink): RequiredRestrictions {
  const r = share.restrictions || {}
  return {
    allowDelete: r.allowDelete !== false,
    allowUpload: r.allowUpload !== false,
    allowEdit: r.allowEdit !== false,
    maxUploadBytes: r.maxUploadBytes ?? DEFAULT_MAX_UPLOAD_BYTES,
  }
}

function buildShareUrl(share: ShareLink, baseOrigin: string) {
  const url = `${baseOrigin}/share/${share.token}`
  return share.passcode ? `${url}?p=${encodeURIComponent(share.passcode)}` : url
}

function RestrictionsEditor(props: {
  restrictions: RequiredRestrictions
  onChange: (r: RequiredRestrictions) => void
}) {
  const quotaMode = () => getQuotaMode(props.restrictions.maxUploadBytes)

  function setMode(mode: QuotaMode) {
    if (mode === 'unlimited') props.onChange({ ...props.restrictions, maxUploadBytes: 0 })
    else if (mode === 'preset')
      props.onChange({ ...props.restrictions, maxUploadBytes: DEFAULT_MAX_UPLOAD_BYTES })
    else
      props.onChange({
        ...props.restrictions,
        maxUploadBytes: props.restrictions.maxUploadBytes || DEFAULT_MAX_UPLOAD_BYTES,
      })
  }

  return (
    <div class='space-y-3'>
      <label class='flex cursor-pointer items-center gap-3'>
        <input
          type='checkbox'
          checked={props.restrictions.allowUpload}
          class='border-input h-4 w-4 rounded'
          onChange={(e) =>
            props.onChange({ ...props.restrictions, allowUpload: e.currentTarget.checked })
          }
        />
        <div>
          <p class='text-sm font-medium'>Allow uploads & file creation</p>
          <p class='text-muted-foreground text-xs'>Create new files and folders</p>
        </div>
      </label>

      <label class='flex cursor-pointer items-center gap-3'>
        <input
          type='checkbox'
          checked={props.restrictions.allowEdit}
          class='border-input h-4 w-4 rounded'
          onChange={(e) =>
            props.onChange({ ...props.restrictions, allowEdit: e.currentTarget.checked })
          }
        />
        <div>
          <p class='text-sm font-medium'>Allow editing & renaming</p>
          <p class='text-muted-foreground text-xs'>Edit file contents, rename, and move items</p>
        </div>
      </label>

      <label class='flex cursor-pointer items-center gap-3'>
        <input
          type='checkbox'
          checked={props.restrictions.allowDelete}
          class='border-input h-4 w-4 rounded'
          onChange={(e) =>
            props.onChange({ ...props.restrictions, allowDelete: e.currentTarget.checked })
          }
        />
        <div>
          <p class='text-sm font-medium'>Allow deletion</p>
          <p class='text-muted-foreground text-xs'>Delete files and folders</p>
        </div>
      </label>

      <div class='space-y-2'>
        <p class='text-sm font-medium'>Upload size limit</p>
        <div class='flex gap-1.5'>
          {(['unlimited', 'preset', 'custom'] as const).map((mode) => (
            <button
              type='button'
              class={`h-7 rounded-md border px-2 text-xs capitalize ${
                quotaMode() === mode
                  ? 'border-primary bg-primary text-primary-foreground'
                  : 'border-input bg-background hover:bg-accent'
              }`}
              onClick={() => setMode(mode)}
            >
              {mode}
            </button>
          ))}
        </div>
        <Show when={quotaMode() === 'preset'}>
          <div class='flex flex-wrap gap-1.5'>
            <For each={[...SIZE_PRESETS]}>
              {(preset) => (
                <button
                  type='button'
                  class={`h-7 rounded-md border px-2 text-xs ${
                    props.restrictions.maxUploadBytes === preset.value
                      ? 'border-primary bg-primary text-primary-foreground'
                      : 'border-input bg-background hover:bg-accent'
                  }`}
                  onClick={() =>
                    props.onChange({ ...props.restrictions, maxUploadBytes: preset.value })
                  }
                >
                  {preset.label}
                </button>
              )}
            </For>
          </div>
        </Show>
        <Show when={quotaMode() === 'custom'}>
          <div class='flex items-center gap-2'>
            <input
              type='number'
              min={1}
              class='border-input bg-background h-7 w-24 rounded-md border px-2 text-xs'
              value={Math.round(props.restrictions.maxUploadBytes / (1024 * 1024))}
              onInput={(e) => {
                const mb = parseInt(e.currentTarget.value, 10)
                if (!isNaN(mb) && mb > 0) {
                  props.onChange({ ...props.restrictions, maxUploadBytes: mb * 1024 * 1024 })
                }
              }}
            />
            <span class='text-muted-foreground text-xs'>MB</span>
          </div>
        </Show>
      </div>
    </div>
  )
}

function ShareLinkCard(props: {
  share: ShareLink
  shareLinkBase: string
  isDirectory: boolean
  isEditable: boolean
  onRevoked: () => void
}) {
  const queryClient = useQueryClient()
  const [copiedLink, setCopiedLink] = createSignal(false)
  const [showSettings, setShowSettings] = createSignal(false)
  const [editable, setEditable] = createSignal(props.share.editable)
  const [restrictions, setRestrictions] = createSignal<RequiredRestrictions>(
    extractRestrictions(props.share),
  )

  let debounceTimer: ReturnType<typeof setTimeout> | undefined
  onCleanup(() => {
    if (debounceTimer) clearTimeout(debounceTimer)
  })

  createEffect(() => {
    const s = props.share
    setEditable(s.editable)
    setRestrictions(extractRestrictions(s))
  })

  const updateMutation = useMutation(() => ({
    mutationFn: (vars: { token: string; editable: boolean; restrictions: RequiredRestrictions }) =>
      fetch('/api/shares', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(vars),
      }).then((r) => r.json()),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: queryKeys.shares() })
    },
  }))

  function scheduleUpdate(newEditable: boolean, newRestrictions: RequiredRestrictions) {
    if (debounceTimer) clearTimeout(debounceTimer)
    debounceTimer = setTimeout(() => {
      updateMutation.mutate({
        token: props.share.token,
        editable: newEditable,
        restrictions: newRestrictions,
      })
    }, 500)
  }

  const revokeMutation = useMutation(() => ({
    mutationFn: (vars: { token: string }) => post('/api/shares/delete', vars),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: queryKeys.shares() })
      props.onRevoked()
    },
  }))

  async function handleCopyLink() {
    try {
      await navigator.clipboard.writeText(buildShareUrl(props.share, props.shareLinkBase))
      setCopiedLink(true)
      window.setTimeout(() => setCopiedLink(false), 2000)
    } catch {
      /* ignore */
    }
  }

  const url = () => buildShareUrl(props.share, props.shareLinkBase)
  const used = () => props.share.usedBytes || 0
  const limit = () => restrictions().maxUploadBytes

  const settingsSummary = createMemo(() => {
    const ed = editable()
    const r = restrictions()
    if (!ed) return 'Read-only'
    const denied: string[] = []
    if (!r.allowUpload) denied.push('upload')
    if (!r.allowEdit) denied.push('edit')
    if (!r.allowDelete) denied.push('delete')
    const rest = denied.length > 0 ? ` (no ${denied.join(', ')})` : ''
    const lim = limit()
    const quota =
      lim > 0
        ? ` · ${formatFileSize(used())} / ${formatFileSize(lim)}`
        : ` · ${formatFileSize(used())} (unlimited)`
    return `Editable${rest}${quota}`
  })

  return (
    <div class='space-y-3 rounded-lg border border-border p-3'>
      <div class='flex items-center justify-between'>
        <p class='text-muted-foreground text-xs'>
          Created{' '}
          {new Date(props.share.createdAt).toLocaleDateString(undefined, {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
          })}
        </p>
        <span class='bg-muted text-muted-foreground rounded px-1.5 py-0.5 text-xs'>
          {props.share.isDirectory ? 'Folder' : 'File'}
        </span>
      </div>

      <div class='flex gap-2'>
        <input
          type='text'
          readOnly
          class='border-input bg-background flex-1 rounded-md border px-3 py-2 font-mono text-xs'
          value={url()}
        />
        <button
          type='button'
          title='Copy link'
          class='border-input bg-background inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-md border hover:bg-accent'
          onClick={() => void handleCopyLink()}
        >
          {copiedLink() ? (
            <Check class='h-4 w-4' stroke-width={2} />
          ) : (
            <Copy class='h-4 w-4' stroke-width={2} />
          )}
        </button>
      </div>

      <Show when={props.share.passcode}>
        <p class='text-muted-foreground text-xs'>Passcode is included in the link.</p>
      </Show>

      <button
        type='button'
        class='text-foreground flex h-8 w-full items-center justify-between rounded-md px-2 text-xs hover:bg-muted/50'
        onClick={() => setShowSettings(!showSettings())}
      >
        <span>{settingsSummary()}</span>
        {showSettings() ? (
          <ChevronUp class='h-3.5 w-3.5' stroke-width={2} />
        ) : (
          <ChevronDown class='h-3.5 w-3.5' stroke-width={2} />
        )}
      </button>

      <Show when={showSettings()}>
        <div class='space-y-3 pt-1'>
          <Show when={props.isDirectory && props.isEditable}>
            <label class='flex cursor-pointer items-center gap-3'>
              <input
                type='checkbox'
                checked={editable()}
                class='border-input h-4 w-4 rounded'
                onChange={(e) => {
                  const v = e.currentTarget.checked
                  setEditable(v)
                  scheduleUpdate(v, restrictions())
                }}
              />
              <div>
                <p class='text-sm font-medium'>Allow editing</p>
                <p class='text-muted-foreground text-xs'>
                  Recipients can create, edit, and delete files
                </p>
              </div>
            </label>
          </Show>

          <Show when={editable()}>
            <div class='space-y-3 rounded-lg border border-border p-3'>
              <p class='text-muted-foreground text-xs font-medium'>Restrictions</p>
              <RestrictionsEditor
                restrictions={restrictions()}
                onChange={(r) => {
                  setRestrictions(r)
                  scheduleUpdate(editable(), r)
                }}
              />
            </div>
          </Show>
        </div>
      </Show>

      <button
        type='button'
        class='bg-destructive text-destructive-foreground hover:bg-destructive/90 flex h-9 w-full items-center justify-center gap-1.5 rounded-md text-sm font-medium disabled:opacity-50'
        disabled={revokeMutation.isPending}
        onClick={() => revokeMutation.mutate({ token: props.share.token })}
      >
        <Trash2 class='h-3.5 w-3.5' stroke-width={2} />
        {revokeMutation.isPending ? 'Revoking...' : 'Revoke'}
      </button>
    </div>
  )
}

export type ShareDialogProps = {
  isOpen: boolean
  onClose: () => void
  filePath: string
  fileName: string
  isDirectory: boolean
  isEditable: boolean
  existingShares: ShareLink[]
  shareLinkBase: string
}

export function ShareDialog(props: ShareDialogProps) {
  const queryClient = useQueryClient()
  const [showCreate, setShowCreate] = createSignal(false)
  const [newEditable, setNewEditable] = createSignal(false)
  const [newRestrictions, setNewRestrictions] = createSignal<RequiredRestrictions>({
    allowDelete: true,
    allowUpload: true,
    allowEdit: true,
    maxUploadBytes: DEFAULT_MAX_UPLOAD_BYTES,
  })

  createEffect(() => {
    if (props.isOpen) {
      setShowCreate(false)
      setNewEditable(false)
      setNewRestrictions({
        allowDelete: true,
        allowUpload: true,
        allowEdit: true,
        maxUploadBytes: DEFAULT_MAX_UPLOAD_BYTES,
      })
    }
  })

  const createShareMutation = useMutation(() => ({
    mutationFn: (vars: {
      path: string
      isDirectory: boolean
      editable: boolean
      restrictions?: RequiredRestrictions
    }) => post('/api/shares', vars),
    onSuccess: () => {
      setShowCreate(false)
      void queryClient.invalidateQueries({ queryKey: queryKeys.shares() })
    },
  }))

  const hasShares = createMemo(() => props.existingShares.length > 0)

  const sortedExistingShares = createMemo(() =>
    [...props.existingShares].sort((a, b) => b.createdAt - a.createdAt),
  )

  function handleSubmitNewShare() {
    createShareMutation.mutate({
      path: props.filePath,
      isDirectory: props.isDirectory,
      editable: newEditable(),
      ...(newEditable() ? { restrictions: newRestrictions() } : {}),
    })
  }

  return (
    <Show when={props.isOpen}>
      <div
        class='fixed inset-0 z-550000 flex items-center justify-center bg-black/50 p-4'
        role='presentation'
        onClick={() => props.onClose()}
      >
        <div
          role='dialog'
          aria-modal='true'
          aria-labelledby='share-dialog-title'
          class='bg-card text-card-foreground max-h-[85vh] w-full max-w-md overflow-y-auto rounded-lg border border-border p-6 shadow-lg'
          onClick={(e) => e.stopPropagation()}
        >
          <div class='mb-4 space-y-1.5'>
            <h2 id='share-dialog-title' class='flex items-center gap-2 text-lg font-semibold'>
              <LinkIcon class='h-5 w-5' stroke-width={2} />
              Share Links
            </h2>
            <p class='text-muted-foreground text-sm'>
              {hasShares()
                ? `${props.existingShares.length} share${props.existingShares.length > 1 ? 's' : ''} for "${props.fileName}"`
                : `Create a share link for "${props.fileName}"`}
            </p>
          </div>

          <div class='space-y-3'>
            <Show
              when={showCreate()}
              fallback={
                <button
                  type='button'
                  class='border-input bg-background hover:bg-accent flex h-9 w-full items-center justify-center gap-1.5 rounded-md border text-sm'
                  onClick={() => setShowCreate(true)}
                >
                  <Plus class='h-3.5 w-3.5' stroke-width={2} />
                  Create New Share Link
                </button>
              }
            >
              <div class='space-y-3 rounded-lg border border-dashed border-border p-3'>
                <p class='text-sm font-medium'>New Share Link</p>

                <Show when={props.isDirectory && props.isEditable}>
                  <>
                    <label class='flex cursor-pointer items-center gap-3'>
                      <input
                        type='checkbox'
                        checked={newEditable()}
                        class='border-input h-4 w-4 rounded'
                        onChange={(e) => setNewEditable(e.currentTarget.checked)}
                      />
                      <div>
                        <p class='text-sm font-medium'>Allow editing</p>
                        <p class='text-muted-foreground text-xs'>
                          Recipients can create, edit, and delete files
                        </p>
                      </div>
                    </label>

                    <Show when={newEditable()}>
                      <div class='space-y-3 rounded-lg border border-border p-3'>
                        <p class='text-muted-foreground text-xs font-medium'>Restrictions</p>
                        <RestrictionsEditor
                          restrictions={newRestrictions()}
                          onChange={setNewRestrictions}
                        />
                      </div>
                    </Show>
                  </>
                </Show>

                <div class='flex gap-2'>
                  <button
                    type='button'
                    class='bg-primary text-primary-foreground hover:bg-primary/90 flex h-9 flex-1 items-center justify-center gap-1.5 rounded-md text-sm font-medium disabled:opacity-50'
                    disabled={createShareMutation.isPending}
                    onClick={() => handleSubmitNewShare()}
                  >
                    <LinkIcon class='h-3.5 w-3.5' stroke-width={2} />
                    {createShareMutation.isPending ? 'Creating...' : 'Create'}
                  </button>
                  <button
                    type='button'
                    class='border-input bg-background hover:bg-accent h-9 rounded-md border px-3 text-sm'
                    onClick={() => setShowCreate(false)}
                  >
                    Cancel
                  </button>
                </div>
              </div>
            </Show>

            <For each={sortedExistingShares()}>
              {(share) => (
                <ShareLinkCard
                  share={share}
                  shareLinkBase={props.shareLinkBase}
                  isDirectory={props.isDirectory}
                  isEditable={props.isEditable}
                  onRevoked={() => {}}
                />
              )}
            </For>

            <Show when={!hasShares() && !showCreate()}>
              <p class='text-muted-foreground py-2 text-center text-sm'>
                No share links yet. Create one to get started.
              </p>
            </Show>
          </div>
        </div>
      </div>
    </Show>
  )
}
