// src/media-center/AudioPlayer.tsx
import { api, post } from '@/lib/api/client'
import { queryKeys } from '@/lib/api/query-keys'
import { MediaType, type FileItem } from '@/lib/files/types'
import { useQuery } from '@tanstack/solid-query'
import Monitor from 'lucide-solid/icons/monitor'
import Pause from 'lucide-solid/icons/pause'
import Play from 'lucide-solid/icons/play'
import Repeat from 'lucide-solid/icons/repeat'
import StepBack from 'lucide-solid/icons/step-back'
import StepForward from 'lucide-solid/icons/step-forward'
import Volume2 from 'lucide-solid/icons/volume-2'
import VolumeX from 'lucide-solid/icons/volume-x'
import { Show, createEffect, createMemo } from 'solid-js'
import { createUrlSearchParamsMemo, useBrowserHistory } from '@/lib/browser/browser-history'
import {
  audioPlaybackQueueFromFiles,
  fetchAudioMetadata,
  formatPlaybackTime,
  playbackQueuesEqual,
  type PlaybackItem,
} from '@/features/playback'
import { usePlaybackSession, usePlaybackSnapshot } from '@/features/playback/PlaybackProvider'
import {
  buildAudioMetadataUrl,
  buildMediaUrl,
  buildThumbnailUrl,
} from '@/lib/media/build-media-url'
import { setAudioOnly } from '@/lib/browser/url-state-actions'
import { parentPath } from '@/lib/files/path-utils'

export function AudioPlayer() {
  const history = useBrowserHistory()
  const urlSearchParams = createUrlSearchParamsMemo(history)
  const session = usePlaybackSession()
  const snapshot = usePlaybackSnapshot()

  const currentItem = createMemo(() => snapshot().currentItem)
  const playbackMode = createMemo(() => snapshot().mode)
  const shouldHandleAudio = createMemo(() => !!currentItem() && playbackMode() === 'audio')
  const playingPath = createMemo(() => currentItem()?.locator ?? '')
  const currentDir = createMemo(() => urlSearchParams().get('dir') || parentPath(playingPath()))
  const fileName = createMemo(() => currentItem()?.name ?? '')
  const isVideoFile = createMemo(() => currentItem()?.media === 'video')

  const filesQuery = useQuery(() => ({
    queryKey: queryKeys.files(currentDir()),
    queryFn: () => api<{ files: FileItem[] }>(`/api/files?dir=${encodeURIComponent(currentDir())}`),
  }))
  const allFiles = createMemo(() => filesQuery.data?.files ?? [])

  createEffect(
    () => {
      const current = currentItem()
      if (!current || playbackMode() !== 'audio') return null
      return { current, queue: audioPlaybackQueueFromFiles(allFiles(), current) }
    },
    (next) => {
      if (!next) return
      const state = session.getSnapshot()
      if (!playbackQueuesEqual(state.queue, next.queue)) {
        session.dispatch({ type: 'setQueue', queue: next.queue, current: next.current })
      }
    },
  )

  const coverArtUrl = createMemo(() => {
    const coverFile = allFiles().find((file) => {
      if (file.type !== MediaType.IMAGE) return false
      return file.name.toLowerCase().replace(/\.[^.]+$/, '') === 'cover'
    })
    return coverFile ? buildMediaUrl(coverFile.path) : null
  })

  const metadataUrl = createMemo(() => {
    const path = playingPath()
    return path ? buildAudioMetadataUrl(path) : ''
  })
  const metadataQuery = useQuery(() => ({
    queryKey: queryKeys.audioMetadata(playingPath()),
    queryFn: () => fetchAudioMetadata(metadataUrl()),
    enabled: shouldHandleAudio() && !!metadataUrl(),
    refetchOnWindowFocus: false,
  }))
  const audioMetadata = createMemo(() => metadataQuery.data)

  const displayImageUrl = createMemo(() => {
    const path = playingPath()
    if (isVideoFile() && path) return buildThumbnailUrl(path)
    return audioMetadata()?.coverArt || coverArtUrl()
  })
  const scrubTime = createMemo(() => snapshot().position)
  const displayDuration = createMemo(() => {
    const metadataDuration = audioMetadata()?.duration
    return isVideoFile() && metadataDuration && metadataDuration > 0
      ? metadataDuration
      : snapshot().duration
  })
  const isRepeat = createMemo(() => snapshot().repeat)
  const hasPreviousAudio = createMemo(() => {
    const state = snapshot()
    return state.position > 20 || state.currentIndex > 0
  })
  const hasNextAudio = createMemo(() => {
    const state = snapshot()
    return state.currentIndex >= 0 && state.currentIndex + 1 < state.queue.length
  })

  function incrementView(item: PlaybackItem | undefined) {
    if (item) void post('/api/stats/views', { filePath: item.locator }).catch(() => undefined)
  }

  function playPrevious() {
    const state = session.getSnapshot()
    if (state.position <= 20) incrementView(state.queue[state.currentIndex - 1])
    session.dispatch({ type: 'previous' })
  }

  function playNext() {
    const state = session.getSnapshot()
    incrementView(state.queue[state.currentIndex + 1])
    session.dispatch({ type: 'next' })
  }

  function handleShowVideo() {
    if (!isVideoFile()) return
    session.dispatch({ type: 'setMode', mode: 'video' })
    setAudioOnly(false)
  }

  return (
    <Show when={shouldHandleAudio()}>
      <div
        data-testid='audio-player-chrome'
        class='fixed right-0 bottom-0 left-0 z-50 border-t border-border bg-background pb-[env(safe-area-inset-bottom,0px)]'
      >
        <div class='relative h-px w-full bg-secondary min-[650px]:hidden'>
          <div
            class='absolute top-0 left-0 h-full bg-white transition-all duration-100'
            style={{
              width: `${displayDuration() > 0 ? (scrubTime() / displayDuration()) * 100 : 0}%`,
            }}
          />
          <input
            type='range'
            aria-label='Playback position'
            aria-valuetext={`${formatPlaybackTime(scrubTime())} of ${formatPlaybackTime(displayDuration())}`}
            min={0}
            max={displayDuration() || 0}
            value={scrubTime()}
            onInput={(event) =>
              session.dispatch({
                type: 'seek',
                position: Number.parseFloat(event.currentTarget.value),
              })
            }
            class='absolute top-0 left-0 h-full w-full cursor-pointer opacity-0'
            disabled={!currentItem()}
          />
        </div>

        <div class='container mx-auto px-2 py-1.5 min-[650px]:px-4 min-[650px]:py-3'>
          <div class='flex min-w-0 items-center gap-2 min-[650px]:gap-4'>
            <div class='flex shrink-0 items-center gap-0.5 min-[650px]:gap-2'>
              <button
                type='button'
                aria-label='Previous track'
                disabled={!hasPreviousAudio()}
                onClick={playPrevious}
                class='inline-flex size-8 shrink-0 items-center justify-center rounded-md hover:bg-accent disabled:opacity-50 min-[650px]:size-10'
              >
                <StepBack class='size-3.5 min-[650px]:size-4' />
              </button>
              <button
                type='button'
                aria-label={snapshot().desiredPlaying ? 'Pause' : 'Play'}
                disabled={!currentItem()}
                onClick={() => session.dispatch({ type: 'toggle' })}
                class='inline-flex size-8 shrink-0 items-center justify-center rounded-md bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50 min-[650px]:size-10'
              >
                <Show
                  when={snapshot().desiredPlaying}
                  fallback={<Play class='size-3.5 min-[650px]:size-4' />}
                >
                  <Pause class='size-3.5 min-[650px]:size-4' />
                </Show>
              </button>
              <button
                type='button'
                aria-label='Next track'
                disabled={!hasNextAudio()}
                onClick={playNext}
                class='inline-flex size-8 shrink-0 items-center justify-center rounded-md hover:bg-accent disabled:opacity-50 min-[650px]:size-10'
              >
                <StepForward class='size-3.5 min-[650px]:size-4' />
              </button>
              <button
                type='button'
                aria-label={isRepeat() ? 'Disable repeat' : 'Enable repeat'}
                aria-pressed={isRepeat() ? 'true' : 'false'}
                disabled={!currentItem()}
                onClick={() => session.dispatch({ type: 'toggleRepeat' })}
                class={
                  isRepeat()
                    ? 'inline-flex size-8 shrink-0 items-center justify-center rounded-md bg-primary text-primary-foreground disabled:opacity-50 min-[650px]:size-10'
                    : 'inline-flex size-8 shrink-0 items-center justify-center rounded-md hover:bg-accent disabled:opacity-50 min-[650px]:size-10'
                }
              >
                <Repeat class='size-3.5 min-[650px]:size-4' />
              </button>
              <Show when={isVideoFile()}>
                <button
                  type='button'
                  disabled={!currentItem()}
                  onClick={handleShowVideo}
                  aria-label='Show video'
                  class='inline-flex size-8 shrink-0 items-center justify-center rounded-md hover:bg-accent disabled:opacity-50 min-[650px]:size-10'
                >
                  <Monitor class='size-3.5 min-[650px]:size-4' />
                </button>
              </Show>
            </div>

            <div class='hidden h-8 w-px shrink-0 bg-border min-[650px]:block' />

            <div class='hidden flex-1 items-center gap-3 min-[650px]:flex'>
              <span class='text-sm tabular-nums'>{formatPlaybackTime(scrubTime())}</span>
              <input
                type='range'
                aria-label='Playback position'
                aria-valuetext={`${formatPlaybackTime(scrubTime())} of ${formatPlaybackTime(displayDuration())}`}
                min={0}
                max={displayDuration() || 0}
                value={scrubTime()}
                onInput={(event) =>
                  session.dispatch({
                    type: 'seek',
                    position: Number.parseFloat(event.currentTarget.value),
                  })
                }
                class='h-2 flex-1 cursor-pointer appearance-none rounded-lg bg-secondary [&::-webkit-slider-thumb]:h-3 [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-primary'
                disabled={!currentItem()}
              />
              <span class='text-sm tabular-nums'>{formatPlaybackTime(displayDuration())}</span>
            </div>

            <div class='hidden h-8 w-px shrink-0 bg-border min-[650px]:block' />

            <div class='hidden min-w-[140px] items-center gap-2 lg:flex'>
              <button
                type='button'
                aria-label={snapshot().muted ? 'Unmute' : 'Mute'}
                onClick={() => session.dispatch({ type: 'setMuted', muted: !snapshot().muted })}
                class='inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-md hover:bg-accent'
              >
                <Show when={snapshot().muted} fallback={<Volume2 class='h-4 w-4' />}>
                  <VolumeX class='h-4 w-4' />
                </Show>
              </button>
              <input
                type='range'
                aria-label='Volume'
                aria-valuetext={`${Math.round((snapshot().muted ? 0 : snapshot().volume) * 100)} percent`}
                min={0}
                max={1}
                step={0.01}
                value={snapshot().muted ? 0 : snapshot().volume}
                onInput={(event) =>
                  session.dispatch({
                    type: 'setVolume',
                    volume: Number.parseFloat(event.currentTarget.value),
                  })
                }
                class='h-2 flex-1 cursor-pointer appearance-none rounded-lg bg-secondary [&::-webkit-slider-thumb]:h-3 [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-primary'
              />
            </div>

            <div class='hidden h-8 w-px shrink-0 bg-border md:block' />

            <div class='flex min-w-0 flex-1 items-center gap-2 min-[650px]:w-[200px] min-[650px]:flex-none min-[650px]:gap-3 lg:w-[280px]'>
              <div class='size-9 shrink-0 overflow-hidden rounded bg-secondary min-[650px]:size-12'>
                <Show when={displayImageUrl()}>
                  <img src={displayImageUrl()!} alt='Album art' class='size-full object-cover' />
                </Show>
              </div>

              <div class='min-w-0 flex-1'>
                <Show when={!metadataQuery.isLoading}>
                  <div class='truncate text-xs font-medium min-[650px]:text-sm'>
                    {audioMetadata()?.title || fileName()}
                  </div>
                  <div class='truncate text-[11px] text-muted-foreground min-[650px]:text-xs'>
                    {audioMetadata()?.artist || 'Unknown Artist'}
                  </div>
                </Show>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Show>
  )
}

// components/viewers/audio-player.tsx
'use client'

import { useCallback, useEffect, useRef, useState, useMemo } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { Play, Pause, Volume2, VolumeX, StepBack, StepForward, Repeat, Monitor } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import { FileItem, MediaType } from '@/lib/types'
import { useMediaPlayer, useMediaPlayerStore } from '@/lib/use-media-player'
import { useAudioMetadata } from '@/lib/use-audio-metadata'
import { useViewStats } from '@/lib/use-view-stats'
import { useFiles } from '@/lib/use-files'
import {
  AudioPlayerContent,
  type AudioPlayerContentRef,
} from '@/components/viewers/audio-player-content'

export function AudioPlayer() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const audioContentRef = useRef<AudioPlayerContentRef>(null)
  const [volume, setVolume] = useState(1)
  const [isMuted, setIsMuted] = useState(false)

  const store = useMediaPlayerStore()
  const {
    currentFile,
    mediaType,
    isPlaying,
    currentTime,
    duration,
    isRepeat,
    playFile,
    setCurrentFile,
    setIsPlaying,
    setCurrentTime,
    setDuration,
    toggleRepeat,
  } = useMediaPlayer()

  const { incrementView } = useViewStats()

  const playingPath = searchParams.get('playing')
  const currentDir = searchParams.get('dir') || ''
  const fileName = (playingPath || '').split('/').pop() || ''

  const extension = (playingPath || '').split('.').pop()?.toLowerCase()
  const audioExtensions = ['mp3', 'wav', 'ogg', 'm4a', 'flac', 'aac', 'opus']
  const videoExtensions = ['mp4', 'webm', 'ogg', 'mov', 'avi', 'mkv']
  const isAudioFile = playingPath && audioExtensions.includes(extension || '')
  const isVideoFile = playingPath && videoExtensions.includes(extension || '')
  const isAudioOnly = searchParams.get('audioOnly') === 'true'

  const dirToFetch = useMemo(() => {
    if (!currentDir && !playingPath) return ''
    let dir = currentDir
    if (!dir && playingPath) {
      const pathParts = playingPath.split(/[/\\]/)
      pathParts.pop()
      dir = pathParts.join('/')
    }
    return dir
  }, [currentDir, playingPath])

  const { data: allFiles = [] } = useFiles(dirToFetch)

  const audioFiles = useMemo(() => {
    return allFiles.filter(
      (file: FileItem) => file.type === MediaType.AUDIO || file.type === MediaType.VIDEO,
    )
  }, [allFiles])

  const coverArtUrl = useMemo(() => {
    const coverFile = allFiles.find((file: FileItem) => {
      if (file.type !== MediaType.IMAGE) return false
      const name = file.name.toLowerCase()
      const nameWithoutExt = name.substring(0, name.lastIndexOf('.'))
      return nameWithoutExt === 'cover'
    })
    return coverFile ? `/api/media/${coverFile.path}` : null
  }, [allFiles])

  const { data: audioMetadata, isLoading: isLoadingMetadata } = useAudioMetadata(
    playingPath,
    !!isAudioFile,
  )

  const playNextAudioRef = useRef<() => void>(() => {})
  const playPreviousAudioRef = useRef<() => void>(() => {})
  const isRepeatRef = useRef(isRepeat)

  useEffect(() => {
    isRepeatRef.current = isRepeat
  }, [isRepeat])

  const playNextAudio = useCallback(() => {
    if (!playingPath || audioFiles.length === 0) return

    const currentIndex = audioFiles.findIndex((file) => file.path === playingPath)
    if (currentIndex === -1) {
      setIsPlaying(false)
      return
    }

    let nextFile = null
    for (let i = currentIndex + 1; i < audioFiles.length; i++) {
      if (audioFiles[i].type === MediaType.AUDIO) {
        nextFile = audioFiles[i]
        break
      }
    }

    if (!nextFile) {
      setIsPlaying(false)
      return
    }

    incrementView(nextFile.path)

    const params = new URLSearchParams(searchParams)
    params.set('playing', nextFile.path)
    params.set('dir', currentDir)
    router.replace(`/?${params.toString()}`, { scroll: false })

    playFile(nextFile.path, 'audio')
  }, [
    playingPath,
    audioFiles,
    searchParams,
    currentDir,
    router,
    setIsPlaying,
    playFile,
    incrementView,
  ])

  const playPreviousAudio = useCallback(() => {
    if (!playingPath || audioFiles.length === 0) return

    const audio = audioContentRef.current?.getAudioElement()
    if (audio && audio.currentTime > 20) {
      audio.currentTime = 0
      return
    }

    const currentIndex = audioFiles.findIndex((file) => file.path === playingPath)
    if (currentIndex === -1) return

    let previousFile = null
    for (let i = currentIndex - 1; i >= 0; i--) {
      if (audioFiles[i].type === MediaType.AUDIO) {
        previousFile = audioFiles[i]
        break
      }
    }

    if (!previousFile) return

    incrementView(previousFile.path)

    const params = new URLSearchParams(searchParams)
    params.set('playing', previousFile.path)
    params.set('dir', currentDir)
    router.replace(`/?${params.toString()}`, { scroll: false })

    playFile(previousFile.path, 'audio')
  }, [playingPath, audioFiles, searchParams, currentDir, router, playFile, incrementView])

  useEffect(() => {
    playNextAudioRef.current = playNextAudio
  }, [playNextAudio])
  useEffect(() => {
    playPreviousAudioRef.current = playPreviousAudio
  }, [playPreviousAudio])

  const handleAudioEnded = useCallback(() => {
    if (isRepeatRef.current) {
      const audio = audioContentRef.current?.getAudioElement()
      if (audio) {
        audio.currentTime = 0
        audio.play()
      }
    } else {
      playNextAudioRef.current()
    }
  }, [])

  const handleAudioError = useCallback(() => {
    setIsPlaying(false)
  }, [setIsPlaying])

  // Load audio source when playing path changes
  useEffect(() => {
    const audio = audioContentRef.current?.getAudioElement()
    if (!audio || !playingPath || (!isAudioFile && !isVideoFile)) return

    const mediaUrl = isVideoFile ? `/api/audio/extract/${playingPath}` : `/api/media/${playingPath}`
    const fullUrl = new URL(mediaUrl, window.location.origin).href

    if (audio.src !== fullUrl) {
      const isSameFile = currentFile === playingPath

      if (currentFile !== playingPath || mediaType !== 'audio') {
        setCurrentFile(playingPath, 'audio')
      }

      audio.src = fullUrl
      audio.load()

      if (isSameFile) {
        const storedTime = store.getState().currentTime
        if (storedTime > 0) {
          const seekToPosition = () => {
            audio.currentTime = storedTime
            audio.removeEventListener('loadedmetadata', seekToPosition)
          }
          audio.addEventListener('loadedmetadata', seekToPosition)
        }
      }

      if ('mediaSession' in navigator) {
        navigator.mediaSession.setActionHandler('play', () => audio.play())
        navigator.mediaSession.setActionHandler('pause', () => audio.pause())
        navigator.mediaSession.setActionHandler('seekbackward', (details) => {
          audio.currentTime = Math.max(0, audio.currentTime - (details.seekOffset || 10))
        })
        navigator.mediaSession.setActionHandler('seekforward', (details) => {
          audio.currentTime = Math.min(
            audio.duration,
            audio.currentTime + (details.seekOffset || 10),
          )
        })
        navigator.mediaSession.setActionHandler('seekto', (details) => {
          if (details.seekTime != null) audio.currentTime = details.seekTime
        })
        navigator.mediaSession.setActionHandler('previoustrack', () =>
          playPreviousAudioRef.current(),
        )
        navigator.mediaSession.setActionHandler('nexttrack', () => playNextAudioRef.current())
      }
    }
  }, [playingPath, isAudioFile, isVideoFile, currentFile, mediaType, setCurrentFile, store])

  // Update Media Session metadata
  useEffect(() => {
    if (!playingPath || (!isAudioFile && !isVideoFile) || !('mediaSession' in navigator)) return

    const metadata: MediaMetadataInit = {
      title: isVideoFile ? `${fileName} (Audio)` : audioMetadata?.title || fileName,
      artist: isVideoFile ? 'Video Audio' : audioMetadata?.artist || 'Unknown Artist',
      album: isVideoFile
        ? currentDir || 'Unknown Album'
        : audioMetadata?.album || currentDir || 'Unknown Album',
    }

    const artworkUrl = audioMetadata?.coverArt || coverArtUrl
    if (artworkUrl) {
      const fullArtworkUrl = artworkUrl.startsWith('data:')
        ? artworkUrl
        : new URL(artworkUrl, window.location.origin).href

      metadata.artwork = [
        { src: fullArtworkUrl, sizes: '512x512', type: 'image/jpeg' },
        { src: fullArtworkUrl, sizes: '256x256', type: 'image/jpeg' },
        { src: fullArtworkUrl, sizes: '128x128', type: 'image/jpeg' },
      ]
    }

    navigator.mediaSession.metadata = new MediaMetadata(metadata)
  }, [playingPath, isAudioFile, isVideoFile, audioMetadata, fileName, currentDir, coverArtUrl])

  const handleTogglePlayPause = () => {
    if (playingPath) playFile(playingPath, 'audio')
  }

  const handleShowVideo = () => {
    const audio = audioContentRef.current?.getAudioElement()
    if (audio && playingPath) {
      setCurrentTime(audio.currentTime)
      setCurrentFile(playingPath, 'video')

      const params = new URLSearchParams(searchParams)
      params.delete('audioOnly')
      router.replace(`/?${params.toString()}`, { scroll: false })
    }
  }

  const handleSeek = (e: React.ChangeEvent<HTMLInputElement>) => {
    const audio = audioContentRef.current?.getAudioElement()
    if (!audio) return
    audio.currentTime = parseFloat(e.target.value)
  }

  const handleVolumeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const audio = audioContentRef.current?.getAudioElement()
    if (!audio) return
    const vol = parseFloat(e.target.value)
    audio.volume = vol
    setVolume(vol)
    setIsMuted(vol === 0)
  }

  const toggleMute = () => {
    const audio = audioContentRef.current?.getAudioElement()
    if (!audio) return

    if (isMuted) {
      audio.volume = volume || 0.5
      setVolume(volume || 0.5)
      setIsMuted(false)
    } else {
      audio.volume = 0
      setIsMuted(true)
    }
  }

  const formatTime = (time: number) => {
    if (isNaN(time)) return '0:00'
    const minutes = Math.floor(time / 60)
    const seconds = Math.floor(time % 60)
    return `${minutes}:${seconds.toString().padStart(2, '0')}`
  }

  const hasPreviousAudio = useCallback(() => {
    if (!playingPath || audioFiles.length === 0) return false
    const currentIndex = audioFiles.findIndex((file) => file.path === playingPath)
    if (currentIndex === -1) return false
    for (let i = currentIndex - 1; i >= 0; i--) {
      if (audioFiles[i].type === MediaType.AUDIO) return true
    }
    return false
  }, [playingPath, audioFiles])

  const hasNextAudio = useCallback(() => {
    if (!playingPath || audioFiles.length === 0) return false
    const currentIndex = audioFiles.findIndex((file) => file.path === playingPath)
    if (currentIndex === -1) return false
    for (let i = currentIndex + 1; i < audioFiles.length; i++) {
      if (audioFiles[i].type === MediaType.AUDIO) return true
    }
    return false
  }, [playingPath, audioFiles])

  const showPlayer = isAudioFile || (isVideoFile && isAudioOnly)

  const audioSrc = useMemo(() => {
    if (!playingPath) return ''
    return isVideoFile ? `/api/audio/extract/${playingPath}` : `/api/media/${playingPath}`
  }, [playingPath, isVideoFile])

  return (
    <>
      <AudioPlayerContent
        ref={audioContentRef}
        src={audioSrc}
        onTimeUpdate={setCurrentTime}
        onDurationChange={setDuration}
        onPlay={() => setIsPlaying(true)}
        onPause={() => setIsPlaying(false)}
        onEnded={handleAudioEnded}
        onError={handleAudioError}
        isPlaying={
          isPlaying && mediaType === 'audio' && currentFile === playingPath
            ? true
            : !isPlaying && mediaType === 'audio' && currentFile === playingPath
              ? false
              : undefined
        }
      />

      {showPlayer && (
        <div className='fixed bottom-0 left-0 right-0 bg-background z-50'>
          <div className='min-[650px]:hidden relative w-full h-1 bg-secondary'>
            <div
              className='absolute top-0 left-0 h-full bg-white transition-all duration-100'
              style={{ width: `${duration > 0 ? (currentTime / duration) * 100 : 0}%` }}
            />
            <input
              type='range'
              min='0'
              max={duration || 0}
              value={currentTime}
              onChange={handleSeek}
              className='absolute top-0 left-0 w-full h-full opacity-0 cursor-pointer'
              disabled={!playingPath}
            />
          </div>

          <div className='border-t border-border' />

          <div className='container mx-auto px-4 py-3'>
            <div className='flex items-center gap-4'>
              <div className='flex items-center gap-2'>
                <Button
                  variant='ghost'
                  size='icon'
                  onClick={playPreviousAudio}
                  disabled={!hasPreviousAudio()}
                >
                  <StepBack className='h-4 w-4' />
                </Button>
                <Button
                  variant='default'
                  size='icon'
                  onClick={handleTogglePlayPause}
                  disabled={!playingPath}
                >
                  {isPlaying && mediaType === 'audio' && currentFile === playingPath ? (
                    <Pause className='h-4 w-4' />
                  ) : (
                    <Play className='h-4 w-4' />
                  )}
                </Button>
                <Button
                  variant='ghost'
                  size='icon'
                  onClick={playNextAudio}
                  disabled={!hasNextAudio()}
                >
                  <StepForward className='h-4 w-4' />
                </Button>
                <Button
                  variant={isRepeat ? 'default' : 'ghost'}
                  size='icon'
                  onClick={toggleRepeat}
                  disabled={!playingPath}
                >
                  <Repeat className='h-4 w-4' />
                </Button>
                {isVideoFile && (
                  <Button
                    variant='ghost'
                    size='icon'
                    onClick={handleShowVideo}
                    disabled={!playingPath}
                    aria-label='Show video'
                  >
                    <Monitor className='h-4 w-4' />
                  </Button>
                )}
              </div>

              <Separator orientation='vertical' className='h-8 hidden min-[650px]:block' />

              <div className='hidden min-[650px]:flex flex-1 items-center gap-3'>
                <span className='text-sm tabular-nums'>{formatTime(currentTime)}</span>
                <input
                  type='range'
                  min='0'
                  max={duration || 0}
                  value={currentTime}
                  onChange={handleSeek}
                  className='flex-1 h-2 bg-secondary rounded-lg appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:h-3 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-primary'
                  disabled={!playingPath}
                />
                <span className='text-sm tabular-nums'>{formatTime(duration)}</span>
              </div>

              <Separator orientation='vertical' className='h-8 hidden min-[650px]:block' />

              <div className='hidden lg:flex items-center gap-2 min-w-[140px]'>
                <Button variant='ghost' size='icon' onClick={toggleMute}>
                  {isMuted ? <VolumeX className='h-4 w-4' /> : <Volume2 className='h-4 w-4' />}
                </Button>
                <input
                  type='range'
                  min='0'
                  max='1'
                  step='0.01'
                  value={isMuted ? 0 : volume}
                  onChange={handleVolumeChange}
                  className='flex-1 h-2 bg-secondary rounded-lg appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:h-3 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-primary'
                />
              </div>

              <Separator orientation='vertical' className='h-8 hidden md:block' />

              <div className='w-[200px] lg:w-[280px] flex items-center gap-3'>
                <div className='shrink-0 w-12 h-12 rounded overflow-hidden bg-secondary'>
                  {(audioMetadata?.coverArt || coverArtUrl) && (
                    <img
                      src={audioMetadata?.coverArt || coverArtUrl || ''}
                      alt='Album art'
                      className='w-full h-full object-cover'
                    />
                  )}
                </div>

                <div className='flex-1 min-w-0'>
                  {!isLoadingMetadata && (
                    <>
                      <div className='font-medium truncate text-sm'>
                        {audioMetadata?.title || fileName}
                      </div>
                      <div className='text-xs text-muted-foreground truncate'>
                        {audioMetadata?.artist || 'Unknown Artist'}
                      </div>
                    </>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
