// src/file-browser/Breadcrumbs.tsx
import { cn } from '@/lib/utils'
import ChevronRight from 'lucide-solid/icons/chevron-right'
import House from 'lucide-solid/icons/house'
import MoreHorizontal from 'lucide-solid/icons/more-horizontal'
import { For, Show, createEffect, createMemo, createSignal, onCleanup } from 'solid-js'

type BreadcrumbsProps = {
  currentPath: string
  onNavigate: (path: string) => void
  mode?: 'MediaServer' | 'Workspace'
}

type BreadcrumbRow =
  | { id: string; kind: 'home'; path: string; name: string; isLast: boolean }
  | { id: string; kind: 'crumb'; path: string; name: string; isLast: boolean }
  | { id: string; kind: 'ellipsis-inline' }
  | { id: string; kind: 'ellipsis-end' }

export function Breadcrumbs(props: BreadcrumbsProps) {
  const isWorkspace = () => (props.mode ?? 'MediaServer') === 'Workspace'

  const crumbs = createMemo(() => {
    const parts = props.currentPath ? props.currentPath.split(/[/\\]/).filter(Boolean) : []
    return [
      { name: 'Home', path: '' },
      ...parts.map((part, index) => ({
        name: part,
        path: parts.slice(0, index + 1).join('/'),
      })),
    ]
  })

  const [containerEl, setContainerEl] = createSignal<HTMLDivElement | null>(null)
  const [measureEl, setMeasureEl] = createSignal<HTMLDivElement | null>(null)
  const [visibleIndices, setVisibleIndices] = createSignal<Set<number>>(new Set())
  const [showEllipsis, setShowEllipsis] = createSignal(false)
  const [isManuallyExpanded, setIsManuallyExpanded] = createSignal(false)
  const [wouldShowEllipsis, setWouldShowEllipsis] = createSignal(false)

  const effectiveVisible = createMemo(() => {
    const s = visibleIndices()
    const c = crumbs()
    if (s.size === 0 && c.length > 0) return new Set(c.map((_, i) => i))
    return s
  })

  const btnClass = (isCurrent: boolean) =>
    cn(
      'inline-flex shrink-0 items-center justify-center gap-1.5 rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
      isWorkspace() ? 'h-7 px-2 text-xs gap-1' : 'h-8 px-2.5 text-sm gap-1.5',
      isCurrent
        ? 'bg-primary text-primary-foreground shadow-sm hover:bg-primary/90'
        : 'text-foreground hover:bg-accent hover:text-accent-foreground',
    )

  const ellipsisBtnClass = () =>
    cn(
      'inline-flex shrink-0 items-center justify-center rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
      isWorkspace() ? 'h-7 px-2' : 'h-8 px-2.5',
      'text-foreground hover:bg-accent hover:text-accent-foreground',
    )

  createEffect(() => {
    crumbs()
    isManuallyExpanded()
    const container = containerEl()
    const measure = measureEl()
    if (!container || !measure) return

    const calculate = () => {
      const bc = crumbs()
      const expanded = isManuallyExpanded()
      if (!containerEl() || !measureEl() || bc.length <= 3) {
        setVisibleIndices(new Set(bc.map((_, i) => i)))
        setShowEllipsis(false)
        setWouldShowEllipsis(false)
        return
      }

      const availableWidth = container.clientWidth
      const computedStyle = window.getComputedStyle(container)
      const gap = parseFloat(computedStyle.gap) || 0

      const crumbElements = measure.children
      const crumbWidths: number[] = []
      for (let i = 0; i < crumbElements.length; i++) {
        crumbWidths.push((crumbElements[i] as HTMLElement).offsetWidth)
      }
      const ellipsisWidth = (crumbElements[crumbElements.length - 1] as HTMLElement).offsetWidth

      const calculateTotalWidth = (indices: number[]) => {
        const itemsWidth = indices.reduce((sum, idx) => sum + (crumbWidths[idx] || 0), 0)
        const gapsWidth = (indices.length - 1) * gap
        const safetyMargin = 10
        return itemsWidth + gapsWidth + safetyMargin
      }

      const allIndices = Array.from({ length: bc.length }, (_, i) => i)
      const totalWidth = calculateTotalWidth(allIndices)

      if (expanded) {
        setVisibleIndices(new Set(bc.map((_, i) => i)))
        setShowEllipsis(false)
        setWouldShowEllipsis(totalWidth > availableWidth)
        return
      }

      if (totalWidth <= availableWidth) {
        setVisibleIndices(new Set(allIndices))
        setShowEllipsis(false)
        setWouldShowEllipsis(false)
        setIsManuallyExpanded(false)
        return
      }

      const requiredIndices = [0, bc.length - 2, bc.length - 1]
      const visible = [...requiredIndices]

      for (let i = 1; i < bc.length - 2; i++) {
        const testIndices = [...visible, i].sort((a, b) => a - b)
        const testWidth = calculateTotalWidth(testIndices) + ellipsisWidth + gap
        if (testWidth <= availableWidth) {
          visible.push(i)
        } else {
          break
        }
      }

      visible.sort((a, b) => a - b)
      const allVisible = visible.length === bc.length
      setShowEllipsis(!allVisible)
      setWouldShowEllipsis(!allVisible)
      setVisibleIndices(new Set(visible))
    }

    calculate()
    const ro = new ResizeObserver(calculate)
    ro.observe(container)
    onCleanup(() => ro.disconnect())
  })

  const toggleEllipsis = () => setIsManuallyExpanded((v) => !v)

  const breadcrumbRows = createMemo((): BreadcrumbRow[] => {
    const list = crumbs()
    const vis = effectiveVisible()
    if (list.length === 0) return []

    const rows: BreadcrumbRow[] = [
      {
        id: 'home',
        kind: 'home',
        path: list[0].path,
        name: list[0].name,
        isLast: list.length === 1,
      },
    ]

    for (let index = 1; index < list.length; index++) {
      const crumb = list[index]
      if (showEllipsis() && index === list.length - 2) {
        const hasHiddenCrumbs = !vis.has(index - 1)
        if (hasHiddenCrumbs) {
          rows.push({ id: 'ellipsis-inline', kind: 'ellipsis-inline' })
          rows.push({
            id: `crumb-${crumb.path}`,
            kind: 'crumb',
            path: crumb.path,
            name: crumb.name,
            isLast: index === list.length - 1,
          })
          continue
        }
      }
      if (vis.has(index)) {
        rows.push({
          id: `crumb-${crumb.path}`,
          kind: 'crumb',
          path: crumb.path,
          name: crumb.name,
          isLast: index === list.length - 1,
        })
      }
    }

    if (isManuallyExpanded() && wouldShowEllipsis()) {
      rows.push({ id: 'ellipsis-end', kind: 'ellipsis-end' })
    }

    return rows
  })

  return (
    <>
      <div
        ref={setMeasureEl}
        class='pointer-events-none absolute left-0 top-0 flex items-center gap-1 lg:gap-2'
        style={{ visibility: 'hidden' }}
        aria-hidden='true'
      >
        <For each={crumbs()}>
          {(crumb, index) => (
            <div class='flex items-center gap-2'>
              <Show when={index() > 0}>
                <ChevronRight class='h-4 w-4 shrink-0 text-muted-foreground' stroke-width={2} />
              </Show>
              <button type='button' class={btnClass(index() === crumbs().length - 1)} disabled>
                <Show when={index() === 0}>
                  <House class='h-4 w-4 shrink-0' stroke-width={2} />
                </Show>
                {crumb.name}
              </button>
            </div>
          )}
        </For>
        <div class='flex items-center gap-2'>
          <ChevronRight class='h-4 w-4 shrink-0 text-muted-foreground' stroke-width={2} />
          <button type='button' class={ellipsisBtnClass()} disabled>
            <MoreHorizontal class='h-4 w-4 shrink-0' stroke-width={2} />
          </button>
        </div>
      </div>

      <div
        ref={setContainerEl}
        class='relative flex min-w-0 flex-1 flex-wrap items-center gap-1 lg:gap-2'
        aria-label='Breadcrumb'
      >
        <For each={breadcrumbRows()}>
          {(row) => {
            switch (row.kind) {
              case 'home':
                return (
                  <div class='flex items-center gap-2'>
                    <button
                      type='button'
                      class={btnClass(row.isLast)}
                      onClick={() => props.onNavigate(row.path)}
                    >
                      <House class='h-4 w-4 shrink-0' stroke-width={2} />
                      {row.name}
                    </button>
                  </div>
                )
              case 'crumb':
                return (
                  <div class='flex items-center gap-2'>
                    <ChevronRight class='h-4 w-4 shrink-0 text-muted-foreground' stroke-width={2} />
                    <button
                      type='button'
                      class={btnClass(row.isLast)}
                      onClick={() => props.onNavigate(row.path)}
                    >
                      {row.name}
                    </button>
                  </div>
                )
              case 'ellipsis-inline':
                return (
                  <div class='flex items-center gap-2'>
                    <ChevronRight class='h-4 w-4 shrink-0 text-muted-foreground' stroke-width={2} />
                    <button
                      type='button'
                      class={ellipsisBtnClass()}
                      onClick={toggleEllipsis}
                      aria-label={
                        isManuallyExpanded() ? 'Collapse breadcrumbs' : 'Expand breadcrumbs'
                      }
                    >
                      <MoreHorizontal class='h-4 w-4 shrink-0' stroke-width={2} />
                    </button>
                  </div>
                )
              case 'ellipsis-end':
                return (
                  <div class='flex items-center gap-2'>
                    <ChevronRight class='h-4 w-4 shrink-0 text-muted-foreground' stroke-width={2} />
                    <button
                      type='button'
                      class={ellipsisBtnClass()}
                      onClick={toggleEllipsis}
                      title='Collapse breadcrumbs'
                    >
                      <MoreHorizontal class='h-4 w-4 shrink-0' stroke-width={2} />
                    </button>
                  </div>
                )
              default:
                return null
            }
          }}
        </For>
      </div>
    </>
  )
}

// components/breadcrumbs.tsx
'use client'

import { Button } from '@/components/ui/button'
import { ChevronRight, Home, MoreHorizontal } from 'lucide-react'
import { useEffect, useRef, useState, useMemo, Fragment } from 'react'
import { getIconComponent } from '@/lib/icon-utils'

interface BreadcrumbsProps {
  currentPath: string
  onNavigate: (path: string) => void
  onFolderHover: (path: string) => void
  customIcons?: Record<string, string>
}

export function Breadcrumbs({
  currentPath,
  onNavigate,
  onFolderHover,
  customIcons = {},
}: BreadcrumbsProps) {
  // Build breadcrumb path
  const breadcrumbs = useMemo(() => {
    const pathParts = currentPath ? currentPath.split(/[/\\]/).filter(Boolean) : []
    return [
      { name: 'Home', path: '' },
      ...pathParts.map((part, index) => ({
        name: part,
        path: pathParts.slice(0, index + 1).join('/'),
      })),
    ]
  }, [currentPath])

  const containerRef = useRef<HTMLDivElement>(null)
  const measureRef = useRef<HTMLDivElement>(null)
  const [visibleIndices, setVisibleIndices] = useState<Set<number>>(
    new Set(breadcrumbs.map((_, i) => i)),
  )
  const [showEllipsis, setShowEllipsis] = useState(false)
  const [isManuallyExpanded, setIsManuallyExpanded] = useState(false)
  const [wouldShowEllipsis, setWouldShowEllipsis] = useState(false)

  useEffect(() => {
    const calculateVisibleBreadcrumbs = () => {
      if (!containerRef.current || !measureRef.current || breadcrumbs.length <= 3) {
        // If 3 or fewer breadcrumbs, show all
        setVisibleIndices(new Set(breadcrumbs.map((_, i) => i)))
        setShowEllipsis(false)
        return
      }

      // Get available width from the container that fills the space
      const availableWidth = containerRef.current.clientWidth

      // Get the gap size from computed styles for breadcrumbs
      const computedStyle = window.getComputedStyle(containerRef.current)
      const gap = parseFloat(computedStyle.gap) || 0

      // Measure all individual crumb widths (including separators)
      const crumbElements = measureRef.current.children
      const crumbWidths: number[] = []

      for (let i = 0; i < crumbElements.length; i++) {
        const el = crumbElements[i] as HTMLElement
        crumbWidths.push(el.offsetWidth)
      }

      // Ellipsis width is the last measured element
      const ellipsisWidth = (crumbElements[crumbElements.length - 1] as HTMLElement).offsetWidth

      // Helper function to calculate total width including gaps
      const calculateTotalWidth = (indices: number[]) => {
        const itemsWidth = indices.reduce((sum, idx) => sum + (crumbWidths[idx] || 0), 0)
        const gapsWidth = (indices.length - 1) * gap
        const safetyMargin = 10 // Add a small margin for safety
        return itemsWidth + gapsWidth + safetyMargin
      }

      // First check if all breadcrumbs fit without ellipsis
      const allIndices = Array.from({ length: breadcrumbs.length }, (_, i) => i)
      const totalWidth = calculateTotalWidth(allIndices)

      // If manually expanded, show all breadcrumbs but check if they would naturally fit
      if (isManuallyExpanded) {
        setVisibleIndices(new Set(breadcrumbs.map((_, i) => i)))
        setShowEllipsis(false)
        // Only show collapse button if breadcrumbs wouldn't naturally fit
        setWouldShowEllipsis(totalWidth > availableWidth)
        return
      }

      if (totalWidth <= availableWidth) {
        setVisibleIndices(new Set(allIndices))
        setShowEllipsis(false)
        setWouldShowEllipsis(false)
        setIsManuallyExpanded(false) // Reset manual expansion when everything fits
        return
      }

      // Calculate required indices: 0 (Home) and last 2
      const requiredIndices = [0, breadcrumbs.length - 2, breadcrumbs.length - 1]

      // Try to fit middle breadcrumbs one by one
      const visible = [...requiredIndices]

      for (let i = 1; i < breadcrumbs.length - 2; i++) {
        // Try adding this breadcrumb
        const testIndices = [...visible, i].sort((a, b) => a - b)
        // Calculate width with ellipsis
        const testWidth = calculateTotalWidth(testIndices) + ellipsisWidth + gap

        if (testWidth <= availableWidth) {
          visible.push(i)
        } else {
          // Can't fit any more, stop
          break
        }
      }

      // Sort the visible indices
      visible.sort((a, b) => a - b)

      // Show ellipsis if we couldn't fit all breadcrumbs
      const allVisible = visible.length === breadcrumbs.length
      setShowEllipsis(!allVisible)
      setWouldShowEllipsis(!allVisible)
      setVisibleIndices(new Set(visible))
    }

    calculateVisibleBreadcrumbs()

    const resizeObserver = new ResizeObserver(calculateVisibleBreadcrumbs)
    if (containerRef.current) {
      resizeObserver.observe(containerRef.current)
    }

    return () => resizeObserver.disconnect()
  }, [breadcrumbs, isManuallyExpanded])

  const renderBreadcrumb = (
    crumb: { name: string; path: string },
    index: number,
    isVisible: boolean = true,
  ) => {
    // Get custom icon for this breadcrumb
    const customIconName = customIcons[crumb.path]
    const CustomIcon = customIconName ? getIconComponent(customIconName) : null

    return (
      <div
        key={crumb.path}
        className='flex items-center gap-2'
        style={
          !isVisible
            ? { position: 'absolute', visibility: 'hidden', pointerEvents: 'none' }
            : undefined
        }
      >
        {index > 0 && <ChevronRight className='h-4 w-4 text-muted-foreground' />}
        <Button
          variant={index === breadcrumbs.length - 1 ? 'default' : 'ghost'}
          size='sm'
          onClick={() => onNavigate(crumb.path)}
          onMouseEnter={() => onFolderHover(crumb.path)}
          className='gap-1.5 text-sm h-8 px-2.5'
          disabled={!isVisible}
        >
          {CustomIcon ? (
            <CustomIcon className='h-4 w-4' />
          ) : (
            index === 0 && <Home className='h-4 w-4' />
          )}
          {crumb.name}
        </Button>
      </div>
    )
  }

  const handleEllipsisClick = () => {
    setIsManuallyExpanded(!isManuallyExpanded)
  }

  return (
    <>
      {/* Measurement container - invisible */}
      <div
        ref={measureRef}
        className='absolute left-0 top-0 flex items-center gap-1 lg:gap-2'
        style={{ visibility: 'hidden', pointerEvents: 'none' }}
      >
        {breadcrumbs.map((crumb, index) => renderBreadcrumb(crumb, index, false))}
        {/* Measure ellipsis button too */}
        <div className='flex items-center gap-2'>
          <ChevronRight className='h-4 w-4 text-muted-foreground' />
          <Button variant='ghost' size='sm' className='h-8 px-2.5' disabled>
            <MoreHorizontal className='h-4 w-4' />
          </Button>
        </div>
      </div>

      {/* Visible breadcrumbs */}
      <div ref={containerRef} className='flex items-center gap-1 lg:gap-2 flex-wrap min-w-0 flex-1'>
        {breadcrumbs.map((crumb, index) => {
          // Show Home (0)
          if (index === 0) {
            return renderBreadcrumb(crumb, index)
          }

          // Show ellipsis/collapse button before last 2 items if needed
          if (showEllipsis && index === breadcrumbs.length - 2) {
            const hasHiddenCrumbs = !visibleIndices.has(index - 1)
            if (hasHiddenCrumbs) {
              return (
                <Fragment key='ellipsis'>
                  <div className='flex items-center gap-2'>
                    <ChevronRight className='h-4 w-4 text-muted-foreground' />
                    <Button
                      variant='ghost'
                      size='sm'
                      className='h-8 px-2.5'
                      onClick={handleEllipsisClick}
                    >
                      <MoreHorizontal className='h-4 w-4' />
                    </Button>
                  </div>
                  {renderBreadcrumb(crumb, index)}
                </Fragment>
              )
            }
          }

          // Show visible crumbs
          if (visibleIndices.has(index)) {
            return renderBreadcrumb(crumb, index)
          }

          return null
        })}

        {/* Show collapse button when manually expanded */}
        {isManuallyExpanded && wouldShowEllipsis && (
          <div className='flex items-center gap-2'>
            <ChevronRight className='h-4 w-4 text-muted-foreground' />
            <Button
              variant='ghost'
              size='sm'
              className='h-8 px-2.5'
              onClick={handleEllipsisClick}
              title='Collapse breadcrumbs'
            >
              <MoreHorizontal className='h-4 w-4' />
            </Button>
          </div>
        )}
      </div>
    </>
  )
}
