// src/features/explorer/KbDashboard.tsx
import { setFileDragData } from '@/lib/files/file-drag-data'
import {
  finePointerDragEnabled,
  subscribeFinePointerDragEnabled,
} from '@/lib/ui/enable-fine-pointer-drag'
import { useQuery } from '@tanstack/solid-query'
import { api } from '@/lib/api/client'
import { queryKeys } from '@/lib/api/query-keys'
import { cn } from '@/lib/ui/cn'
import FileText from 'lucide-solid/icons/file-text'
import { For, Show, createEffect, createMemo, createSignal, onCleanup, onMount } from 'solid-js'

type RecentFile = { path: string; name: string; modifiedAt: string }

function formatRelativeTime(dateStr: string): string {
  const date = new Date(dateStr)
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffMins = Math.floor(diffMs / 60000)
  const diffHours = Math.floor(diffMs / 3600000)
  const diffDays = Math.floor(diffMs / 86400000)
  if (diffMins < 1) return 'Just now'
  if (diffMins < 60) return `${diffMins}m ago`
  if (diffHours < 24) return `${diffHours}h ago`
  if (diffDays < 7) return `${diffDays}d ago`
  return date.toLocaleDateString()
}

type Props = {
  scopePath: string
  onFileClick: (path: string) => void
  /** Tighter strip + chips for embedded window chrome. */
  compact?: boolean
  mode?: 'MediaServer' | 'Workspace'
  /** When set, recent chips use copyMove when true for this path; otherwise copy only (e.g. tab bar). */
  recentDragCanMove?: (filePath: string) => boolean
}

export function KbDashboard(props: Props) {
  const compact = () => props.compact === true || props.mode === 'Workspace'
  const [enableDrag, setEnableDrag] = createSignal(finePointerDragEnabled())

  onMount(() => {
    setEnableDrag(finePointerDragEnabled())
    return subscribeFinePointerDragEnabled(setEnableDrag)
  })

  const directQuery = useQuery(() => ({
    queryKey: queryKeys.kbRecent(props.scopePath),
    queryFn: () =>
      api<{ results: RecentFile[] }>(`/api/kb/recent?root=${encodeURIComponent(props.scopePath)}`),
    enabled: !!props.scopePath,
  }))

  const recent = createMemo(() => (directQuery.data?.results ?? []) as RecentFile[])

  const isLoading = createMemo(() => directQuery.isLoading)

  const [scrollEl, setScrollEl] = createSignal<HTMLDivElement | null>(null)

  function handleWheel(e: WheelEvent) {
    const el = scrollEl()
    if (!el || el.scrollWidth <= el.clientWidth) return
    e.preventDefault()
    el.scrollLeft += e.deltaY
  }

  createEffect(() => {
    const el = scrollEl()
    if (!el) return
    el.addEventListener('wheel', handleWheel, { passive: false })
    onCleanup(() => el.removeEventListener('wheel', handleWheel))
  })

  function onRecentDragStart(file: RecentFile, e: globalThis.DragEvent) {
    const dtr = e.dataTransfer
    if (!dtr || !enableDrag()) return
    const canMove = props.recentDragCanMove?.(file.path) ?? false
    setFileDragData(dtr, {
      path: file.path,
      isDirectory: false,
      sourceKind: 'local',
    })
    dtr.effectAllowed = canMove ? 'copyMove' : 'copy'
  }

  return (
    <Show when={!isLoading() && recent().length > 0}>
      <div
        ref={setScrollEl}
        data-testid='kb-recent-strip'
        class={cn(
          'min-w-0 shrink-0 overflow-x-auto scrollbar-none border-b border-border',
          compact()
            ? 'flex items-center px-1.5 py-1.5 mb-1'
            : 'bg-muted/20 px-1.5 py-1.5 md:px-2 md:py-2',
        )}
      >
        <div
          class={cn('flex w-max min-w-full flex-nowrap', compact() ? 'gap-1' : 'gap-1 md:gap-1.5')}
        >
          <For each={recent()}>
            {(file) => (
              <div
                role='button'
                tabindex={0}
                {...(compact() ? { 'data-no-window-drag': '' } : {})}
                class={cn(
                  'flex shrink-0 cursor-pointer items-center rounded border border-border bg-background text-left transition-colors hover:bg-muted/50',
                  compact()
                    ? 'gap-1 px-1.5 py-0.5'
                    : 'gap-1 px-1.5 py-1 md:gap-1.5 md:px-2 md:py-1.5',
                )}
                draggable={enableDrag()}
                onClick={() => props.onFileClick(file.path)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault()
                    props.onFileClick(file.path)
                  }
                }}
                onDragStart={(e) => onRecentDragStart(file, e)}
              >
                <FileText
                  class={cn(
                    'shrink-0 text-muted-foreground',
                    compact() ? 'h-3.5 w-3.5' : 'h-4 w-4',
                  )}
                  stroke-width={2}
                />
                <span
                  class={cn(
                    'truncate font-medium',
                    compact() ? 'max-w-[10rem] text-xs' : 'text-sm',
                  )}
                >
                  {file.name}
                </span>
                <span
                  class={cn(
                    'shrink-0 text-muted-foreground',
                    compact() ? 'text-[10px] leading-none' : 'text-xs',
                  )}
                >
                  {formatRelativeTime(file.modifiedAt)}
                </span>
              </div>
            )}
          </For>
        </div>
      </div>
    </Show>
  )
}

// components/kb-dashboard.tsx
import { useCallback, useEffect, useRef, memo } from 'react'
import { useQuery } from '@tanstack/react-query'
import { api } from '@/lib/api'
import { FileText } from 'lucide-react'
import { queryKeys } from '@/lib/query-keys'

interface RecentFile {
  path: string
  name: string
  modifiedAt: string
}

interface KbDashboardProps {
  scopePath: string
  onFileClick: (path: string) => void
  shareToken?: string
  dir?: string
}

const RecentFileButton = memo(function RecentFileButton({
  file,
  onFileClick,
}: {
  file: RecentFile
  onFileClick: (path: string) => void
}) {
  const onClick = useCallback(() => {
    onFileClick(file.path)
  }, [onFileClick, file.path])
  return (
    <button
      type='button'
      onClick={onClick}
      className='flex items-center gap-1 md:gap-1.5 px-1.5 py-1 md:px-2 md:py-1.5 rounded border border-border bg-background hover:bg-muted/50 transition-colors text-left shrink-0'
    >
      <FileText className='h-4 w-4 shrink-0 text-muted-foreground' />
      <span className='truncate text-sm font-medium'>{file.name}</span>
      <span className='text-xs text-muted-foreground shrink-0'>
        {formatRelativeTime(file.modifiedAt)}
      </span>
    </button>
  )
})

function formatRelativeTime(dateStr: string): string {
  const date = new Date(dateStr)
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffMins = Math.floor(diffMs / 60000)
  const diffHours = Math.floor(diffMs / 3600000)
  const diffDays = Math.floor(diffMs / 86400000)
  if (diffMins < 1) return 'Just now'
  if (diffMins < 60) return `${diffMins}m ago`
  if (diffHours < 24) return `${diffHours}h ago`
  if (diffDays < 7) return `${diffDays}d ago`
  return date.toLocaleDateString()
}

export function KbDashboard({ scopePath, onFileClick, shareToken, dir }: KbDashboardProps) {
  const { data: directData, isLoading: directLoading } = useQuery({
    queryKey: queryKeys.kbRecent(scopePath),
    queryFn: () =>
      api<{ results: RecentFile[] }>(`/api/kb/recent?root=${encodeURIComponent(scopePath)}`),
    enabled: !shareToken,
  })
  const { data: shareData, isLoading: shareLoading } = useQuery({
    queryKey: shareToken ? queryKeys.shareKbRecent(shareToken, dir) : queryKeys.shareKbRecent(),
    queryFn: () => {
      const params = new URLSearchParams()
      if (dir) params.set('dir', dir)
      return api<{ results: RecentFile[] }>(`/api/share/${shareToken}/kb/recent?${params}`)
    },
    enabled: !!shareToken,
  })
  const recent = ((shareToken ? shareData : directData)?.results || []) as RecentFile[]
  const isLoading = shareToken ? shareLoading : directLoading

  const scrollRef = useRef<HTMLDivElement>(null)

  const handleWheel = useCallback((e: WheelEvent) => {
    const el = scrollRef.current
    if (!el || el.scrollWidth <= el.clientWidth) return
    e.preventDefault()
    el.scrollLeft += e.deltaY
  }, [])

  useEffect(() => {
    const el = scrollRef.current
    if (!el) return
    el.addEventListener('wheel', handleWheel, { passive: false })
    return () => el.removeEventListener('wheel', handleWheel)
  }, [handleWheel])

  if (isLoading || !recent?.length) {
    return null
  }

  return (
    <div
      ref={scrollRef}
      data-testid='kb-recent-strip'
      className='min-w-0 shrink-0 overflow-x-auto scrollbar-none border-b border-border bg-muted/20 px-1.5 py-1.5 md:px-2 md:py-2'
    >
      <div className='flex w-max min-w-full flex-nowrap gap-1 md:gap-1.5'>
        {recent.map((file) => (
          <RecentFileButton key={file.path} file={file} onFileClick={onFileClick} />
        ))}
      </div>
    </div>
  )
}
