// src/media-center/ThemeSwitcher.tsx
import { cn } from '@/lib/ui/cn'
import Settings from 'lucide-solid/icons/settings'
import { Show, createEffect, createSignal, onCleanup } from 'solid-js'
import { Portal } from 'solid-js/web'
import { ThemeSwitcherMenuContent } from './ThemeSwitcherMenuContent'

type Props = { variant?: 'header' | 'floating' }

export function ThemeSwitcher(props: Props) {
  const variant = () => props.variant ?? 'header'
  const [menuOpen, setMenuOpen] = createSignal(false)
  const [menuPosition, setMenuPosition] = createSignal({
    top: 0,
    right: 8,
    bottom: 0,
    maxHeight: 1,
  })
  let trigger: HTMLButtonElement | undefined

  function updateMenuPosition() {
    const rect = trigger?.getBoundingClientRect()
    if (!rect) return
    const viewport = window.visualViewport
    const viewportTop = viewport?.offsetTop ?? 0
    const viewportBottom = viewportTop + (viewport?.height ?? window.innerHeight)
    const top = Math.max(viewportTop + 8, rect.bottom + 4)
    const bottom = Math.max(
      window.innerHeight - viewportBottom + 8,
      window.innerHeight - rect.top + 4,
    )
    setMenuPosition({
      top,
      right: Math.max(8, window.innerWidth - rect.right),
      bottom,
      maxHeight:
        variant() === 'floating'
          ? Math.max(1, rect.top - viewportTop - 12)
          : Math.max(1, viewportBottom - top - 8),
    })
  }

  function toggleMenu() {
    if (!menuOpen()) updateMenuPosition()
    setMenuOpen(!menuOpen())
  }

  createEffect(() => {
    if (!menuOpen()) return
    const update = () => updateMenuPosition()
    window.addEventListener('resize', update)
    window.addEventListener('scroll', update, true)
    window.visualViewport?.addEventListener('resize', update)
    window.visualViewport?.addEventListener('scroll', update)
    onCleanup(() => {
      window.removeEventListener('resize', update)
      window.removeEventListener('scroll', update, true)
      window.visualViewport?.removeEventListener('resize', update)
      window.visualViewport?.removeEventListener('scroll', update)
    })
  })

  return (
    <div class={cn('relative', variant() === 'floating' && 'fixed bottom-4 right-4 z-10002')}>
      <button
        ref={trigger}
        type='button'
        title='Theme settings'
        aria-label='Open theme settings'
        aria-expanded={menuOpen()}
        class='inline-flex size-8 shrink-0 items-center justify-center rounded-md text-sm font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-foreground dark:hover:bg-input/50 aria-expanded:bg-muted aria-expanded:text-foreground'
        onClick={toggleMenu}
      >
        <Settings class='h-4 w-4' stroke-width={2} aria-hidden='true' />
      </button>
      <Show when={menuOpen()}>
        <Portal>
          <div
            class='fixed inset-0 z-10000'
            role='presentation'
            onClick={() => setMenuOpen(false)}
          />
          <div
            data-testid='theme-settings-menu'
            role='menu'
            aria-label='Theme settings'
            class='ring-foreground/10 fixed z-10001 min-w-44 max-w-[calc(100vw-1rem)] overflow-y-auto overscroll-contain rounded-md bg-popover p-1 text-popover-foreground shadow-md ring-1'
            classList={{
              'origin-bottom-right': variant() === 'floating',
              'origin-top-right': variant() !== 'floating',
            }}
            style={{
              right: `${menuPosition().right}px`,
              ...(variant() === 'floating'
                ? {
                    bottom: `${menuPosition().bottom}px`,
                    'max-height': `${menuPosition().maxHeight}px`,
                  }
                : {
                    top: `${menuPosition().top}px`,
                    'max-height': `${menuPosition().maxHeight}px`,
                  }),
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <ThemeSwitcherMenuContent onAfterPick={() => setMenuOpen(false)} />
          </div>
        </Portal>
      </Show>
    </div>
  )
}

// components/theme-switcher.tsx
import { Menu } from '@base-ui/react/menu'
import { Settings, Sun, Moon, Monitor, Check } from 'lucide-react'
import { useTheme, type ThemePalette, type ThemeMode } from '@/lib/use-theme'
import { buttonVariants } from '@/components/ui/button'
import { cn } from '@/lib/utils'

interface ThemeSwitcherProps {
  variant?: 'header' | 'taskbar' | 'floating'
}

const MODES: { value: ThemeMode; label: string; icon: typeof Sun }[] = [
  { value: 'light', label: 'Light', icon: Sun },
  { value: 'dark', label: 'Dark', icon: Moon },
  { value: 'system', label: 'System', icon: Monitor },
]

const PALETTES: { value: ThemePalette; label: string }[] = [
  { value: 'default', label: 'Default' },
  { value: 'caffeine', label: 'Caffeine' },
  { value: 'cosmic-night', label: 'Cosmic Night' },
]

export function ThemeSwitcher({ variant = 'header' }: ThemeSwitcherProps) {
  const { palette, mode, setTheme } = useTheme()

  const triggerClass =
    variant === 'taskbar'
      ? 'h-8 w-8 shrink-0 flex items-center justify-center rounded-none text-amber-500 hover:bg-amber-500/15 hover:text-amber-400'
      : variant === 'floating'
        ? 'fixed top-4 right-4 z-50 rounded-md p-2 bg-background/80 backdrop-blur border border-border shadow-md hover:bg-accent'
        : buttonVariants({ variant: 'ghost', size: 'icon-sm' })

  return (
    <Menu.Root>
      <Menu.Trigger
        className={cn(triggerClass, 'cursor-pointer outline-none')}
        title='Theme settings'
        aria-label='Open theme settings'
      >
        <Settings className='h-4 w-4' />
      </Menu.Trigger>
      <Menu.Portal>
        <Menu.Positioner
          className='isolate z-10001 outline-none'
          side={variant === 'taskbar' ? 'top' : variant === 'floating' ? 'bottom' : 'top'}
          align='end'
          sideOffset={variant === 'taskbar' ? 8 : 4}
        >
          <Menu.Popup className='data-open:animate-in data-closed:animate-out data-closed:fade-out-0 data-open:fade-in-0 data-closed:zoom-out-95 data-open:zoom-in-95 ring-foreground/10 bg-popover text-popover-foreground z-50 min-w-44 origin-(--transform-origin) overflow-hidden rounded-md p-1 shadow-md ring-1 duration-100 outline-none'>
            <div className='px-2 py-1.5 text-xs font-medium text-muted-foreground'>Mode</div>
            {MODES.map((m) => {
              const Icon = m.icon
              return (
                <Menu.Item
                  key={m.value}
                  className='flex cursor-pointer items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none hover:bg-accent hover:text-accent-foreground'
                  onClick={() => setTheme(palette, m.value)}
                >
                  <Icon className='h-4 w-4 shrink-0' />
                  <span className='flex-1'>{m.label}</span>
                  {mode === m.value && <Check className='h-4 w-4 shrink-0' />}
                </Menu.Item>
              )
            })}
            <div className='my-1 h-px bg-border' />
            <div className='px-2 py-1.5 text-xs font-medium text-muted-foreground'>Theme</div>
            {PALETTES.map((p) => (
              <Menu.Item
                key={p.value}
                className='flex cursor-pointer items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none hover:bg-accent hover:text-accent-foreground'
                onClick={() => setTheme(p.value, mode)}
              >
                <span className='flex-1'>{p.label}</span>
                {palette === p.value && <Check className='h-4 w-4 shrink-0' />}
              </Menu.Item>
            ))}
          </Menu.Popup>
        </Menu.Positioner>
      </Menu.Portal>
    </Menu.Root>
  )
}
