// src/pages/WorkspacePage.tsx
import { useCallback, useMemo, useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ThemeSwitcher } from '@/components/theme-switcher'
import { AudioPlayer } from '@/components/workspace/audio-player'
import { Layout, type PinnedTaskbarItemView } from '@/components/workspace/layout'
import { SnapPreview } from '@/components/workspace/snap-preview'
import { TilingLayoutPicker } from '@/components/workspace/tiling-layout-picker'
import { WindowGroup } from '@/components/workspace/window'
import { Button } from '@/components/ui/button'
import { api } from '@/lib/api'
import { getIconComponent } from '@/lib/icon-utils'
import { useFileIcon } from '@/lib/use-file-icon'
import { getMediaType } from '@/lib/media-utils'
import { useMediaPlayer } from '@/lib/use-media-player'
import { useSettings } from '@/lib/use-settings'
import { useSnapZones } from '@/lib/use-snap-zones'
import { MediaType } from '@/lib/types'
import type { SnapZone, WorkspaceWindowDefinition } from '@/lib/use-workspace'
import {
  useWorkspace,
  workspaceSourceToMediaContext,
  snapZoneToBoundsWithOccupied,
} from '@/lib/use-workspace'

interface LayoutPickerState {
  windowId: string
  anchorRect: DOMRect
}

interface WindowTabGroup {
  groupId: string
  windows: WorkspaceWindowDefinition[]
}

function groupWindowsByTab(windows: WorkspaceWindowDefinition[]): WindowTabGroup[] {
  const groups = new Map<string, WorkspaceWindowDefinition[]>()
  const order: string[] = []

  for (const w of windows) {
    const gid = w.tabGroupId ?? w.id
    const existing = groups.get(gid)
    if (existing) {
      existing.push(w)
    } else {
      groups.set(gid, [w])
      order.push(gid)
    }
  }

  return order.map((gid) => ({ groupId: gid, windows: groups.get(gid)! }))
}

interface WorkspacePageProps {
  shareConfig?: { token: string; sharePath: string } | null
}

export function WorkspacePage({ shareConfig = null }: WorkspacePageProps) {
  const {
    windows,
    activeWindowId,
    playbackSource,
    playbackSession,
    activeTabMap,
    focusWindow,
    closeWindow,
    openBrowserWindow,
    openViewerWindow,
    openPlayerWindow,
    updateWindowBounds,
    updateWindowPresentation,
    setWindowMinimized,
    toggleWindowFullscreen,
    snapWindow,
    unsnapWindow,
    resizeSnappedWindow,
    mergeWindowIntoGroup,
    splitWindowFromGroup,
    addTabToGroup,
    openInNewTab,
    setActiveTab,
    updateWindowNavigationState,
    requestPlay,
    pinnedTaskbarItems,
    addPinnedItem,
    removePinnedItem,
  } = useWorkspace({
    initialDir:
      typeof window !== 'undefined' ? new URLSearchParams(window.location.search).get('dir') : null,
    shareConfig,
  })

  const containerRef = useRef<HTMLDivElement>(null)
  const [layoutPicker, setLayoutPicker] = useState<LayoutPickerState | null>(null)
  const windowsRef = useRef(windows)
  const mergeHighlightRef = useRef<string | null>(null)
  const draggedWindowIdRef = useRef<string | null>(null)

  const getZoneBounds = useCallback((zone: SnapZone) => {
    const ws = windowsRef.current
    const excludeId = draggedWindowIdRef.current
    const excludeW = excludeId ? ws.find((w) => w.id === excludeId) : null
    const excludeGroupId = excludeW ? (excludeW.tabGroupId ?? excludeId) : null
    const occupied = ws
      .filter(
        (w) =>
          w.layout?.snapZone &&
          w.layout?.bounds &&
          (excludeGroupId == null || (w.tabGroupId ?? w.id) !== excludeGroupId),
      )
      .map((w) => ({ bounds: w.layout!.bounds!, snapZone: w.layout!.snapZone! }))
    return snapZoneToBoundsWithOccupied(zone, occupied)
  }, [])

  const { onDragMove, onDragEnd } = useSnapZones({ getZoneBounds })

  windowsRef.current = windows

  const windowGroups = useMemo(() => groupWindowsByTab(windows), [windows])

  const findMergeTarget = useCallback(
    (clientX: number, clientY: number, draggedWindowId: string): string | null => {
      const ws = windowsRef.current
      const draggedW = ws.find((w) => w.id === draggedWindowId)
      const draggedGroupId = draggedW?.tabGroupId ?? draggedWindowId

      const elements = document.elementsFromPoint(clientX, clientY)
      for (const el of elements) {
        const groupEl = el.closest('[data-window-group]')
        if (!groupEl) continue
        const gid = groupEl.getAttribute('data-window-group')
        if (!gid || gid === draggedGroupId) continue

        const rect = groupEl.getBoundingClientRect()
        if (clientY >= rect.top && clientY <= rect.top + 32) {
          const targetW = ws.find((w) => (w.tabGroupId ?? w.id) === gid)
          return targetW?.id ?? null
        }
        return null
      }
      return null
    },
    [],
  )

  const updateMergeHighlight = useCallback(
    (clientX: number, clientY: number, draggedWindowId: string) => {
      const container = containerRef.current
      if (!container) return

      const targetId = findMergeTarget(clientX, clientY, draggedWindowId)
      const targetW = targetId ? windowsRef.current.find((w) => w.id === targetId) : null
      const gid = targetW ? (targetW.tabGroupId ?? targetId) : null
      if (gid === mergeHighlightRef.current) return

      if (mergeHighlightRef.current) {
        const prev = container.querySelector(`[data-window-group="${mergeHighlightRef.current}"]`)
        prev?.removeAttribute('data-merge-highlight')
      }

      mergeHighlightRef.current = gid

      if (gid) {
        const el = container.querySelector(`[data-window-group="${gid}"]`)
        el?.setAttribute('data-merge-highlight', '')
      }
    },
    [findMergeTarget],
  )

  const clearMergeHighlight = useCallback(() => {
    if (!mergeHighlightRef.current) return
    const container = containerRef.current
    if (container) {
      const prev = container.querySelector(`[data-window-group="${mergeHighlightRef.current}"]`)
      prev?.removeAttribute('data-merge-highlight')
    }
    mergeHighlightRef.current = null
  }, [])

  const handleDragMove = useCallback(
    (clientX: number, clientY: number, windowId: string) => {
      draggedWindowIdRef.current = windowId
      const mergeTarget = findMergeTarget(clientX, clientY, windowId)
      if (mergeTarget) {
        if (containerRef.current) onDragMove(clientX, clientY, containerRef.current, true)
        updateMergeHighlight(clientX, clientY, windowId)
      } else {
        if (containerRef.current) onDragMove(clientX, clientY, containerRef.current, false)
        clearMergeHighlight()
      }
    },
    [onDragMove, findMergeTarget, updateMergeHighlight, clearMergeHighlight],
  )

  const handleDragStop = useCallback(
    (
      windowId: string,
      finalBounds: { x: number; y: number; width: number; height: number },
      clientX: number,
      clientY: number,
    ) => {
      clearMergeHighlight()

      const hitTargetId = findMergeTarget(clientX, clientY, windowId)
      if (hitTargetId) {
        onDragEnd(containerRef.current)
        mergeWindowIntoGroup(windowId, hitTargetId)
        return
      }

      const zone = onDragEnd(containerRef.current)
      if (zone) {
        if (zone === 'top') {
          toggleWindowFullscreen(windowId)
        } else {
          snapWindow(windowId, zone)
        }
        return
      }

      const w = windowsRef.current.find((win) => win.id === windowId)
      if (w?.layout?.snapZone || w?.layout?.fullscreen) {
        unsnapWindow(windowId, { x: finalBounds.x, y: finalBounds.y })
        return
      }
      updateWindowBounds(windowId, finalBounds)
    },
    [
      onDragEnd,
      snapWindow,
      toggleWindowFullscreen,
      unsnapWindow,
      updateWindowBounds,
      findMergeTarget,
      mergeWindowIntoGroup,
      clearMergeHighlight,
    ],
  )

  const handleDetachTab = useCallback(
    (windowId: string, clientX: number, clientY: number) => {
      const w = windowsRef.current.find((win) => win.id === windowId)
      if (!w) return

      const currentBounds = w.layout?.bounds
      const restoreBounds = w.layout?.restoreBounds
      const width = restoreBounds?.width ?? currentBounds?.width ?? 500
      const height = restoreBounds?.height ?? currentBounds?.height ?? 400

      const container = containerRef.current
      if (!container) return
      const containerRect = container.getBoundingClientRect()
      const oX = containerRect.left
      const oY = containerRect.top

      const initialX = clientX - oX - width / 2
      const initialY = Math.max(0, clientY - oY - 16)

      splitWindowFromGroup(windowId, { x: initialX, y: initialY, width, height })
      focusWindow(windowId)

      const dragOffsetX = width / 2
      const dragOffsetY = 16
      let rafId = 0
      let lastX = clientX
      let lastY = clientY

      const onMouseMove = (e: MouseEvent) => {
        lastX = e.clientX
        lastY = e.clientY
        draggedWindowIdRef.current = windowId
        const mergeTarget = findMergeTarget(e.clientX, e.clientY, windowId)
        if (mergeTarget) {
          onDragMove(e.clientX, e.clientY, container, true)
          updateMergeHighlight(e.clientX, e.clientY, windowId)
        } else {
          onDragMove(e.clientX, e.clientY, container, false)
          clearMergeHighlight()
        }

        if (!rafId) {
          rafId = requestAnimationFrame(() => {
            rafId = 0
            updateWindowBounds(windowId, {
              x: lastX - oX - dragOffsetX,
              y: Math.max(0, lastY - oY - dragOffsetY),
              width,
              height,
            })
          })
        }
      }

      const onMouseUp = (e: MouseEvent) => {
        cleanup()
        clearMergeHighlight()
        if (rafId) cancelAnimationFrame(rafId)

        const hitId = findMergeTarget(e.clientX, e.clientY, windowId)
        if (hitId) {
          onDragEnd(container)
          mergeWindowIntoGroup(windowId, hitId)
          return
        }

        const snapZone = onDragEnd(container)
        if (snapZone) {
          if (snapZone === 'top') {
            toggleWindowFullscreen(windowId)
          } else {
            snapWindow(windowId, snapZone)
          }
          return
        }

        updateWindowBounds(windowId, {
          x: e.clientX - oX - dragOffsetX,
          y: Math.max(0, e.clientY - oY - dragOffsetY),
          width,
          height,
        })
      }

      const cleanup = () => {
        document.removeEventListener('mousemove', onMouseMove)
        document.removeEventListener('mouseup', onMouseUp)
      }

      document.addEventListener('mousemove', onMouseMove)
      document.addEventListener('mouseup', onMouseUp)
    },
    [
      splitWindowFromGroup,
      focusWindow,
      updateWindowBounds,
      onDragMove,
      onDragEnd,
      snapWindow,
      toggleWindowFullscreen,
      mergeWindowIntoGroup,
      findMergeTarget,
      updateMergeHighlight,
      clearMergeHighlight,
    ],
  )

  const handleRestoreDrag = useCallback(
    (windowId: string, clientX: number, _clientY: number) => {
      const w = windowsRef.current.find((win) => win.id === windowId)
      if (!w) return

      const currentBounds = w.layout?.bounds
      const restoreBounds = w.layout?.restoreBounds
      const restoredW = restoreBounds?.width ?? currentBounds?.width ?? 500

      const container = containerRef.current
      if (!container) return
      const oX = container.getBoundingClientRect().left

      const currentWidth = currentBounds?.width ?? restoredW
      const grabRatio = currentBounds
        ? Math.min(Math.max((clientX - oX - currentBounds.x) / currentWidth, 0), 1)
        : 0.5

      const newX = clientX - oX - restoredW * grabRatio
      const newY = currentBounds?.y ?? 0

      unsnapWindow(windowId, { x: newX, y: newY })
    },
    [unsnapWindow],
  )

  const handleLayoutSelect = useCallback(
    (zone: SnapZone) => {
      if (layoutPicker) {
        snapWindow(layoutPicker.windowId, zone)
        setLayoutPicker(null)
      }
    },
    [layoutPicker, snapWindow],
  )

  const handleLayoutFullscreen = useCallback(() => {
    if (layoutPicker) {
      toggleWindowFullscreen(layoutPicker.windowId)
      setLayoutPicker(null)
    }
  }, [layoutPicker, toggleWindowFullscreen])

  const handleNavigationStateChange = useCallback(
    (windowId: string, dir: string | null, viewing: string | null) => {
      updateWindowNavigationState(windowId, { dir, viewing })
    },
    [updateWindowNavigationState],
  )

  const handleCloseTab = useCallback(
    (windowId: string) => {
      const w = windows.find((win) => win.id === windowId)
      if (w?.type === 'player') {
        playbackSession.closePlayer()
      }

      if (w?.tabGroupId) {
        const groupId = w.tabGroupId
        const isActive = activeTabMap[groupId] === windowId
        if (isActive) {
          const groupTabs = windows.filter((win) => win.tabGroupId === groupId)
          const idx = groupTabs.findIndex((t) => t.id === windowId)
          const next = groupTabs[idx - 1] ?? groupTabs[idx + 1]
          if (next) {
            setActiveTab(groupId, next.id)
          }
        }
      }

      closeWindow(windowId)
    },
    [windows, closeWindow, playbackSession, activeTabMap, setActiveTab],
  )

  const handleDropFileToTabBar = useCallback(
    (
      targetWindowId: string,
      data: {
        path: string
        isDirectory: boolean
        source: import('@/lib/use-workspace').WorkspaceSource
      },
    ) => {
      const dir = data.isDirectory ? '' : data.path.split(/[/\\]/).slice(0, -1).join('/')
      openInNewTab(
        targetWindowId,
        { path: data.path, isDirectory: data.isDirectory },
        dir,
        data.source,
      )
    },
    [openInNewTab],
  )

  const { data: authConfig } = useQuery({
    queryKey: ['auth-config'],
    queryFn: () =>
      api<{ enabled: boolean; shareLinkDomain?: string; editableFolders: string[] }>(
        '/api/auth/config',
      ),
    enabled: !shareConfig,
  })

  const editableFolders = shareConfig
    ? [shareConfig.sharePath]
    : (authConfig?.editableFolders ?? [])
  const playbackContext = useMemo(
    () => workspaceSourceToMediaContext(playbackSource),
    [playbackSource],
  )
  const { settings } = useSettings('', !shareConfig)
  const defaultSource = useMemo(
    () =>
      shareConfig
        ? { kind: 'share' as const, token: shareConfig.token, sharePath: shareConfig.sharePath }
        : { kind: 'local' as const, rootPath: null },
    [shareConfig],
  )
  const handleAddToTaskbar = useCallback(
    (file: { path: string; isDirectory: boolean; name: string }) => {
      addPinnedItem({
        path: file.path,
        isDirectory: file.isDirectory,
        title: file.name,
        customIconName: settings.customIcons[file.path] ?? null,
        source: defaultSource,
      })
    },
    [addPinnedItem, defaultSource, settings.customIcons],
  )
  const currentMediaFile = useMediaPlayer((state) => state.currentFile)
  const currentMediaType = useMediaPlayer((state) => state.mediaType)
  const mediaPlayerIsPlaying = useMediaPlayer((state) => state.isPlaying)
  const { getIcon } = useFileIcon({
    customIcons: settings.customIcons,
    playingPath: playbackSession.state.playing,
    currentFile: currentMediaFile,
    mediaPlayerIsPlaying,
    mediaType: currentMediaType,
  })
  const taskbarItems = useMemo(
    () =>
      windowGroups.map((group) => {
        const groupWindows = group.windows
        const groupId = group.groupId
        const leader = groupWindows[0]
        const activeTabId = activeTabMap[groupId] ?? leader?.id
        const displayWindow =
          groupWindows.find((w) => w.id === activeTabId) ?? leader ?? groupWindows[0]
        const tabCount = groupWindows.length
        const path =
          displayWindow.iconPath ??
          (displayWindow.type === 'browser'
            ? (displayWindow.initialState.dir ?? '')
            : displayWindow.type === 'player'
              ? (playbackSession.state.playing ?? '')
              : (displayWindow.initialState.viewing ?? ''))
        const isDir = displayWindow.type === 'browser'
        const tooltip = path ? `${isDir ? 'Folder' : 'File'}: ${path}` : displayWindow.title
        const dragData =
          path && displayWindow.source
            ? {
                path,
                isDirectory: isDir,
                sourceKind: displayWindow.source.kind,
                sourceToken: displayWindow.source.token,
              }
            : undefined
        return {
          id: groupId,
          label: tabCount > 1 ? `${displayWindow.title} (+${tabCount - 1})` : displayWindow.title,
          active: groupWindows.some((w) => w.id === activeWindowId),
          tooltip,
          dragData,
          icon: getIcon(
            displayWindow.iconType ??
              (displayWindow.type === 'browser'
                ? MediaType.FOLDER
                : displayWindow.type === 'player'
                  ? MediaType.VIDEO
                  : displayWindow.initialState.viewing
                    ? getMediaType(displayWindow.initialState.viewing.split('.').pop() ?? '')
                    : MediaType.OTHER),
            displayWindow.iconPath ??
              (displayWindow.type === 'browser'
                ? (displayWindow.initialState.dir ?? '')
                : displayWindow.type === 'player'
                  ? (playbackSession.state.playing ?? '')
                  : (displayWindow.initialState.viewing ?? '')),
            (displayWindow.iconType ?? MediaType.OTHER) === MediaType.AUDIO,
            (displayWindow.iconType ??
              (displayWindow.type === 'player' ? MediaType.VIDEO : MediaType.OTHER)) ===
              MediaType.VIDEO,
            displayWindow.iconIsVirtual ?? false,
          ),
          onSelect: () => {
            const leaderId = leader?.id ?? groupWindows[0]?.id
            const isMinimized = leader?.layout?.minimized ?? false
            const isActive = groupWindows.some((w) => w.id === activeWindowId)
            if (isMinimized) {
              focusWindow(leaderId)
            } else if (isActive) {
              setWindowMinimized(leaderId, true)
            } else {
              focusWindow(leaderId)
            }
          },
          onClose: () => {
            for (const w of groupWindows) {
              if (w.type === 'player') playbackSession.closePlayer()
              closeWindow(w.id)
            }
          },
        }
      }),
    [
      windowGroups,
      activeWindowId,
      activeTabMap,
      focusWindow,
      setWindowMinimized,
      getIcon,
      playbackSession,
      closeWindow,
    ],
  )

  const pinnedTaskbarItemViews = useMemo((): PinnedTaskbarItemView[] => {
    return pinnedTaskbarItems.map((pin) => {
      const customName = pin.customIconName ?? settings.customIcons[pin.path]
      const mediaType = pin.isDirectory
        ? MediaType.FOLDER
        : getMediaType(pin.path.split('.').pop() ?? '')
      const iconNode = customName
        ? (() => {
            const C = getIconComponent(customName)
            return C ? (
              <C className='h-5 w-5 text-muted-foreground' />
            ) : (
              getIcon(
                mediaType,
                pin.path,
                mediaType === MediaType.AUDIO,
                mediaType === MediaType.VIDEO,
                false,
              )
            )
          })()
        : getIcon(
            mediaType,
            pin.path,
            mediaType === MediaType.AUDIO,
            mediaType === MediaType.VIDEO,
            false,
          )
      const tooltip = `${pin.isDirectory ? 'Folder' : 'File'}: ${pin.path}`
      const dragData = {
        path: pin.path,
        isDirectory: pin.isDirectory,
        sourceKind: pin.source.kind,
        sourceToken: pin.source.token,
      }
      return {
        id: pin.id,
        label: pin.title,
        icon: iconNode,
        tooltip,
        dragData,
        onSelect: () => {
          if (pin.isDirectory) {
            openBrowserWindow({ source: pin.source, initialState: { dir: pin.path } })
          } else if (mediaType === MediaType.VIDEO || mediaType === MediaType.AUDIO) {
            const parentDir = pin.path.split(/[/\\]/).slice(0, -1).join('/')
            requestPlay({ source: pin.source, path: pin.path, dir: parentDir })
          } else {
            const parentDir = pin.path.split(/[/\\]/).slice(0, -1).join('/')
            openViewerWindow({
              source: pin.source,
              title: pin.title,
              initialState: { dir: parentDir, viewing: pin.path },
            })
          }
        },
        onUnpin: () => removePinnedItem(pin.id),
      }
    })
  }, [
    pinnedTaskbarItems,
    settings.customIcons,
    getIcon,
    openBrowserWindow,
    openViewerWindow,
    requestPlay,
    removePinnedItem,
  ])

  return (
    <Layout
      items={taskbarItems}
      pinnedItems={pinnedTaskbarItemViews}
      onNewBrowser={() => openBrowserWindow()}
      taskbarRightSlot={
        <>
          <AudioPlayer
            session={playbackSession}
            mediaContext={playbackContext}
            onShowVideo={() => {
              playbackSession.setAudioOnly(false)
              openPlayerWindow()
            }}
          />
          <ThemeSwitcher variant='taskbar' />
        </>
      }
      emptyState={
        <div className='flex h-full items-center justify-center p-6'>
          <div className='w-full max-w-md rounded-xl border border-border bg-card/95 p-8 text-center shadow-2xl backdrop-blur'>
            <div className='space-y-3'>
              <div className='text-lg font-medium'>No windows are open</div>
              <div className='text-sm text-muted-foreground'>
                Start a browser window to build your workspace.
              </div>
              <Button onClick={() => openBrowserWindow()}>Open Browser</Button>
            </div>
          </div>
        </div>
      }
    >
      <div
        ref={containerRef}
        className='relative h-full w-full overflow-hidden bg-[radial-gradient(circle_at_top,var(--color-foreground)/0.03,transparent_28%),linear-gradient(to_bottom,var(--color-foreground)/0.02,transparent)]'
      >
        <SnapPreview />
        {windowGroups.map((group) => (
          <WindowGroup
            key={group.groupId}
            tabs={group.windows}
            activeTabId={activeTabMap[group.groupId] ?? null}
            editableFolders={editableFolders}
            playbackSession={playbackSession}
            activeWindowId={activeWindowId}
            onFocus={focusWindow}
            onMinimize={(windowId) => setWindowMinimized(windowId, true)}
            onToggleMaximize={toggleWindowFullscreen}
            onClose={(windowId) => {
              const w = windows.find((win) => win.id === windowId)
              if (!w) return
              const groupId = w.tabGroupId ?? w.id
              const groupWindows = windows.filter((win) => (win.tabGroupId ?? win.id) === groupId)
              for (const win of groupWindows) {
                if (win.type === 'player') playbackSession.closePlayer()
                closeWindow(win.id)
              }
            }}
            onUpdateBounds={updateWindowBounds}
            onResizeSnapped={resizeSnappedWindow}
            onDragMove={handleDragMove}
            onDragStop={handleDragStop}
            onPresentationChange={updateWindowPresentation}
            onNavigationStateChange={handleNavigationStateChange}
            onRequestPlay={(source, path, dir) => requestPlay({ source, path, dir })}
            onRequestView={(source, path, dir) =>
              openViewerWindow({
                title: path.split(/[/\\]/).filter(Boolean).at(-1) || 'Viewer',
                source,
                initialState: { dir, viewing: path },
              })
            }
            onOpenLayoutPicker={(windowId, anchorRect) => setLayoutPicker({ windowId, anchorRect })}
            onSelectTab={setActiveTab}
            onCloseTab={handleCloseTab}
            onAddTab={addTabToGroup}
            onOpenInNewTabInSameWindow={openInNewTab}
            onDetachTab={handleDetachTab}
            onRestoreDrag={handleRestoreDrag}
            onDropFileToTabBar={handleDropFileToTabBar}
            onAddToTaskbar={handleAddToTaskbar}
          />
        ))}
        {layoutPicker && (
          <TilingLayoutPicker
            anchorRect={layoutPicker.anchorRect}
            containerRef={containerRef}
            onSelectZone={handleLayoutSelect}
            onSelectFullscreen={handleLayoutFullscreen}
            onClose={() => setLayoutPicker(null)}
          />
        )}
      </div>
    </Layout>
  )
}

// solid/src/WorkspacePage.tsx
import type { GlobalSettings } from '@/lib/use-settings'
import type { FileItem } from '@/lib/types'
import { MediaType } from '@/lib/types'
import { getMediaType } from '@/lib/media-utils'
import { computeSnappedResizeWindows } from '@/lib/workspace-session-store'
import {
  createDefaultBounds,
  createFullscreenBounds,
  createWindowLayout,
  PLAYER_WINDOW_ID,
} from '@/lib/workspace-geometry'
import type {
  PersistedWorkspaceState,
  PinnedTaskbarItem,
  SnapZone,
  WorkspaceSource,
  WorkspaceWindowDefinition,
} from '@/lib/use-workspace'
import {
  normalizePersistedWorkspaceState,
  snapZoneToBoundsWithOccupied,
  workspaceStorageBaseKey,
  workspaceStorageSessionKey,
} from '@/lib/use-workspace'
import { detectSnapZone, type SnapDetectResult } from '@/lib/use-snap-zones'
import { useMutation, useQuery, useQueryClient } from '@tanstack/solid-query'
import { api, post } from '@/lib/api'
import { queryKeys } from '@/lib/query-keys'
import File from 'lucide-solid/icons/file'
import FolderOpen from 'lucide-solid/icons/folder-open'
import Folder from 'lucide-solid/icons/folder'
import { For, Show, createEffect, createMemo, createSignal, onCleanup, untrack } from 'solid-js'
import { useBrowserHistory, navigateSearchParams } from './browser-history'
import { applySnapPreviewLayout } from './workspace/snap-preview'
import { WorkspaceTilingPicker } from './workspace/WorkspaceTilingPicker'
import { WorkspaceBrowserPane, type WorkspaceShareConfig } from './workspace/WorkspaceBrowserPane'
import { WorkspaceViewerPane } from './workspace/WorkspaceViewerPane'
import { WorkspaceWindowChrome, type WorkspaceBounds } from './workspace/WorkspaceWindowChrome'

const DEFAULT_SOURCE: WorkspaceSource = { kind: 'local', rootPath: null }

function isWorkspaceRoute(pathname: string) {
  return pathname === '/workspace' || /^\/share\/[^/]+\/workspace\/?$/.test(pathname)
}

function defaultPersistedState(source: WorkspaceSource): PersistedWorkspaceState {
  return {
    windows: [
      {
        id: 'workspace-window-1',
        type: 'browser',
        title: 'Browser 1',
        iconName: null,
        iconPath: '',
        iconType: MediaType.FOLDER,
        iconIsVirtual: false,
        source,
        initialState: {},
        tabGroupId: null,
        layout: createWindowLayout(undefined, createDefaultBounds(0, 'browser'), 1),
      },
    ],
    activeWindowId: 'workspace-window-1',
    activeTabMap: {},
    nextWindowId: 2,
    pinnedTaskbarItems: [],
  }
}

function persistWorkspaceState(storageKey: string, state: PersistedWorkspaceState) {
  try {
    const serializable = {
      ...state,
      windows: state.windows.filter((w) => w.id !== PLAYER_WINDOW_ID),
      pinnedTaskbarItems: state.pinnedTaskbarItems ?? [],
    }
    localStorage.setItem(storageKey, JSON.stringify(serializable))
  } catch {}
}

function loadPersisted(storageKey: string): PersistedWorkspaceState | null {
  const raw = localStorage.getItem(storageKey)
  if (!raw) return null
  try {
    return normalizePersistedWorkspaceState(JSON.parse(raw) as unknown)
  } catch {
    return null
  }
}

type AuthConfig = { enabled: boolean; editableFolders: string[] }

export type WorkspacePageProps = {
  shareConfig?: { token: string; sharePath: string } | null
  shareWorkspaceTaskbarPins?: PinnedTaskbarItem[]
  shareCanEdit?: boolean
}

export function WorkspacePage(props: WorkspacePageProps = {}) {
  const history = useBrowserHistory()
  const queryClient = useQueryClient()

  const shareConfig = () => props.shareConfig ?? null

  const browserSource = createMemo(
    (): WorkspaceSource =>
      shareConfig()
        ? {
            kind: 'share',
            token: shareConfig()!.token,
            sharePath: shareConfig()!.sharePath,
          }
        : DEFAULT_SOURCE,
  )

  const storageSessionKeyFull = createMemo(() => {
    const loc = history()
    const sid = new URLSearchParams(loc.search).get('ws') ?? ''
    const base = workspaceStorageBaseKey(shareConfig()?.token ?? null)
    return { sid, key: sid ? workspaceStorageSessionKey(base, sid) : '' }
  })

  const [workspace, setWorkspace] = createSignal<PersistedWorkspaceState | null>(null)

  let workspaceAreaEl: HTMLDivElement | undefined
  let snapPreviewEl: HTMLDivElement | undefined
  const [layoutPicker, setLayoutPicker] = createSignal<{
    windowId: string
    anchor: DOMRect
  } | null>(null)
  let dragZoneRef: SnapDetectResult | null = null
  let draggedWindowIdForSnap: string | null = null

  const [pinsHydratedFor, setPinsHydratedFor] = createSignal('')

  const settingsQuery = useQuery(() => ({
    queryKey: queryKeys.settings(),
    queryFn: () => api<GlobalSettings>('/api/settings'),
    staleTime: Infinity,
    enabled: !shareConfig(),
  }))

  const authQuery = useQuery(() => ({
    queryKey: queryKeys.authConfig(),
    queryFn: () => api<AuthConfig>('/api/auth/config'),
    staleTime: Infinity,
    enabled: !shareConfig(),
  }))

  const editableFolders = createMemo((): string[] => {
    if (shareConfig()) return []
    return authQuery.data?.editableFolders ?? []
  })

  const sharePanel = createMemo((): WorkspaceShareConfig | null => {
    const c = shareConfig()
    if (!c) return null
    return { token: c.token, sharePath: c.sharePath }
  })

  const serverPinsReady = createMemo(() => (shareConfig() ? true : settingsQuery.isSuccess))

  const serverPinsList = createMemo((): PinnedTaskbarItem[] => {
    if (shareConfig()) return props.shareWorkspaceTaskbarPins ?? []
    return settingsQuery.data?.workspaceTaskbarPins ?? []
  })

  const persistPinsMutation = useMutation(() => ({
    mutationFn: (items: PinnedTaskbarItem[]) => {
      const c = shareConfig()
      if (c) {
        return post(`/api/share/${c.token}/workspaceTaskbarPins`, { items })
      }
      return post('/api/settings/workspaceTaskbarPins', { items })
    },
    onSettled: () => {
      const c = shareConfig()
      if (c) {
        void queryClient.invalidateQueries({ queryKey: queryKeys.shareInfo(c.token) })
      } else {
        void queryClient.invalidateQueries({ queryKey: queryKeys.settings() })
      }
    },
  }))

  createEffect(() => {
    const loc = history()
    if (!isWorkspaceRoute(loc.pathname)) return
    let sid = new URLSearchParams(loc.search).get('ws') ?? ''
    if (!sid) {
      sid = crypto.randomUUID()
      navigateSearchParams({ ws: sid }, 'replace')
    }
    const base = workspaceStorageBaseKey(shareConfig()?.token ?? null)
    const key = workspaceStorageSessionKey(base, sid)
    untrack(() => {
      const loaded = loadPersisted(key)
      const src = browserSource()
      setWorkspace(loaded ?? defaultPersistedState(src))
      setPinsHydratedFor('')
    })
  })

  createEffect(() => {
    const { key } = storageSessionKeyFull()
    const w = workspace()
    if (!key || !w) return
    persistWorkspaceState(key, w)
  })

  createEffect(() => {
    if (!serverPinsReady()) return
    const { key } = storageSessionKeyFull()
    const w = workspace()
    if (!key || !w) return
    if (pinsHydratedFor() === key) return

    const serverPins = serverPinsList()
    untrack(() => {
      if (serverPins.length > 0) {
        setWorkspace((prev) => (prev ? { ...prev, pinnedTaskbarItems: serverPins } : prev))
      } else if ((w.pinnedTaskbarItems?.length ?? 0) > 0) {
        void persistPinsMutation.mutateAsync(w.pinnedTaskbarItems ?? [])
      }
    })
    setPinsHydratedFor(key)
  })

  function focusWindow(windowId: string) {
    const w = workspace()
    if (!w) return
    const maxZ = Math.max(...w.windows.map((x) => x.layout?.zIndex ?? 1), 1)
    setWorkspace({
      ...w,
      activeWindowId: windowId,
      windows: w.windows.map((win) =>
        win.id === windowId ? { ...win, layout: { ...win.layout, zIndex: maxZ + 1 } } : win,
      ),
    })
  }

  function closeWindow(windowId: string) {
    const w = workspace()
    if (!w) return
    const next = w.windows.filter((x) => x.id !== windowId)
    let active = w.activeWindowId
    if (active === windowId) {
      active = next[next.length - 1]?.id ?? active
    }
    setWorkspace({ ...w, windows: next, activeWindowId: active })
  }

  function updateWindowViewing(windowId: string, viewing: string) {
    const w = workspace()
    if (!w) return
    const title = viewing.split(/[/\\]/).pop() ?? 'File'
    setWorkspace({
      ...w,
      windows: w.windows.map((win) =>
        win.id === windowId
          ? { ...win, title, initialState: { ...win.initialState, viewing } }
          : win,
      ),
    })
  }

  function navigateDir(windowId: string, dir: string) {
    const w = workspace()
    if (!w) return
    setWorkspace({
      ...w,
      windows: w.windows.map((win) =>
        win.id === windowId ? { ...win, initialState: { ...win.initialState, dir } } : win,
      ),
    })
  }

  function openBrowser(options?: { source?: WorkspaceSource; initialState?: { dir?: string } }) {
    const w = workspace()
    if (!w) return
    const n = w.nextWindowId
    const id = `workspace-window-${n}`
    const source = options?.source ?? browserSource()
    const newWin: WorkspaceWindowDefinition = {
      id,
      type: 'browser',
      title: `Browser ${n}`,
      iconName: null,
      iconPath: '',
      iconType: MediaType.FOLDER,
      iconIsVirtual: false,
      source,
      initialState: options?.initialState?.dir != null ? { dir: options.initialState.dir } : {},
      tabGroupId: null,
      layout: createWindowLayout(undefined, createDefaultBounds(w.windows.length, 'browser'), n),
    }
    const maxZ = Math.max(...w.windows.map((x) => x.layout?.zIndex ?? 1), 1)
    newWin.layout = { ...newWin.layout, zIndex: maxZ + 1 }
    setWorkspace({
      ...w,
      windows: [...w.windows, newWin],
      nextWindowId: n + 1,
      activeWindowId: id,
    })
  }

  function openViewerFromBrowser(windowId: string, file: FileItem) {
    const w = workspace()
    const winDef = w?.windows.find((x) => x.id === windowId)
    if (!winDef) return
    openViewer(windowId, file, winDef.source)
  }

  function openViewer(_fromWindowId: string, file: FileItem, source: WorkspaceSource) {
    const w = workspace()
    if (!w) return
    const n = w.nextWindowId
    const id = `workspace-window-${n}`
    const parentDir = file.path.split(/[/\\]/).slice(0, -1).join('/') || ''
    const newWin: WorkspaceWindowDefinition = {
      id,
      type: 'viewer',
      title: file.name,
      iconName: null,
      iconPath: file.path,
      iconType: file.type,
      iconIsVirtual: false,
      source,
      initialState: { dir: parentDir, viewing: file.path },
      tabGroupId: null,
      layout: createWindowLayout(undefined, createDefaultBounds(w.windows.length, 'viewer'), n),
    }
    const maxZ = Math.max(...w.windows.map((x) => x.layout?.zIndex ?? 1), 1)
    newWin.layout = { ...newWin.layout, zIndex: maxZ + 1 }
    setWorkspace({
      ...w,
      windows: [...w.windows, newWin],
      nextWindowId: n + 1,
      activeWindowId: id,
    })
  }

  function addPinnedItem(file: FileItem) {
    const w = workspace()
    if (!w) return
    const source = browserSource()
    const pinKey = (p: PinnedTaskbarItem) => `${p.path}:${p.source.kind}:${p.source.token ?? ''}`
    const newKey = `${file.path}:${source.kind}:${source.token ?? ''}`
    if ((w.pinnedTaskbarItems ?? []).some((p) => pinKey(p) === newKey)) return
    const customIcons = settingsQuery.data?.customIcons ?? {}
    const item: PinnedTaskbarItem = {
      id: crypto.randomUUID(),
      path: file.path,
      isDirectory: file.isDirectory,
      title: file.name,
      customIconName: customIcons[file.path] ?? null,
      source,
    }
    const next = [...(w.pinnedTaskbarItems ?? []), item]
    setWorkspace({ ...w, pinnedTaskbarItems: next })
    void persistPinsMutation.mutateAsync(next)
  }

  function removePinnedItem(id: string) {
    const w = workspace()
    if (!w) return
    const next = (w.pinnedTaskbarItems ?? []).filter((p) => p.id !== id)
    setWorkspace({ ...w, pinnedTaskbarItems: next })
    void persistPinsMutation.mutateAsync(next)
  }

  function selectPinned(pin: PinnedTaskbarItem) {
    if (pin.isDirectory) {
      openBrowser({ source: pin.source, initialState: { dir: pin.path } })
      return
    }
    const ext = pin.path.split('.').pop()?.toLowerCase() ?? ''
    const type = getMediaType(ext)
    if (type === MediaType.VIDEO || type === MediaType.AUDIO) {
      return
    }
    const synthetic: FileItem = {
      path: pin.path,
      name: pin.title,
      isDirectory: false,
      isVirtual: false,
      size: 0,
      type,
      extension: ext,
    }
    openViewer('', synthetic, pin.source)
  }

  function getZoneBoundsForDrag(zone: SnapZone): WorkspaceBounds {
    const w = workspace()
    if (!w) return snapZoneToBoundsWithOccupied(zone, [])
    const ex = draggedWindowIdForSnap
    const occupied = w.windows
      .filter((x) => x.id !== ex && x.layout?.snapZone && x.layout.bounds)
      .map((x) => ({ bounds: x.layout!.bounds!, snapZone: x.layout!.snapZone! }))
    return snapZoneToBoundsWithOccupied(zone, occupied)
  }

  function handleDragPointerMove(windowId: string, clientX: number, clientY: number) {
    draggedWindowIdForSnap = windowId
    const c = workspaceAreaEl
    const p = snapPreviewEl
    if (!c || !p) return
    const rect = c.getBoundingClientRect()
    const z = detectSnapZone(clientX - rect.left, clientY - rect.top, rect.width, rect.height)
    dragZoneRef = z
    applySnapPreviewLayout(p, z, c, getZoneBoundsForDrag)
  }

  function restoreDrag(windowId: string, clientX: number, clientY: number) {
    const w = workspace()
    const container = workspaceAreaEl?.getBoundingClientRect()
    if (!w || !container) return
    const win = w.windows.find((x) => x.id === windowId)
    if (!win) return
    const currentBounds = win.layout?.bounds
    const restoreBounds = win.layout?.restoreBounds
    const restoredW = restoreBounds?.width ?? currentBounds?.width ?? 500
    const currentWidth = currentBounds?.width ?? restoredW
    const oX = container.left
    const grabRatio = currentBounds
      ? Math.min(Math.max((clientX - oX - currentBounds.x) / currentWidth, 0), 1)
      : 0.5
    const newX = clientX - oX - restoredW * grabRatio
    const newY = currentBounds?.y ?? 0
    unsnapWindow(windowId, { x: newX, y: newY })
  }

  function unsnapWindow(windowId: string, drop: { x: number; y: number } | null) {
    setWorkspace((prev) => {
      if (!prev) return prev
      return {
        ...prev,
        windows: prev.windows.map((win) => {
          if (win.id !== windowId) return win
          const restored = win.layout?.restoreBounds ?? win.layout?.bounds
          return {
            ...win,
            layout: {
              ...win.layout,
              snapZone: null,
              fullscreen: false,
              bounds:
                drop && restored
                  ? { x: drop.x, y: drop.y, width: restored.width, height: restored.height }
                  : (restored ?? win.layout?.bounds ?? null),
              restoreBounds: null,
            },
          }
        }),
      }
    })
  }

  function snapWindowState(windowId: string, zone: SnapZone) {
    setWorkspace((prev) => {
      if (!prev) return prev
      const maxZ = Math.max(...prev.windows.map((x) => x.layout?.zIndex ?? 1), 1)
      const occupied = prev.windows
        .filter((x) => x.id !== windowId && x.layout?.snapZone && x.layout.bounds)
        .map((x) => ({ bounds: x.layout!.bounds!, snapZone: x.layout!.snapZone! }))
      const snapBounds = snapZoneToBoundsWithOccupied(zone, occupied)
      return {
        ...prev,
        activeWindowId: windowId,
        windows: prev.windows.map((win) =>
          win.id === windowId
            ? {
                ...win,
                layout: {
                  ...win.layout,
                  fullscreen: false,
                  snapZone: zone,
                  minimized: false,
                  zIndex: maxZ + 1,
                  bounds: snapBounds,
                  restoreBounds: win.layout?.restoreBounds ?? win.layout?.bounds ?? null,
                },
              }
            : win,
        ),
      }
    })
  }

  function toggleFullscreenWindow(windowId: string) {
    setWorkspace((prev) => {
      if (!prev) return prev
      const maxZ = Math.max(...prev.windows.map((x) => x.layout?.zIndex ?? 1), 1)
      return {
        ...prev,
        activeWindowId: windowId,
        windows: prev.windows.map((win) => {
          if (win.id !== windowId) return win
          const currentBounds = win.layout?.bounds ?? createDefaultBounds(0, win.type)
          const isFs = win.layout?.fullscreen ?? false
          return {
            ...win,
            layout: {
              ...win.layout,
              fullscreen: !isFs,
              snapZone: null,
              minimized: false,
              zIndex: maxZ + 1,
              bounds: isFs
                ? (win.layout?.restoreBounds ?? currentBounds)
                : createFullscreenBounds(),
              restoreBounds: isFs ? null : currentBounds,
            },
          }
        }),
      }
    })
  }

  function setWindowMinimized(windowId: string, minimized: boolean) {
    setWorkspace((prev) =>
      prev
        ? {
            ...prev,
            windows: prev.windows.map((win) =>
              win.id === windowId ? { ...win, layout: { ...win.layout, minimized } } : win,
            ),
          }
        : prev,
    )
  }

  function updateWindowBounds(windowId: string, bounds: WorkspaceBounds) {
    setWorkspace((prev) =>
      prev
        ? {
            ...prev,
            windows: prev.windows.map((win) =>
              win.id === windowId ? { ...win, layout: { ...win.layout, bounds } } : win,
            ),
          }
        : prev,
    )
  }

  function resizeSnappedWindowBounds(windowId: string, bounds: WorkspaceBounds, direction: string) {
    setWorkspace((prev) =>
      prev
        ? {
            ...prev,
            windows: computeSnappedResizeWindows(prev.windows, windowId, bounds, direction),
          }
        : prev,
    )
  }

  function onDragPointerEnd(
    windowId: string,
    bounds: WorkspaceBounds,
    clientX: number,
    clientY: number,
  ) {
    const zone = dragZoneRef
    const c = workspaceAreaEl
    const p = snapPreviewEl
    if (c && p) applySnapPreviewLayout(p, null, c, getZoneBoundsForDrag)
    dragZoneRef = null
    draggedWindowIdForSnap = null

    if (zone === 'top') {
      toggleFullscreenWindow(windowId)
      return
    }
    if (zone) {
      snapWindowState(windowId, zone as SnapZone)
      return
    }

    const w = workspace()?.windows.find((x) => x.id === windowId)
    if (w?.layout?.snapZone || w?.layout?.fullscreen) {
      unsnapWindow(windowId, { x: bounds.x, y: bounds.y })
      return
    }
    updateWindowBounds(windowId, bounds)
  }

  const [pinMenu, setPinMenu] = createSignal<{
    x: number
    y: number
    pinId: string
  } | null>(null)

  createEffect(() => {
    const m = pinMenu()
    if (!m) return
    const onDoc = (e: MouseEvent) => {
      const t = e.target as Element | null
      if (t?.closest?.('[data-pin-context-menu]')) return
      setPinMenu(null)
    }
    document.addEventListener('mousedown', onDoc)
    onCleanup(() => document.removeEventListener('mousedown', onDoc))
  })

  const visibleWindows = createMemo(
    () => workspace()?.windows.filter((x) => !x.layout?.minimized) ?? [],
  )
  const pinnedItems = createMemo(() => workspace()?.pinnedTaskbarItems ?? [])

  return (
    <div class='workspace-layout pointer-events-auto fixed inset-0 flex flex-col overflow-hidden bg-background select-none'>
      <div
        class='relative min-h-0 flex-1 overflow-hidden'
        ref={(el) => {
          workspaceAreaEl = el
        }}
      >
        <div
          ref={(el) => {
            snapPreviewEl = el ?? undefined
          }}
          data-snap-preview
          class='pointer-events-none absolute rounded-sm border-2 border-blue-400/50 bg-blue-500/15 transition-all duration-150'
          style={{ display: 'none', 'z-index': 99999 }}
        />
        <For each={visibleWindows()}>
          {(win) => (
            <WorkspaceWindowChrome
              windowId={win.id}
              groupId={win.tabGroupId ?? win.id}
              workspace={workspace}
              isActive={workspace()?.activeWindowId === win.id}
              containerEl={() => workspaceAreaEl}
              onFocusWindow={focusWindow}
              onClose={closeWindow}
              onMinimize={(id) => setWindowMinimized(id, true)}
              onToggleFullscreen={toggleFullscreenWindow}
              onOpenLayoutPicker={(windowId, rect) => setLayoutPicker({ windowId, anchor: rect })}
              onRestoreDrag={restoreDrag}
              onDragPointerMove={handleDragPointerMove}
              onDragPointerEnd={onDragPointerEnd}
              onDragDuringMove={updateWindowBounds}
              onResizeSnapped={resizeSnappedWindowBounds}
              onUpdateBounds={updateWindowBounds}
            >
              <Show when={win.type === 'browser'}>
                <WorkspaceBrowserPane
                  windowId={win.id}
                  workspace={workspace}
                  sharePanel={sharePanel}
                  editableFolders={editableFolders()}
                  onNavigateDir={navigateDir}
                  onOpenViewer={openViewerFromBrowser}
                  onAddToTaskbar={addPinnedItem}
                />
              </Show>
              <Show when={win.type === 'viewer'}>
                <WorkspaceViewerPane
                  windowId={win.id}
                  workspace={workspace}
                  sharePanel={sharePanel}
                  editableFolders={editableFolders()}
                  shareCanEdit={props.shareConfig ? (props.shareCanEdit ?? false) : false}
                  onUpdateViewing={updateWindowViewing}
                />
              </Show>
            </WorkspaceWindowChrome>
          )}
        </For>
        <Show when={layoutPicker()}>
          {(get) => {
            const p = get()
            const c = workspaceAreaEl
            if (!c) return null
            return (
              <WorkspaceTilingPicker
                anchorRect={p.anchor}
                container={c}
                onSelectZone={(zone) => {
                  snapWindowState(p.windowId, zone)
                  setLayoutPicker(null)
                }}
                onSelectFullscreen={() => {
                  toggleFullscreenWindow(p.windowId)
                  setLayoutPicker(null)
                }}
                onClose={() => setLayoutPicker(null)}
              />
            )
          }}
        </Show>
      </div>

      <div class='relative bg-background px-3' style={{ 'z-index': '999999' }}>
        <div class='flex h-8 items-center gap-2'>
          <button
            type='button'
            title='Open browser window'
            class='flex h-7 w-7 shrink-0 items-center justify-center rounded-none text-amber-500 hover:bg-amber-500/15 hover:text-amber-400'
            onClick={() => openBrowser()}
          >
            <FolderOpen class='h-5 w-5' stroke-width={1.75} />
          </button>

          <div class='flex min-w-0 flex-1 items-center gap-2 overflow-x-auto'>
            <For each={pinnedItems()}>
              {(pin) => {
                const tooltip = `${pin.isDirectory ? 'Folder' : 'File'}: ${pin.path}`
                return (
                  <button
                    type='button'
                    title={tooltip}
                    aria-label={tooltip}
                    class='flex h-7 w-7 shrink-0 items-center justify-center rounded-none text-muted-foreground hover:bg-muted hover:text-foreground'
                    onClick={() => selectPinned(pin)}
                    onContextMenu={(e) => {
                      e.preventDefault()
                      setPinMenu({ x: e.clientX, y: e.clientY, pinId: pin.id })
                    }}
                  >
                    <Show
                      when={pin.isDirectory}
                      fallback={<File class='h-5 w-5' stroke-width={1.75} />}
                    >
                      <Folder class='h-5 w-5' stroke-width={1.75} />
                    </Show>
                  </button>
                )
              }}
            </For>
          </div>
        </div>
      </div>

      <Show when={pinMenu()}>
        {(get) => {
          const m = get()
          return (
            <div
              data-pin-context-menu
              class='fixed z-[1000000] min-w-36 rounded-md border border-border bg-popover p-1 text-popover-foreground shadow-md'
              style={{ left: `${m.x}px`, top: `${m.y}px` }}
              role='menu'
            >
              <button
                type='button'
                data-slot='context-menu-item'
                class='flex w-full cursor-pointer items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-none select-none hover:bg-accent hover:text-accent-foreground'
                role='menuitem'
                onClick={() => {
                  removePinnedItem(m.pinId)
                  setPinMenu(null)
                }}
              >
                Unpin
              </button>
            </div>
          )
        }}
      </Show>
    </div>
  )
}
