// components/viewers/video-player.tsx
'use client'

import { useEffect, useRef, useState, useCallback } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { Minimize2, Maximize2, X, ArrowUp, Headphones } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { useMediaPlayer } from '@/lib/use-media-player'
import {
  useVideoPlayerPosition,
  validatePosition,
  getDefaultPosition,
} from '@/lib/use-video-player-position'
import { useVideoPlaybackTime } from '@/lib/use-video-playback-time'
import {
  VideoPlayerContent,
  type VideoPlayerContentRef,
} from '@/components/viewers/video-player-content'

interface Position {
  x: number
  y: number
}

export function VideoPlayer() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const playerRef = useRef<HTMLDivElement>(null)
  const videoContentRef = useRef<VideoPlayerContentRef>(null)
  const [isMinimized, setIsMinimized] = useState(false)
  const [showScrollToTop, setShowScrollToTop] = useState(false)
  const [isDragging, setIsDragging] = useState(false)
  const dragOffset = useRef<Position>({ x: 0, y: 0 })

  const { position, setPosition } = useVideoPlayerPosition()
  const { getSavedTime, saveTime } = useVideoPlaybackTime()

  const {
    currentFile,
    mediaType,
    isPlaying,
    currentTime,
    setCurrentFile,
    setIsPlaying,
    setCurrentTime,
    setDuration,
  } = useMediaPlayer()

  const playingPath = searchParams.get('playing')
  const isAudioOnly = searchParams.get('audioOnly') === 'true'
  const fileName = (playingPath || '').split('/').pop() || ''

  const extension = (playingPath || '').split('.').pop()?.toLowerCase()
  const videoExtensions = ['mp4', 'webm', 'ogg', 'mov', 'avi', 'mkv']
  const isVideoFile = playingPath && videoExtensions.includes(extension || '')

  const handleDragStart = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!isMinimized) return
    const target = e.target as HTMLElement
    if (target.closest('button') || target.closest('video')) return

    setIsDragging(true)
    const rect = playerRef.current?.getBoundingClientRect()
    if (rect) {
      dragOffset.current = { x: e.clientX - rect.left, y: e.clientY - rect.top }
    }
  }

  useEffect(() => {
    if (!isDragging) return

    const handleMouseMove = (e: MouseEvent) => {
      const newX = e.clientX - dragOffset.current.x
      const newY = e.clientY - dragOffset.current.y
      const maxX = window.innerWidth - (playerRef.current?.offsetWidth || 320)
      const maxY = window.innerHeight - (playerRef.current?.offsetHeight || 300)
      setPosition({
        x: Math.max(0, Math.min(newX, maxX)),
        y: Math.max(0, Math.min(newY, maxY)),
      })
    }

    const handleMouseUp = () => setIsDragging(false)

    document.addEventListener('mousemove', handleMouseMove)
    document.addEventListener('mouseup', handleMouseUp)
    return () => {
      document.removeEventListener('mousemove', handleMouseMove)
      document.removeEventListener('mouseup', handleMouseUp)
    }
  }, [isDragging, setPosition])

  // Sync store when playing path changes
  useEffect(() => {
    if (!playingPath || !isVideoFile || isAudioOnly) return
    if (currentFile !== playingPath || mediaType !== 'video') {
      setCurrentFile(playingPath, 'video')
    }
  }, [playingPath, isVideoFile, isAudioOnly, currentFile, mediaType, setCurrentFile])

  const handleTimeUpdate = useCallback(
    (time: number) => {
      setCurrentTime(time)
      const video = videoContentRef.current?.getVideoElement()
      if (playingPath && video && !isNaN(video.duration) && video.duration > 0) {
        saveTime(playingPath, time, video.duration)
      }
    },
    [setCurrentTime, playingPath, saveTime],
  )

  const handlePlay = useCallback(() => setIsPlaying(true), [setIsPlaying])
  const handlePause = useCallback(() => setIsPlaying(false), [setIsPlaying])
  const handleDurationChange = useCallback(
    (duration: number) => setDuration(duration),
    [setDuration],
  )

  useEffect(() => {
    const handleScroll = () => {
      setShowScrollToTop(!isMinimized && window.scrollY > 200)
    }
    window.addEventListener('scroll', handleScroll)
    handleScroll()
    return () => window.removeEventListener('scroll', handleScroll)
  }, [isMinimized])

  const toggleMinimize = () => {
    const newMinimized = !isMinimized
    setIsMinimized(newMinimized)

    if (newMinimized && typeof window !== 'undefined') {
      const validatedPos = validatePosition(position)
      if (position.x === 0 && position.y === 0) {
        setPosition(getDefaultPosition())
      } else if (validatedPos.x !== position.x || validatedPos.y !== position.y) {
        setPosition(validatedPos)
      }
    }
  }

  const handleClose = () => {
    const video = videoContentRef.current?.getVideoElement()
    if (video) video.pause()
    window.location.href =
      window.location.pathname +
      window.location.search.replace(/[?&]playing=[^&]*/g, '').replace(/^&/, '?')
  }

  const handleAudioOnly = () => {
    const video = videoContentRef.current?.getVideoElement()
    if (video && playingPath) {
      setCurrentTime(video.currentTime)
      const params = new URLSearchParams(searchParams)
      params.set('audioOnly', 'true')
      router.replace(`/?${params.toString()}`, { scroll: false })
    }
  }

  if (!isVideoFile || isAudioOnly) return null

  const initialTime = getSavedTime(playingPath!) ?? (currentTime > 0 ? currentTime : 0)

  return (
    <>
      <div
        ref={playerRef}
        className={` ${isMinimized ? 'fixed z-40 w-80' : 'w-full bg-background'}`}
        style={isMinimized ? { left: `${position.x}px`, top: `${position.y}px` } : undefined}
      >
        <Card className={`py-0 ${isMinimized ? '' : 'w-full rounded-none border-x-0 border-t-0'}`}>
          <div className='bg-black'>
            <div
              className='bg-background/90 backdrop-blur-sm border-b border-border p-2 flex items-center justify-between z-10'
              onMouseDown={handleDragStart}
              style={{ cursor: isMinimized ? (isDragging ? 'grabbing' : 'grab') : 'default' }}
            >
              <span className='text-sm font-medium truncate flex-1 px-2'>{fileName}</span>
              <div className='flex items-center gap-1'>
                <Button
                  variant='ghost'
                  size='icon'
                  onClick={handleAudioOnly}
                  className='h-8 w-8'
                  aria-label='Audio only mode'
                >
                  <Headphones className='h-4 w-4' />
                </Button>
                <Button variant='ghost' size='icon' onClick={toggleMinimize} className='h-8 w-8'>
                  {isMinimized ? (
                    <Maximize2 className='h-4 w-4' />
                  ) : (
                    <Minimize2 className='h-4 w-4' />
                  )}
                </Button>
                <Button variant='ghost' size='icon' onClick={handleClose} className='h-8 w-8'>
                  <X className='h-4 w-4' />
                </Button>
              </div>
            </div>
            <VideoPlayerContent
              ref={videoContentRef}
              src={`/api/media/${playingPath}`}
              fileName={fileName}
              initialTime={initialTime}
              onTimeUpdate={handleTimeUpdate}
              onDurationChange={handleDurationChange}
              onPlay={handlePlay}
              onPause={handlePause}
              isPlaying={
                isPlaying && currentFile === playingPath && mediaType === 'video'
                  ? true
                  : !isPlaying && currentFile === playingPath && mediaType === 'video'
                    ? false
                    : undefined
              }
              maxHeight={isMinimized ? '180px' : '70vh'}
              minHeight={isMinimized ? '180px' : undefined}
              height={isMinimized ? '180px' : undefined}
              aspectRatio={isMinimized ? undefined : '16 / 9'}
            />
          </div>
        </Card>
      </div>

      {showScrollToTop && !isMinimized && (
        <Button
          variant='default'
          size='icon'
          onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
          className='flex fixed bottom-4 right-4 lg:bottom-8 lg:right-8 z-50 h-10 w-10 rounded-full shadow-lg'
          aria-label='Scroll to top'
        >
          <ArrowUp className='h-4 w-4' />
        </Button>
      )}
    </>
  )
}

// src/media/VideoPlayer.tsx
import { useMediaPlayer } from '@/lib/use-media-player'
import { useVideoPlaybackTime } from '@/lib/use-video-playback-time'
import {
  getDefaultPosition,
  useVideoPlayerPosition,
  validatePosition,
} from '@/lib/use-video-player-position'
import { createEffect, createMemo, createSignal, onCleanup, onMount, Show } from 'solid-js'
import Headphones from 'lucide-solid/icons/headphones'
import Maximize2 from 'lucide-solid/icons/maximize-2'
import Minimize2 from 'lucide-solid/icons/minimize-2'
import X from 'lucide-solid/icons/x'
import { createUrlSearchParamsMemo, useBrowserHistory } from '../browser-history'
import { closePlayer, setAudioOnly } from '../lib/url-state-actions'
import { buildAdminMediaUrl } from '../lib/build-media-url'

const VIDEO_EXTENSIONS = ['mp4', 'webm', 'ogg', 'mov', 'avi', 'mkv', 'm4v']

export function VideoPlayer() {
  const history = useBrowserHistory()
  const urlSearchParams = createUrlSearchParamsMemo(history)

  const playingPath = createMemo(() => urlSearchParams().get('playing'))

  const audioOnly = createMemo(() => urlSearchParams().get('audioOnly') === 'true')

  const extension = createMemo(() => (playingPath() || '').split('.').pop()?.toLowerCase() || '')
  const isVideoFile = createMemo(
    () => !!playingPath() && VIDEO_EXTENSIONS.includes(extension()) && !audioOnly(),
  )

  const mediaUrl = createMemo(() => {
    const path = playingPath()
    if (!path) return ''
    return buildAdminMediaUrl(path)
  })

  const fileName = createMemo(() => (playingPath() || '').split('/').pop() || '')

  const [isMinimized, setIsMinimized] = createSignal(false)
  const [position, setPositionView] = createSignal(useVideoPlayerPosition.getState().position)

  onMount(() => {
    const unsub = useVideoPlayerPosition.subscribe((s) => {
      setPositionView(s.position)
    })
    onCleanup(unsub)
  })

  const [videoEl, setVideoEl] = createSignal<HTMLVideoElement | undefined>()

  createEffect(() => {
    const path = playingPath()
    const url = mediaUrl()
    const vid = videoEl()
    if (!path || !isVideoFile() || !vid || !url) return

    useMediaPlayer.getState().setCurrentFile(path, 'video')

    const targetHref = new URL(url, window.location.origin).href
    const srcMismatch = vid.src !== targetHref

    const finish = () => {
      const st = useMediaPlayer.getState()
      const storeT = st.currentFile === path && st.mediaType === 'video' ? st.currentTime : 0
      const savedT = useVideoPlaybackTime.getState().getSavedTime(path) ?? 0
      const t = storeT > 0 ? storeT : savedT
      if (t > 0) {
        try {
          vid.currentTime = t
        } catch {
          /* ignore */
        }
      }
      void vid.play().catch(() => {})
    }

    let onCanPlay: () => void = () => {}

    if (srcMismatch) {
      onCanPlay = () => {
        vid.removeEventListener('canplay', onCanPlay)
        vid.removeEventListener('error', onCanPlay)
        finish()
      }
      vid.addEventListener('canplay', onCanPlay)
      vid.addEventListener('error', onCanPlay)
      vid.pause()
      vid.src = targetHref
      vid.load()
    } else {
      finish()
    }

    onCleanup(() => {
      vid.removeEventListener('canplay', onCanPlay)
      vid.removeEventListener('error', onCanPlay)
    })
  })

  createEffect(() => {
    const path = playingPath()
    const vid = videoEl()
    if (!path || !isVideoFile()) {
      if (vid) {
        vid.pause()
        vid.removeAttribute('src')
        vid.load()
      }
    }
  })

  function toggleMinimize() {
    const next = !isMinimized()
    setIsMinimized(next)

    if (next && typeof window !== 'undefined') {
      const store = useVideoPlayerPosition.getState()
      const pos = store.position
      const validatedPos = validatePosition(pos)
      if (pos.x === 0 && pos.y === 0) {
        store.setPosition(getDefaultPosition())
      } else if (validatedPos.x !== pos.x || validatedPos.y !== pos.y) {
        store.setPosition(validatedPos)
      }
    } else if (!next && typeof window !== 'undefined') {
      requestAnimationFrame(() => window.scrollTo({ top: 0, behavior: 'smooth' }))
    }
  }

  function handleAudioOnly() {
    const vid = videoEl()
    const path = playingPath()
    if (!path) return
    if (vid) {
      vid.pause()
      useMediaPlayer.getState().setCurrentTime(vid.currentTime)
    }
    setAudioOnly(true)
    useMediaPlayer.getState().setCurrentFile(path, 'audio')
    useMediaPlayer.getState().setIsPlaying(true)
  }

  function handleClose() {
    const vid = videoEl()
    if (vid) {
      vid.pause()
      vid.removeAttribute('src')
      vid.load()
    }
    closePlayer()
    setIsMinimized(false)
  }

  onCleanup(() => {
    const vid = videoEl()
    if (vid) {
      vid.pause()
      vid.removeAttribute('src')
      vid.load()
    }
  })

  const containerClass = () => (isMinimized() ? 'fixed z-40 w-80' : 'w-full bg-background')

  const containerStyle = (): Record<string, string | undefined> => {
    if (!isMinimized()) return {}
    const p = position()
    return { left: `${p.x}px`, top: `${p.y}px` }
  }

  const videoAreaStyle = (): Record<string, string | undefined> => {
    if (isMinimized()) {
      return {
        'max-height': '180px',
        'min-height': '180px',
        height: '180px',
      }
    }
    return { 'max-height': '70vh', 'aspect-ratio': '16 / 9' }
  }

  let lastScrolledPlayingPath: string | null = null

  createEffect(() => {
    const path = playingPath()
    if (!path || !isVideoFile() || isMinimized()) return
    if (lastScrolledPlayingPath === path) return
    lastScrolledPlayingPath = path
    requestAnimationFrame(() => window.scrollTo({ top: 0, behavior: 'smooth' }))
  })

  return (
    <Show when={isVideoFile() && playingPath()}>
      <div
        class={containerClass()}
        style={containerStyle()}
        data-video-player-inline={isMinimized() ? undefined : 'true'}
      >
        <div
          class={isMinimized() ? 'overflow-hidden rounded-lg border border-border shadow-lg' : ''}
        >
          <div class='bg-black'>
            <div class='border-border z-10 flex items-center justify-between border-b bg-background/90 p-2 backdrop-blur-sm'>
              <span class='flex-1 truncate px-2 text-sm font-medium'>{fileName()}</span>
              <div class='flex items-center gap-1'>
                <button
                  type='button'
                  class='inline-flex h-8 w-8 items-center justify-center rounded-md hover:bg-muted'
                  onClick={() => handleAudioOnly()}
                  aria-label='Audio only mode'
                >
                  <Headphones class='h-4 w-4' size={16} stroke-width={2} />
                </button>
                <button
                  type='button'
                  class='inline-flex h-8 w-8 items-center justify-center rounded-md hover:bg-muted'
                  onClick={() => toggleMinimize()}
                  aria-label={isMinimized() ? 'Maximize player' : 'Minimize player'}
                >
                  <Show
                    when={isMinimized()}
                    fallback={<Minimize2 class='h-4 w-4' size={16} stroke-width={2} />}
                  >
                    <Maximize2 class='h-4 w-4' size={16} stroke-width={2} />
                  </Show>
                </button>
                <button
                  type='button'
                  class='inline-flex h-8 w-8 items-center justify-center rounded-md hover:bg-muted'
                  onClick={() => handleClose()}
                  aria-label='Close player'
                >
                  <X class='h-4 w-4' size={16} stroke-width={2} />
                </button>
              </div>
            </div>
            <video
              ref={(el) => {
                setVideoEl(el ?? undefined)
              }}
              controls
              class='w-full bg-black'
              style={videoAreaStyle()}
            >
              Your browser does not support the video tag.
            </video>
          </div>
        </div>
      </div>
    </Show>
  )
}
