// components/workspace/video-player.tsx
import { useEffect, useRef } from 'react'
import { Headphones, MonitorPlay } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useMediaPlayer } from '@/lib/use-media-player'
import { useMediaUrl } from '@/lib/use-media-url'
import { useNavigationSession } from '@/lib/use-navigation-session'
import { useVideoPlaybackTime } from '@/lib/use-video-playback-time'
import type { NavigationSession } from '@/lib/navigation-session'
import type { SourceContext } from '@/lib/source-context'

interface WorkspaceVideoPlayerProps {
  session?: NavigationSession
  mediaContext?: SourceContext
}

const VIDEO_EXTENSIONS = new Set(['mp4', 'webm', 'ogg', 'mov', 'avi', 'mkv'])

function isVideoPath(path: string | null) {
  const extension = path?.split('.').pop()?.toLowerCase()
  return extension ? VIDEO_EXTENSIONS.has(extension) : false
}

export function VideoPlayer({
  session: sessionProp,
  mediaContext,
}: WorkspaceVideoPlayerProps = {}) {
  const session = useNavigationSession(sessionProp)
  const { state, setAudioOnly } = session
  const videoRef = useRef<HTMLVideoElement>(null)
  const isProgrammaticChange = useRef(false)
  const { getSavedTime, saveTime } = useVideoPlaybackTime()
  const { getMediaUrl } = useMediaUrl(mediaContext)

  const {
    currentFile,
    mediaType,
    isPlaying,
    currentTime,
    volume,
    isMuted,
    setCurrentFile,
    setCurrentTime,
    setDuration,
    setIsPlaying,
  } = useMediaPlayer()

  const playingPath = state.playing
  const audioOnly = state.audioOnly
  const fileName = (playingPath || '').split('/').pop() || 'Video Player'
  const shouldShowVideo = isVideoPath(playingPath)

  useEffect(() => {
    const video = videoRef.current
    if (!video || !playingPath || !shouldShowVideo || audioOnly) {
      return
    }

    const mediaUrl = getMediaUrl(playingPath)
    const fullUrl = new URL(mediaUrl, window.location.origin).href
    if (video.src !== fullUrl) {
      if (currentFile !== playingPath || mediaType !== 'video') {
        setCurrentFile(playingPath, 'video')
      }

      video.src = mediaUrl
      video.load()

      const savedTime = getSavedTime(playingPath)
      const timeToRestore = currentTime > 0 ? currentTime : (savedTime ?? 0)
      if (timeToRestore > 0) {
        const seekToPosition = () => {
          video.currentTime = timeToRestore
          video.removeEventListener('loadedmetadata', seekToPosition)
        }
        video.addEventListener('loadedmetadata', seekToPosition)
      }
    }
  }, [
    audioOnly,
    currentFile,
    currentTime,
    getMediaUrl,
    getSavedTime,
    mediaType,
    playingPath,
    setCurrentFile,
    shouldShowVideo,
  ])

  useEffect(() => {
    const video = videoRef.current
    if (!video || !playingPath || !shouldShowVideo) {
      return
    }

    const updatePositionState = () => {
      setCurrentTime(video.currentTime)
      if (!isNaN(video.duration) && video.duration > 0) {
        saveTime(playingPath, video.currentTime, video.duration)
      }
    }

    const handleLoadedMetadata = () => {
      setDuration(video.duration)
      updatePositionState()
    }

    const handlePlay = () => {
      if (!isProgrammaticChange.current) {
        setIsPlaying(true)
      }
    }

    const handlePause = () => {
      if (!isProgrammaticChange.current) {
        setIsPlaying(false)
      }
    }

    const handleEnded = () => {
      setIsPlaying(false)
    }

    video.addEventListener('loadedmetadata', handleLoadedMetadata)
    video.addEventListener('timeupdate', updatePositionState)
    video.addEventListener('play', handlePlay)
    video.addEventListener('pause', handlePause)
    video.addEventListener('ended', handleEnded)

    return () => {
      video.removeEventListener('loadedmetadata', handleLoadedMetadata)
      video.removeEventListener('timeupdate', updatePositionState)
      video.removeEventListener('play', handlePlay)
      video.removeEventListener('pause', handlePause)
      video.removeEventListener('ended', handleEnded)
    }
  }, [playingPath, saveTime, setCurrentTime, setDuration, setIsPlaying, shouldShowVideo])

  useEffect(() => {
    const video = videoRef.current
    if (
      !video ||
      !shouldShowVideo ||
      audioOnly ||
      currentFile !== playingPath ||
      mediaType !== 'video'
    ) {
      return
    }

    if (isPlaying && video.paused) {
      isProgrammaticChange.current = true
      void video.play().finally(() => {
        isProgrammaticChange.current = false
      })
    } else if (!isPlaying && !video.paused) {
      isProgrammaticChange.current = true
      video.pause()
      isProgrammaticChange.current = false
    }
  }, [audioOnly, currentFile, isPlaying, mediaType, playingPath, shouldShowVideo])

  useEffect(() => {
    const video = videoRef.current
    if (
      !video ||
      !shouldShowVideo ||
      audioOnly ||
      currentFile !== playingPath ||
      mediaType !== 'video'
    ) {
      return
    }

    // Allow taskbar controls to seek the active video without fighting normal timeupdate sync.
    if (Math.abs(video.currentTime - currentTime) > 0.75) {
      video.currentTime = currentTime
    }
  }, [audioOnly, currentFile, currentTime, mediaType, playingPath, shouldShowVideo])

  useEffect(() => {
    const video = videoRef.current
    if (!video || !shouldShowVideo || audioOnly) {
      return
    }

    video.muted = isMuted
    video.volume = isMuted ? 0 : volume
  }, [audioOnly, isMuted, shouldShowVideo, volume])

  if (!playingPath || !shouldShowVideo) {
    return (
      <div className='flex h-full items-center justify-center bg-muted/20 p-6 text-center'>
        <div className='space-y-3'>
          <div className='mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-muted'>
            <MonitorPlay className='h-6 w-6 text-muted-foreground' />
          </div>
          <div className='text-sm font-medium'>No video is playing</div>
          <div className='text-sm text-muted-foreground'>
            Start a video from any browser window to open it here.
          </div>
        </div>
      </div>
    )
  }

  if (audioOnly) {
    return (
      <div className='flex h-full items-center justify-center bg-muted/20 p-6 text-center'>
        <div className='space-y-3'>
          <div className='mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-muted'>
            <Headphones className='h-6 w-6 text-muted-foreground' />
          </div>
          <div className='text-sm font-medium'>{fileName} is playing in audio mode</div>
          <div className='text-sm text-muted-foreground'>
            Restore video playback from the taskbar audio controls or here.
          </div>
          <div>
            <Button variant='outline' onClick={() => setAudioOnly(false)}>
              <MonitorPlay className='h-4 w-4' />
              Show video
            </Button>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className='relative h-full w-full bg-black'>
      <div className='absolute top-3 right-3 z-10'>
        <Button variant='secondary' size='sm' onClick={() => setAudioOnly(true)}>
          <Headphones className='h-4 w-4' />
          Listen only
        </Button>
      </div>
      <video ref={videoRef} controls className='h-full w-full bg-black object-contain'>
        Your browser does not support the video tag.
      </video>
    </div>
  )
}

// src/media/VideoPlayer.tsx
import { useMediaPlayer } from '@/lib/use-media-player'
import { useVideoPlaybackTime } from '@/lib/use-video-playback-time'
import {
  getDefaultPosition,
  useVideoPlayerPosition,
  validatePosition,
} from '@/lib/use-video-player-position'
import { createEffect, createMemo, createSignal, onCleanup, onMount, Show } from 'solid-js'
import Headphones from 'lucide-solid/icons/headphones'
import Maximize2 from 'lucide-solid/icons/maximize-2'
import Minimize2 from 'lucide-solid/icons/minimize-2'
import X from 'lucide-solid/icons/x'
import { createUrlSearchParamsMemo, useBrowserHistory } from '../browser-history'
import { closePlayer, setAudioOnly } from '../lib/url-state-actions'
import { buildAdminMediaUrl } from '../lib/build-media-url'

const VIDEO_EXTENSIONS = ['mp4', 'webm', 'ogg', 'mov', 'avi', 'mkv', 'm4v']

export function VideoPlayer() {
  const history = useBrowserHistory()
  const urlSearchParams = createUrlSearchParamsMemo(history)

  const playingPath = createMemo(() => urlSearchParams().get('playing'))

  const audioOnly = createMemo(() => urlSearchParams().get('audioOnly') === 'true')

  const extension = createMemo(() => (playingPath() || '').split('.').pop()?.toLowerCase() || '')
  const isVideoFile = createMemo(
    () => !!playingPath() && VIDEO_EXTENSIONS.includes(extension()) && !audioOnly(),
  )

  const mediaUrl = createMemo(() => {
    const path = playingPath()
    if (!path) return ''
    return buildAdminMediaUrl(path)
  })

  const fileName = createMemo(() => (playingPath() || '').split('/').pop() || '')

  const [isMinimized, setIsMinimized] = createSignal(false)
  const [position, setPositionView] = createSignal(useVideoPlayerPosition.getState().position)

  onMount(() => {
    const unsub = useVideoPlayerPosition.subscribe((s) => {
      setPositionView(s.position)
    })
    onCleanup(unsub)
  })

  const [videoEl, setVideoEl] = createSignal<HTMLVideoElement | undefined>()

  createEffect(() => {
    const path = playingPath()
    const url = mediaUrl()
    const vid = videoEl()
    if (!path || !isVideoFile() || !vid || !url) return

    useMediaPlayer.getState().setCurrentFile(path, 'video')

    const targetHref = new URL(url, window.location.origin).href
    const srcMismatch = vid.src !== targetHref

    const finish = () => {
      const st = useMediaPlayer.getState()
      const storeT = st.currentFile === path && st.mediaType === 'video' ? st.currentTime : 0
      const savedT = useVideoPlaybackTime.getState().getSavedTime(path) ?? 0
      const t = storeT > 0 ? storeT : savedT
      if (t > 0) {
        try {
          vid.currentTime = t
        } catch {
          /* ignore */
        }
      }
      void vid.play().catch(() => {})
    }

    let onCanPlay: () => void = () => {}

    if (srcMismatch) {
      onCanPlay = () => {
        vid.removeEventListener('canplay', onCanPlay)
        vid.removeEventListener('error', onCanPlay)
        finish()
      }
      vid.addEventListener('canplay', onCanPlay)
      vid.addEventListener('error', onCanPlay)
      vid.pause()
      vid.src = targetHref
      vid.load()
    } else {
      finish()
    }

    onCleanup(() => {
      vid.removeEventListener('canplay', onCanPlay)
      vid.removeEventListener('error', onCanPlay)
    })
  })

  createEffect(() => {
    const path = playingPath()
    const vid = videoEl()
    if (!path || !isVideoFile()) {
      if (vid) {
        vid.pause()
        vid.removeAttribute('src')
        vid.load()
      }
    }
  })

  function toggleMinimize() {
    const next = !isMinimized()
    setIsMinimized(next)

    if (next && typeof window !== 'undefined') {
      const store = useVideoPlayerPosition.getState()
      const pos = store.position
      const validatedPos = validatePosition(pos)
      if (pos.x === 0 && pos.y === 0) {
        store.setPosition(getDefaultPosition())
      } else if (validatedPos.x !== pos.x || validatedPos.y !== pos.y) {
        store.setPosition(validatedPos)
      }
    } else if (!next && typeof window !== 'undefined') {
      requestAnimationFrame(() => window.scrollTo({ top: 0, behavior: 'smooth' }))
    }
  }

  function handleAudioOnly() {
    const vid = videoEl()
    const path = playingPath()
    if (!path) return
    if (vid) {
      vid.pause()
      useMediaPlayer.getState().setCurrentTime(vid.currentTime)
    }
    setAudioOnly(true)
    useMediaPlayer.getState().setCurrentFile(path, 'audio')
    useMediaPlayer.getState().setIsPlaying(true)
  }

  function handleClose() {
    const vid = videoEl()
    if (vid) {
      vid.pause()
      vid.removeAttribute('src')
      vid.load()
    }
    closePlayer()
    setIsMinimized(false)
  }

  onCleanup(() => {
    const vid = videoEl()
    if (vid) {
      vid.pause()
      vid.removeAttribute('src')
      vid.load()
    }
  })

  const containerClass = () => (isMinimized() ? 'fixed z-40 w-80' : 'w-full bg-background')

  const containerStyle = (): Record<string, string | undefined> => {
    if (!isMinimized()) return {}
    const p = position()
    return { left: `${p.x}px`, top: `${p.y}px` }
  }

  const videoAreaStyle = (): Record<string, string | undefined> => {
    if (isMinimized()) {
      return {
        'max-height': '180px',
        'min-height': '180px',
        height: '180px',
      }
    }
    return { 'max-height': '70vh', 'aspect-ratio': '16 / 9' }
  }

  let lastScrolledPlayingPath: string | null = null

  createEffect(() => {
    const path = playingPath()
    if (!path || !isVideoFile() || isMinimized()) return
    if (lastScrolledPlayingPath === path) return
    lastScrolledPlayingPath = path
    requestAnimationFrame(() => window.scrollTo({ top: 0, behavior: 'smooth' }))
  })

  return (
    <Show when={isVideoFile() && playingPath()}>
      <div
        class={containerClass()}
        style={containerStyle()}
        data-video-player-inline={isMinimized() ? undefined : 'true'}
      >
        <div
          class={isMinimized() ? 'overflow-hidden rounded-lg border border-border shadow-lg' : ''}
        >
          <div class='bg-black'>
            <div class='border-border z-10 flex items-center justify-between border-b bg-background/90 p-2 backdrop-blur-sm'>
              <span class='flex-1 truncate px-2 text-sm font-medium'>{fileName()}</span>
              <div class='flex items-center gap-1'>
                <button
                  type='button'
                  class='inline-flex h-8 w-8 items-center justify-center rounded-md hover:bg-muted'
                  onClick={() => handleAudioOnly()}
                  aria-label='Audio only mode'
                >
                  <Headphones class='h-4 w-4' size={16} stroke-width={2} />
                </button>
                <button
                  type='button'
                  class='inline-flex h-8 w-8 items-center justify-center rounded-md hover:bg-muted'
                  onClick={() => toggleMinimize()}
                  aria-label={isMinimized() ? 'Maximize player' : 'Minimize player'}
                >
                  <Show
                    when={isMinimized()}
                    fallback={<Minimize2 class='h-4 w-4' size={16} stroke-width={2} />}
                  >
                    <Maximize2 class='h-4 w-4' size={16} stroke-width={2} />
                  </Show>
                </button>
                <button
                  type='button'
                  class='inline-flex h-8 w-8 items-center justify-center rounded-md hover:bg-muted'
                  onClick={() => handleClose()}
                  aria-label='Close player'
                >
                  <X class='h-4 w-4' size={16} stroke-width={2} />
                </button>
              </div>
            </div>
            <video
              ref={(el) => {
                setVideoEl(el ?? undefined)
              }}
              controls
              class='w-full bg-black'
              style={videoAreaStyle()}
            >
              Your browser does not support the video tag.
            </video>
          </div>
        </div>
      </div>
    </Show>
  )
}
